// UTILITY_TINY.C - rz-ghidra decompilation
// Source: chunk_37.bin
// Functions: 1
// Generated by decompile_all.py
//
// NOTE: 16-bit x86 real mode. Pointer arithmetic uses 16-bit segments.
// CS:0x10C = chunk loader, 0xFF00+ = game state globals
//
