/* ====================================================================== */
/* STRINGS                                                             */
/* ====================================================================== */

static const char *STR_0x3c = "eDÎHÎþCãeCGIG»ûÿIGîögCã"; // [ibm037]
static const char *STR_0x5b = "dDGQeCH"; // [ibm037]
static const char *STR_0x7b = "cDGfCGQeCÃQiûÿãÃQfCGH"; // [ibm037]
static const char *STR_0xf0 = "ýCEGöfCG"; // [ibm037]
static const char *STR_0x14b = "«CEGIfCeùÿGãH"; // [ibm037]
static const char *STR_0x16f = "eDGFgCEGöfCGöýDîFeCãdCGãöfDEãQeCîfDGöýDîH"; // [ibm037]
static const char *STR_0x19a = "cDGHQcDGãöfDãH"; // [ibm037]
static const char *STR_0x1b4 = "cDgCÃQeCödCGî"; // [ibm037]
static const char *STR_0x1c3 = "cCãöfCÖGFfCG"; // [ibm037]
static const char *STR_0x1d1 = "dDGfCîöfDeCGGHQRQdCIã"; // [ibm037]
static const char *STR_0x1e8 = "cCãHQeD"; // [ibm037]
static const char *STR_0x1f6 = "dCîýCGãöfDG"; // [ibm037]
static const char *STR_0x207 = "öþCGöeCîýCGGöjC"; // [ibm037]
static const char *STR_0x223 = "«CGî&BAB&BAB&aCã"; // [ibm037]
static const char *STR_0x234 = "QýDGFeCã"; // [ibm037]
static const char *STR_0x24e = "cCãöýCGGH"; // [ibm037]
static const char *STR_0x26c = "«DGãQfCGH"; // [ibm037]
static const char *STR_0x277 = "eÔGI±CãeCîHQ»CGîfCî"; // [ibm037]
static const char *STR_0x299 = "«CGãIQeDîHQdÔ"; // [ibm037]
static const char *STR_0x2e9 = "GEGÖIoCGãöfDG"; // [ibm037]
static const char *STR_0x304 = "QÎnCGGFG"; // [ibm037]
static const char *STR_0x339 = "fCîeCîmDGGIöfCG"; // [ibm037]
static const char *STR_0x34b = "gRgCGIfDEGImCGãöfCîFQdÔ"; // [ibm037]
static const char *STR_0x364 = "gCGQfDîQlCGGöHQeDãHQeÔ"; // [ibm037]
static const char *STR_0x37f = "cCGgCãH"; // [ibm037]
static const char *STR_0x399 = "HGQdDQgCîQlCGãöfDG"; // [ibm037]
static const char *STR_0x3b7 = "kDGãF°CEî BAB gCÖG"; // [ibm037]
static const char *STR_0x3ca = "QlCGîøBABAB B aCÃþCãömCEãH"; // [ibm037]
static const char *STR_0x3eb = "ðCGInCGîIGí"; // [ibm037]
static const char *STR_0x3fd = "HQýCãFmCG"; // [ibm037]
static const char *STR_0x413 = "öþCEGHQdDþDGÃö"; // [ibm037]
static const char *STR_0x429 = "GfDFfCã"; // [ibm037]
static const char *STR_0x441 = "dCîIfDöfDGöfCF»CFãî.C.îHFQeCEî"; // [ibm037]
static const char *STR_0x48d = "cCîHQýCãöeCGF«CîhCãEGFeCîöþCÖGQeCî"; // [ibm037]
static const char *STR_0x4b1 = "eDFÃAB dCEÃQdCîIþCÖH"; // [ibm037]
static const char *STR_0x4c7 = "cDãHQfCî"; // [ibm037]
static const char *STR_0x4d0 = "GQgDîHGQdDî"; // [ibm037]
static const char *STR_0x4f5 = "»CEGöeC"; // [ibm037]
static const char *STR_0x50d = "eCGFfCFÃ"; // [ibm037]
static const char *STR_0x527 = "DãöeDîHGQa«CãFeC"; // [ibm037]
static const char *STR_0x538 = "GHfCEGfCGFfDGöfDîöc«DîQdCÃQdCîeCG"; // [ibm037]
static const char *STR_0x55c = "cCGFfCîFc«CãH"; // [ibm037]
static const char *STR_0x57e = "cCEîQb«CEãQdCãöHQdCHG"; // [ibm037]
static const char *STR_0x5ae = "GeCGQfCGQfCGIGQdCî"; // [ibm037]
static const char *STR_0x5d2 = "Qc«CGgCÃ BABøBAB&BAB bDãFeCîQc«CGFfCî"; // [ibm037]
static const char *STR_0x619 = "QdCîdA AfCã"; // [ibm037]
static const char *STR_0x630 = "QeCîAB «CîeCãHÃHî"; // [ibm037]
static const char *STR_0x648 = "eCîdaDGFfCîeDã"; // [ibm037]
static const char *STR_0x658 = "eCG.ã.ãEÃHG"; // [ibm037]
static const char *STR_0x66b = "baDGHãdDîqDGÖî"; // [ibm037]
static const char *STR_0x67b = "«DîQcaCÃQcDGEG-B&B-BAB&B&aCGÖîðCãödaCã"; // [ibm037]
static const char *STR_0x6c4 = "dDGFeDîQcaCG"; // [ibm037]
static const char *STR_0x6e3 = "cCãFdaCã"; // [ibm037]
static const char *STR_0x6f6 = "iDÖãFeCGHQdCîdaCãQeCÎöHG.H"; // [ibm037]
static const char *STR_0x725 = "baDGöfDGIã"; // [ibm037]
static const char *STR_0x73f = "dCGFeCîQcaCGoDÎQfCGÖGQeDãQdCîdaCIGøBAB-B B-bCîHQfDãöfDGH"; // [ibm037]
static const char *STR_0x779 = "cCãQdaCãQnCîögDãFfCãQdCGIQdaCãeDGQþDîFgCãH"; // [ibm037]
static const char *STR_0x7a5 = "dCEGQdCGöeaCGH"; // [ibm037]
static const char *STR_0x7c6 = "cCGöeDGöeaDãQdCãþCîFQfCîQeCGfCG"; // [ibm037]
static const char *STR_0x7e7 = "daDGöeCãFýCGEãQfCãöfCGFQdCG"; // [ibm037]
static const char *STR_0x804 = "caCGfCGEFýCîögDãIfCã"; // [ibm037]
static const char *STR_0x81a = "cCGQeDãöeDÃQ»CãFhCãöfCãH"; // [ibm037]
static const char *STR_0x834 = "bDGfÃQdCÃ"; // [ibm037]
static const char *STR_0x848 = "dCîFcCöeDEã"; // [ibm037]
static const char *STR_0x856 = "bDîöðDEãFgCGHQfDÎHãöeCãH"; // [ibm037]
static const char *STR_0x886 = "eCîöeCGIãQ»DÃQfCîfC"; // [ibm037]
static const char *STR_0x8ca = "QfCãgCGIGöðCãIhCî"; // [ibm037]
static const char *STR_0x8e1 = "ögCãöfDîöðCGFHFgDãHQeD"; // [ibm037]
static const char *STR_0x901 = "dCIãýCÃQfDãöQeCGEÃH"; // [ibm037]
static const char *STR_0x94f = "cCGIGHFGIÎ"; // [ibm037]
static const char *STR_0x95b = "eCãöfCãçGFhCãFfCîQdCîFHG"; // [ibm037]
static const char *STR_0x997 = "fDîHQdCãfDîHîEÃFfCã"; // [ibm037]
static const char *STR_0x9ab = "fCEÎQgCEîeDãöeCÃ."; // [ibm037]
static const char *STR_0x9c6 = "dCÎöhCEãöeCîQdCEG"; // [ibm037]
static const char *STR_0x9d9 = "dDîQeDîQeCÃIiCîfCIH"; // [ibm037]
static const char *STR_0x9ee = "cCãHQeCG"; // [ibm037]
static const char *STR_0xa13 = "dCGögCîQeDãçGFhDî"; // [ibm037]
static const char *STR_0xa26 = "cCãöeCGögDãFfCîfC"; // [ibm037]
static const char *STR_0xa40 = "cCãfCGFgDã"; // [ibm037]
static const char *STR_0xa58 = "dCãöfDãFeDGH"; // [ibm037]
static const char *STR_0xa72 = "ögCîfDGH"; // [ibm037]
static const char *STR_0xab9 = "QfCÃeCGIfCãH"; // [ibm037]
static const char *STR_0xad5 = "GQdCãFeCEãQiCIÎ"; // [ibm037]
static const char *STR_0xb01 = "öhCGEãöGögCîfCIãQdDãQ«C"; // [ibm037]
static const char *STR_0xb1a = "FgCGIãHGhCã.eCîlCãEîH"; // [ibm037]
static const char *STR_0xb41 = " B hCÃHG"; // [ibm037]
static const char *STR_0xb65 = "QfCîHQdCÎFGá¸C"; // [ibm037]
static const char *STR_0xb9a = "gCÃQdCG"; // [ibm037]
static const char *STR_0xc0f = "cDÎQgDGIîöGIG"; // [ibm037]
static const char *STR_0xc1e = "cCìGQf÷EîGHG"; // [ibm037]
static const char *STR_0xc93 = "QdDEîQabCãQcDGöfCGEÃIfCã&B BAB aCÃeCãH"; // [ibm037]
static const char *STR_0xcc0 = "QGFîFeC"; // [ibm037]
static const char *STR_0xccf = "Q»CÃeCîcbDIîFHîH"; // [ibm037]
static const char *STR_0xce1 = "cCÎHGQeDG"; // [ibm037]
static const char *STR_0xcec = "cCGQdDãIFQdCã"; // [ibm037]
static const char *STR_0xd2f = "cû\\îeCGH"; // [ibm037]
static const char *STR_0xd41 = "qCGQeÔQeûúIãeDã"; // [ibm037]
static const char *STR_0xd8b = "DGFiDGQfCãðûÿãöeCEGdbDGHQeDîQgCã"; // [ibm037]
static const char *STR_0xdc7 = "fCGQfDG"; // [ibm037]
static const char *STR_0xe18 = "cDãdbCEGöeCÎ"; // [ibm037]
static const char *STR_0xefd = "Gö«DGÖãHGQhQdûÿãH"; // [ibm037]
static const char *STR_0xf34 = "bbDîQdCîQ«DG"; // [ibm037]
static const char *STR_0xf98 = "bDQdDGEÖGöhCÖeûÿGFfûÿFdbCGIfDãQeDFdCãÖHGQgCGeûÿGH"; // [ibm037]
static const char *STR_0xfd1 = "bbCGöfCGöfCGQcCãÖFH"; // [ibm037]
static const char *STR_0xfec = "cûÿîQdû\\GQcbDãöeCãöeDGdCãÖã"; // [ibm037]
static const char *STR_0x1019 = "ãQeCGHöeDGdC"; // [ibm037]
static const char *STR_0x1041 = "dCãöeCQdC"; // [ibm037]
static const char *STR_0x105c = "abCãfCãöeCGQcD"; // [ibm037]
static const char *STR_0x107c = "bCGHGeCGH"; // [ibm037]
static const char *STR_0x1087 = "dDGQcDãÖGöeûÿã"; // [ibm037]
static const char *STR_0x10a4 = "dCãöeCGH"; // [ibm037]
static const char *STR_0x10ae = "aCGIÖGQeûÿî"; // [ibm037]
static const char *STR_0x10c5 = "bbDGQfCîeCÃFîÖãQdûÿG"; // [ibm037]
static const char *STR_0x1105 = "dûÿGöcB&BABAcDGÖöeC"; // [ibm037]
static const char *STR_0x114d = "ûÿãöbQ«CÖGFeCEG"; // [ibm037]
static const char *STR_0x11e0 = "î&BAB BAcûÿã"; // [ibm037]
static const char *STR_0x1285 = "FeDãFdûÿGRQdûÿãFeûÿã"; // [ibm037]
static const char *STR_0x1347 = "GÖãbcCG"; // [ibm037]
static const char *STR_0x1366 = "-  aDGÖãbcCãQdûÿãFdCÖGödûÿH"; // [ibm037]
static const char *STR_0x138f = "cCGfûÿãFdCÖGHQcûÿãRQcû\\î"; // [ibm037]
static const char *STR_0x13a9 = "ðDÃQacDGfûÿIîQaDGÖGödûÿãR"; // [ibm037]
static const char *STR_0x13ca = "h¹ÿãöbcCQfûÿîHFHÃ"; // [ibm037]
static const char *STR_0x143b = "EîFQfûÿGHG"; // [ibm037]
static const char *STR_0x152b = "dûÿãFbcCEG"; // [ibm037]
static const char *STR_0x1549 = "eûÿãFbcDîAB BA -aCã"; // [ibm037]
static const char *STR_0x157e = "ögûÿIGöbcCGHî"; // [ibm037]
static const char *STR_0x158f = "gCî B BAB aCî.bDÎögûÿGI"; // [ibm037]
static const char *STR_0x160b = "FHGôÃQeC"; // [ibm037]
static const char *STR_0x1669 = "adCQgQfCÎö"; // [ibm037]
static const char *STR_0x1686 = "dCQþCGIÃQeDGIgDÎögûÿãôQac÷G"; // [ibm037]
static const char *STR_0x16ab = "eDãFfDÃHG"; // [ibm037]
static const char *STR_0x16d2 = "dCGEãFH"; // [ibm037]
static const char *STR_0x16ff = "baDGQfÔÖGÖH"; // [ibm037]
static const char *STR_0x172b = "QHÃöiCãFfCÃöhCGôdaDG"; // [ibm037]
static const char *STR_0x174d = "gDîQeCÎFgCHG"; // [ibm037]
static const char *STR_0x175b = "baCIfûÿ"; // [ibm037]
static const char *STR_0x1774 = "eCGQdaCG"; // [ibm037]
static const char *STR_0x179d = "þDGQgCÃ"; // [ibm037]
static const char *STR_0x17a5 = "FþAB-BAaûÿÎ"; // [ibm037]
static const char *STR_0x17b6 = " B B&BAB iûÿÎ&B B&BAB BøB-aDGôîFþFhûÿÃ"; // [ibm037]
static const char *STR_0x18a2 = "ÃQaDGHGQcCGîHG"; // [ibm037]
static const char *STR_0x18c2 = "cCGQdCGÎö"; // [ibm037]
static const char *STR_0x18df = "fCãQcCEÃöfCGH"; // [ibm037]
static const char *STR_0x18f2 = "ÖÎlDGeDGÃ"; // [ibm037]
static const char *STR_0x1929 = "jCQeCGîökCGEÎ"; // [ibm037]
static const char *STR_0x193f = "fDQeCGÎABAB-B B BAaC"; // [ibm037]
static const char *STR_0x1971 = "GFðCGÎQeDGá"; // [ibm037]
static const char *STR_0x1afc = "Cavern of Cementar"; // [ascii]

/* ====================================================================== */
/* 0x0: fcn.00000000 */
/* ====================================================================== */

// WARNING: Control flow encountered bad instruction data
// WARNING: Unknown calling convention -- yet parameter storage is locked

void fcn.00000000(int16_t arg3)
{
    char in_AL;
    int16_t in_BX;
    int16_t unaff_SI;
    undefined2 unaff_DS;
    bool in_OF;
    
    if (in_OF) {
        *(char *)(in_BX + unaff_SI) = *(char *)(in_BX + unaff_SI) + in_AL;
    // WARNING: Bad instruction - Truncating control flow here
        halt_baddata();
    }
    return;
}

