// Export all decompiled functions to C files
//@category Export

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.*;
import java.io.*;

public class ExportDecompiledC extends GhidraScript {

    @Override
    public void run() throws Exception {
        DecompInterface decompiler = new DecompInterface();
        decompiler.openProgram(currentProgram);

        String outputDir = getScriptArgs().length > 0 ?
            getScriptArgs()[0] : "decompiled_output";
        File outDir = new File(outputDir);
        outDir.mkdirs();

        String baseName = currentProgram.getName().replaceAll("\\.[^.]+$", "");
        File outputFile = new File(outDir, baseName + "_decompiled.c");

        println("Decompiling to: " + outputFile.getAbsolutePath());

        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile))) {
            writer.println("/* Decompiled from " + currentProgram.getName() + " */");
            writer.println("/* Generated by Ghidra */");
            writer.println();

            FunctionIterator functions = currentProgram.getFunctionManager().getFunctions(true);
            int count = 0;

            for (Function function : functions) {
                monitor.checkCancelled();
                monitor.setMessage("Decompiling " + function.getName());

                DecompileResults results = decompiler.decompileFunction(function, 30, monitor);

                if (results != null && results.decompileCompleted()) {
                    writer.println("// Address: " + function.getEntryPoint());
                    writer.println(results.getDecompiledFunction().getC());
                    writer.println();
                    count++;
                } else {
                    writer.println("// Failed to decompile: " + function.getName());
                    writer.println("// Address: " + function.getEntryPoint());
                    writer.println();
                }
            }

            println("Successfully decompiled " + count + " functions");
        }

        decompiler.dispose();
    }
}
