coverage:
  status:
    project:
      default:
        branches:
          - dev
          - 'release-*'
        if_not_found: failure
        target: auto
        threshold: 0.5%
    patch:
      default:
        if_not_found: success
        target: auto
        threshold: 0.5%
ignore:
  - "binrz/rz-test"
  - ".github"
  - "doc"
  - "examples"
  - "man"
  - "mk"
  - "subprojects/mpc"
  - "subprojects/nettle"
  - "subprojects/packagefiles"
  - "subprojects/xxhash"
  - "subprojects/yxml"
  - "sys"
  - "test"

comment:
  layout: "header, files, components, footer"
  require_changes: true
