/* Decompiled from game.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:02b0

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __cdecl16near
FUN_0000_02b0(int param_1,uint param_2,byte param_3,undefined2 param_4,undefined2 param_5,
             undefined1 param_6)

{
  byte *pbVar1;
  uint *puVar2;
  char *pcVar3;
  byte bVar4;
  undefined4 uVar5;
  byte bVar6;
  byte bVar7;
  byte bVar8;
  undefined2 in_AX;
  undefined1 uVar11;
  undefined2 uVar10;
  undefined2 in_DX;
  int in_BX;
  int unaff_BP;
  int unaff_SI;
  undefined4 *puVar12;
  undefined4 *in_EDI;
  undefined2 unaff_SS;
  undefined2 unaff_DS;
  long in_FS_OFFSET;
  byte in_AF;
  uint uStack_2;
  char cVar9;
  
  pbVar1 = (byte *)(in_BX + (int)(undefined4 *)in_EDI);
  bVar4 = *pbVar1;
  bVar6 = (byte)in_AX;
  *pbVar1 = *pbVar1 + bVar6;
  uVar5 = in(in_DX);
  *in_EDI = uVar5;
  puVar2 = (uint *)(in_BX + 0x61);
  *puVar2 = *puVar2 + (uint)CARRY1(bVar4,bVar6) * -(*puVar2 & 3);
  puVar12 = (undefined4 *)(in_EDI + 1);
  pcVar3 = (char *)(in_BX + (int)puVar12);
  *pcVar3 = *pcVar3 + bVar6;
  uStack_2 = 0x6367;
  if (*pcVar3 != '\0') {
    *(undefined1 *)0xa2e9 = param_6;
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  pbVar1 = (byte *)(unaff_BP + (int)puVar12);
  bVar4 = *pbVar1;
  *pbVar1 = *pbVar1 + bVar6;
  puVar2 = (uint *)((long)in_EDI + in_FS_OFFSET + 0x65);
  *puVar2 = *puVar2 + (uint)CARRY1(bVar4,bVar6) * (2 - (*puVar2 & 3));
  *(char *)(in_BX + unaff_SI) = *(char *)(in_BX + unaff_SI) + bVar6;
  bVar6 = bVar6 + 0x67;
  pbVar1 = (byte *)(in_BX + unaff_SI);
  bVar4 = *pbVar1;
  *pbVar1 = *pbVar1 + bVar6;
  uVar10 = in(in_DX);
  *(undefined2 *)(in_EDI + 1) = uVar10;
  puVar2 = (uint *)(in_BX + 0x61);
  *puVar2 = *puVar2 + (uint)CARRY1(bVar4,bVar6) * (2 - (*puVar2 & 3));
  *(char *)(in_BX + unaff_SI) = *(char *)(in_BX + unaff_SI) + bVar6;
  if (CONCAT11((char)((uint)in_AX >> 8),bVar6) != -0x6467) {
    pbVar1 = (byte *)(param_1 + 0x6367);
    bVar4 = *pbVar1;
    bVar7 = (byte)param_4;
    *pbVar1 = *pbVar1 + bVar7;
    bVar6 = 9 < (bVar7 & 0xf) | in_AF;
    uVar11 = (undefined1)((uint)param_4 >> 8);
    bVar8 = bVar7 + bVar6 * -6;
    cVar9 = bVar8 + (0x9f < bVar8 | CARRY1(bVar4,bVar7) | bVar6 * (bVar8 < 6)) * -0x60;
    uVar10 = CONCAT11(uVar11,cVar9);
    *(uint *)0x534d = *(uint *)0x534d ^ 0x6366;
    *(char *)(param_1 + 0x6368) = *(char *)(param_1 + 0x6368) + cVar9;
    *(uint *)0x63af = *(uint *)0x63af ^ param_2;
    *(uint *)0x534d = *(uint *)0x534d ^ 0x6365;
    *(char *)(param_1 + 0x6368) = *(char *)(param_1 + 0x6368) + cVar9;
    *(byte *)0x63af = *(byte *)0x63af ^ param_3;
    *(char *)(param_1 + 0x6368) = *(char *)(param_1 + 0x6368) + cVar9;
    *(char *)(param_1 + 0x6368) = *(char *)(param_1 + 0x6368) + cVar9;
    *(char *)(param_1 + 0x6369) = *(char *)(param_1 + 0x6369) + cVar9;
    if ((param_2 & 0x7f00) == 0) {
      return CONCAT11(uVar11,*(undefined1 *)0xff00);
    }
    uStack_2 = (uint)*(byte *)0xa0;
  }
  do {
    uVar10 = (*_DAT_0000_203e)();
    uStack_2 = uStack_2 - 1;
  } while (uStack_2 != 0);
  return uVar10;
}



// Address: 0000:03a5

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_03a5(void)

{
  uint uVar1;
  undefined2 unaff_DS;
  
  if (*(char *)0xa0 == '\0') {
    return;
  }
  uVar1 = (uint)*(byte *)0xa0;
  do {
    (*_DAT_0000_203e)();
    uVar1 = uVar1 - 1;
  } while (uVar1 != 0);
  return;
}



// Address: 0000:03e5

void FUN_0000_03e5(void)

{
  undefined2 unaff_DS;
  
                    /* WARNING: Could not recover jumptable at 0x000003ed. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)*(byte *)0xff14 * 2 + -0x5c0e))();
  return;
}



