/* Decompiled from zeliad.exe */
/* Generated by Ghidra */

// Address: 1000:0000

/* WARNING (jumptable): Stack frame is not setup normally: Input value of stackpointer is not used
    */
/* WARNING: Stack frame is not setup normally: Input value of stackpointer is not used */
/* WARNING: This function may have set the stack pointer */

void entry(void)

{
  byte *pbVar1;
  undefined1 *puVar2;
  code *pcVar3;
  byte bVar4;
  int iVar5;
  int iVar6;
  undefined2 uVar7;
  undefined1 *puVar8;
  undefined1 *puVar9;
  byte *pbVar10;
  undefined1 *puVar11;
  byte *pbVar12;
  undefined2 unaff_ES;
  undefined2 uVar13;
  undefined1 uVar14;
  bool bVar15;
  
  uVar13 = 0x109f;
  puVar8 = (undefined1 *)0x2000;
  pcVar3 = (code *)swi(0x21);
  bVar4 = (*pcVar3)();
  uVar14 = bVar4 < 2;
  if ((bool)uVar14) {
    pcVar3 = (code *)swi(0x20);
    (*pcVar3)();
  }
  *(undefined2 *)(puVar8 + -2) = 0x13;
  FUN_1000_05f9();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  if ((bool)uVar14) {
    *(undefined2 *)(puVar8 + -2) = 0x20;
    FUN_1000_0520();
    pcVar3 = (code *)swi(0x21);
    (*pcVar3)();
  }
  *(undefined2 *)(puVar8 + -2) = 0x2a;
  FUN_1000_0390();
  if ((bool)uVar14) {
    FUN_1000_04ca();
    return;
  }
  *(undefined2 *)(puVar8 + -2) = 0x32;
  FUN_1000_03cc();
  *(undefined2 *)(puVar8 + -2) = 0x35;
  FUN_1000_0390();
  if ((bool)uVar14) {
    FUN_1000_04ca();
    return;
  }
  *(undefined2 *)(puVar8 + -2) = 0x3d;
  FUN_1000_0443();
  *(undefined2 *)(puVar8 + -2) = 0x40;
  FUN_1000_0390();
  if ((bool)uVar14) {
    FUN_1000_04ca();
    return;
  }
  *(undefined2 *)(puVar8 + -2) = 0x48;
  FUN_1000_047c();
  *(undefined2 *)(puVar8 + -2) = 0x4b;
  FUN_1000_0390();
  if ((bool)uVar14) {
    FUN_1000_04ca();
    return;
  }
  *(undefined2 *)(puVar8 + -2) = 0x53;
  FUN_1000_0493();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  uVar7 = 0x4000;
  pcVar3 = (code *)swi(0x21);
  iVar5 = (*pcVar3)();
  if ((bool)uVar14) {
    if (iVar5 == 8) {
      pcVar3 = (code *)swi(0x21);
      (*pcVar3)();
      pcVar3 = (code *)swi(0x21);
      (*pcVar3)();
    }
    pcVar3 = (code *)swi(0x21);
    (*pcVar3)();
    pcVar3 = (code *)swi(0x21);
    iVar5 = (*pcVar3)();
  }
  DAT_1000_08af = iVar5;
  *(undefined2 *)(puVar8 + -2) = 0x83;
  FUN_1000_0385();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  bVar15 = false;
  puVar9 = puVar8;
  if (DAT_1000_08e8 != '\0') {
    DAT_1000_08c4 = 0x109f;
    uVar7 = 0x8c6;
    pcVar3 = (code *)swi(0x21);
    DAT_1000_08c2 = puVar8;
    (*pcVar3)();
    uVar13 = DAT_1000_08c4;
    puVar9 = DAT_1000_08c2;
    if (bVar15) {
      *(undefined2 *)(DAT_1000_08c2 + -2) = 0xbb;
      FUN_1000_0520();
      pcVar3 = (code *)swi(0x21);
      (*pcVar3)();
    }
  }
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  DAT_1000_08b1._0_2_ = uVar7;
  DAT_1000_08b1._2_2_ = unaff_ES;
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  DAT_1000_08b5._0_2_ = uVar7;
  DAT_1000_08b5._2_2_ = unaff_ES;
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  DAT_1000_08b9 = uVar7;
  DAT_1000_08bb = unaff_ES;
  (*pcVar3)();
  iVar5 = DAT_1000_08af;
  DAT_1000_08bd = uVar7;
  DAT_1000_08bf = unaff_ES;
  *(undefined2 *)0xff00 = 0x2d9;
  *(undefined2 *)0xff02 = 0x1000;
  uVar7 = DAT_1000_08b1._2_2_;
  *(undefined2 *)0xff04 = (undefined2)DAT_1000_08b1;
  *(undefined2 *)0xff06 = uVar7;
  uVar7 = DAT_1000_08b5._2_2_;
  *(undefined2 *)0xff79 = (undefined2)DAT_1000_08b5;
  *(undefined2 *)0xff7b = uVar7;
  *(undefined1 *)0xff16 = 0;
  *(undefined1 *)0xff17 = 0;
  *(undefined2 *)0xff18 = 0;
  *(undefined1 *)0xff1d = 0;
  *(undefined1 *)0xff1e = 0;
  *(undefined2 *)0xff1f = 0;
  *(undefined1 *)0xff26 = 0xff;
  *(undefined1 *)0xff09 = 0xff;
  *(undefined1 *)0xff27 = 0;
  *(undefined1 *)0xff28 = 0;
  *(undefined1 *)0xff0b = 0;
  *(undefined1 *)0xff08 = 0;
  *(undefined1 *)0xff75 = 0;
  *(undefined1 *)0xff33 = 5;
  *(undefined1 *)0xff34 = 0;
  *(undefined1 *)0xff38 = 0;
  *(undefined1 *)0xff39 = 0;
  *(undefined1 *)0xff3a = 0;
  *(undefined1 *)0xff43 = 0;
  *(undefined1 *)0xff3c = 0;
  *(undefined1 *)0xff3b = 0;
  *(undefined1 *)0xff74 = 0;
  *(undefined1 *)0xff40 = 0;
  *(undefined1 *)0xff42 = 0;
  *(undefined1 *)0xff78 = 0;
  *(undefined1 *)0xff0a = DAT_1000_08e9;
  *(char *)0xff15 = DAT_1000_08e8;
  puVar11 = (undefined1 *)0xff6c;
  for (iVar6 = 8; iVar6 != 0; iVar6 = iVar6 + -1) {
    puVar2 = puVar11;
    puVar11 = puVar11 + 1;
    *puVar2 = 0;
  }
  *(undefined2 *)(puVar9 + -2) = 0x1000;
  uVar7 = *(undefined2 *)(puVar9 + -2);
  pbVar10 = (byte *)0x869;
  pbVar12 = (byte *)0xff6c;
  iVar6 = 8;
  do {
    pbVar1 = pbVar10;
    pbVar10 = pbVar10 + 1;
    bVar4 = *pbVar1;
    if (bVar4 == 0x2e) break;
    if ((0x60 < bVar4) && (bVar4 < 0x7b)) {
      bVar4 = bVar4 & 0x5f;
    }
    pbVar1 = pbVar12;
    pbVar12 = pbVar12 + 1;
    *pbVar1 = bVar4;
    iVar6 = iVar6 + -1;
  } while (iVar6 != 0);
  *(undefined1 *)0xff14 = DAT_1000_08e7;
  *(int *)0xff2c = DAT_1000_08af + 0x1000;
  *(undefined2 *)(puVar9 + -2) = 0x1000;
  *(undefined2 *)(puVar9 + -2) = 0x21c;
  FUN_1000_04ef();
  *(undefined2 *)(puVar9 + -2) = 0x227;
  FUN_1000_04ef();
  *(undefined2 *)(puVar9 + -2) = 0x232;
  FUN_1000_04ef();
  *(undefined2 *)(puVar9 + -2) = 0x246;
  FUN_1000_04ef();
  *(undefined2 *)(puVar9 + -2) = 0x255;
  FUN_1000_04ef();
  *(undefined2 *)(puVar9 + -2) = 0x264;
  FUN_1000_04ef();
  *(undefined2 *)(puVar9 + -2) = 0x1000;
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  iVar5 = DAT_1000_08af;
  iVar6 = DAT_1000_08af + 0xff0;
  *(undefined2 *)0xff0c = 0x100;
  *(int *)0xff0e = iVar6;
  *(undefined2 *)0xff10 = 0x1100;
  *(int *)0xff12 = iVar6;
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  out(0x43,0x36);
  out(0x40,0xb1);
  out(0x40,0x13);
  *(undefined2 *)(puVar9 + -2) = 0x2cf;
  FUN_1000_057a();
                    /* WARNING: Could not recover jumptable at 0x000102d4. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)(ulong)DAT_1000_08ad)();
  return;
}



// Address: 1000:0340

void FUN_1000_0340(void)

{
  code *pcVar1;
  bool bVar2;
  undefined1 uVar3;
  
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  out(0x43,0x36);
  bVar2 = false;
  uVar3 = 1;
  out(0x40,0);
  out(0x40,0);
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  if (bVar2) {
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
  }
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  do {
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
  } while (!(bool)uVar3);
  return;
}



// Address: 1000:0385

void __cdecl16near FUN_1000_0385(void)

{
  code *pcVar1;
  undefined1 in_ZF;
  
  do {
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
  } while (!(bool)in_ZF);
  return;
}



// Address: 1000:0390

void __cdecl16near FUN_1000_0390(void)

{
  code *pcVar1;
  byte *pbVar2;
  undefined4 uVar3;
  
  DAT_1000_08ea = '\0';
  do {
    pcVar1 = (code *)swi(0x21);
    uVar3 = (*pcVar1)();
    pbVar2 = (byte *)((ulong)uVar3 >> 0x10);
    if ((int)uVar3 == 0) {
      return;
    }
  } while (*pbVar2 < 0x20);
  do {
    DAT_1000_08ea = DAT_1000_08ea + '\x01';
    *pbVar2 = *pbVar2 | 0x20;
    do {
      pcVar1 = (code *)swi(0x21);
      uVar3 = (*pcVar1)();
      pbVar2 = (byte *)((ulong)uVar3 >> 0x10);
      if ((int)uVar3 == 0) {
        return;
      }
    } while (*pbVar2 == 0x20);
  } while (0x1f < *pbVar2);
  return;
}



// Address: 1000:03cc

void __cdecl16near FUN_1000_03cc(void)

{
  char *pcVar1;
  char *pcVar2;
  int in_CX;
  int iVar3;
  int iVar4;
  char *unaff_SI;
  char *pcVar5;
  char *pcVar6;
  char *pcVar7;
  undefined2 unaff_DS;
  bool bVar8;
  
  FUN_1000_04da();
  if (in_CX == 4) {
    pcVar6 = (char *)0x433;
    iVar3 = 4;
    bVar8 = true;
    do {
      iVar4 = 3;
      pcVar5 = unaff_SI;
      pcVar7 = pcVar6;
      do {
        if (iVar4 == 0) break;
        iVar4 = iVar4 + -1;
        pcVar2 = pcVar7;
        pcVar7 = pcVar7 + 1;
        pcVar1 = pcVar5;
        pcVar5 = pcVar5 + 1;
        bVar8 = *pcVar1 == *pcVar2;
      } while (bVar8);
      if (bVar8) {
        *(char *)0x8e7 = pcVar6[3];
        return;
      }
      pcVar6 = pcVar6 + 4;
      bVar8 = pcVar6 == (char *)0x0;
      iVar3 = iVar3 + -1;
      if (iVar3 == 0) {
        FUN_1000_04ca();
        return;
      }
    } while( true );
  }
  if (in_CX != 5) {
    FUN_1000_04ca();
    return;
  }
  pcVar6 = (char *)0x429;
  iVar3 = 2;
  bVar8 = true;
  do {
    iVar4 = 4;
    pcVar5 = unaff_SI;
    pcVar7 = pcVar6;
    do {
      if (iVar4 == 0) break;
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar7;
      pcVar7 = pcVar7 + 1;
      pcVar1 = pcVar5;
      pcVar5 = pcVar5 + 1;
      bVar8 = *pcVar1 == *pcVar2;
    } while (bVar8);
    if (bVar8) {
      *(char *)0x8e7 = pcVar6[4];
      return;
    }
    pcVar6 = pcVar6 + 5;
    bVar8 = pcVar6 == (char *)0x0;
    iVar3 = iVar3 + -1;
    if (iVar3 == 0) {
      FUN_1000_04ca();
      return;
    }
  } while( true );
}



// Address: 1000:0443

void __cdecl16near FUN_1000_0443(void)

{
  undefined1 *puVar1;
  char *pcVar2;
  undefined1 *puVar3;
  char *pcVar4;
  int in_CX;
  uint uVar5;
  int iVar6;
  undefined1 *unaff_SI;
  char *pcVar7;
  undefined1 *puVar8;
  char *pcVar9;
  undefined2 unaff_DS;
  bool bVar10;
  
  DAT_1000_08e8 = 0;
  FUN_1000_04da();
  uVar5 = in_CX - 1;
  if (0xe < uVar5) {
    uVar5 = 0xf;
  }
  puVar8 = (undefined1 *)0x88b;
  for (; uVar5 != 0; uVar5 = uVar5 - 1) {
    puVar3 = puVar8;
    puVar8 = puVar8 + 1;
    puVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    *puVar3 = *puVar1;
  }
  bVar10 = true;
  *puVar8 = 0;
  pcVar9 = (char *)0x88b;
  pcVar7 = (char *)0x473;
  iVar6 = 9;
  do {
    if (iVar6 == 0) break;
    iVar6 = iVar6 + -1;
    pcVar4 = pcVar9;
    pcVar9 = pcVar9 + 1;
    pcVar2 = pcVar7;
    pcVar7 = pcVar7 + 1;
    bVar10 = *pcVar2 == *pcVar4;
  } while (bVar10);
  if (!bVar10) {
    return;
  }
  *(undefined1 *)0x8e8 = 0xff;
  return;
}



// Address: 1000:047c

void __cdecl16near FUN_1000_047c(void)

{
  undefined1 *puVar1;
  undefined1 *puVar2;
  int in_CX;
  uint uVar3;
  undefined1 *unaff_SI;
  undefined1 *puVar4;
  undefined2 unaff_DS;
  
  FUN_1000_04da();
  uVar3 = in_CX - 1;
  if (0xe < uVar3) {
    uVar3 = 0xf;
  }
  puVar4 = (undefined1 *)0x89d;
  for (; uVar3 != 0; uVar3 = uVar3 - 1) {
    puVar2 = puVar4;
    puVar4 = puVar4 + 1;
    puVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    *puVar2 = *puVar1;
  }
  *puVar4 = 0;
  return;
}



// Address: 1000:0493

void __cdecl16near FUN_1000_0493(void)

{
  char *pcVar1;
  char *pcVar2;
  code *pcVar3;
  int in_CX;
  int iVar4;
  uint uVar5;
  char *unaff_SI;
  char *pcVar6;
  undefined2 unaff_DS;
  bool bVar7;
  
  FUN_1000_04da();
  if (in_CX == 3) {
    pcVar6 = (char *)0x4c8;
    iVar4 = 2;
    bVar7 = true;
    do {
      if (iVar4 == 0) break;
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar6;
      pcVar6 = pcVar6 + 1;
      pcVar1 = unaff_SI;
      unaff_SI = unaff_SI + 1;
      bVar7 = *pcVar1 == *pcVar2;
    } while (bVar7);
    if (bVar7) {
      DAT_1000_08e9 = 0;
      return;
    }
  }
  else if (in_CX == 4) {
    pcVar6 = (char *)0x4c5;
    iVar4 = 3;
    bVar7 = true;
    do {
      if (iVar4 == 0) break;
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar6;
      pcVar6 = pcVar6 + 1;
      pcVar1 = unaff_SI;
      unaff_SI = unaff_SI + 1;
      bVar7 = *pcVar1 == *pcVar2;
    } while (bVar7);
    if (bVar7) {
      DAT_1000_08e9 = 0xff;
      return;
    }
  }
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar3 = (code *)swi(0x21);
  (*pcVar3)();
  pcVar6 = (char *)0x8eb;
  uVar5 = (uint)DAT_1000_08ea;
  do {
    pcVar1 = pcVar6;
    pcVar6 = pcVar6 + 1;
    if (*pcVar1 == ':') {
      return;
    }
    uVar5 = uVar5 - 1;
  } while (uVar5 != 0);
  FUN_1000_04ca();
  return;
}



// Address: 1000:04ca

void FUN_1000_04ca(void)

{
  char *pcVar1;
  code *pcVar2;
  uint uVar3;
  char *pcVar4;
  
  pcVar2 = (code *)swi(0x21);
  (*pcVar2)();
  pcVar2 = (code *)swi(0x21);
  (*pcVar2)();
  pcVar2 = (code *)swi(0x21);
  (*pcVar2)();
  pcVar4 = (char *)0x8eb;
  uVar3 = (uint)DAT_1000_08ea;
  do {
    pcVar1 = pcVar4;
    pcVar4 = pcVar4 + 1;
    if (*pcVar1 == ':') {
      return;
    }
    uVar3 = uVar3 - 1;
  } while (uVar3 != 0);
  FUN_1000_04ca();
  return;
}



// Address: 1000:04da

void __cdecl16near FUN_1000_04da(void)

{
  char *pcVar1;
  uint uVar2;
  char *pcVar3;
  
  pcVar3 = (char *)0x8eb;
  uVar2 = (uint)DAT_1000_08ea;
  do {
    pcVar1 = pcVar3;
    pcVar3 = pcVar3 + 1;
    if (*pcVar1 == ':') {
      return;
    }
    uVar2 = uVar2 - 1;
  } while (uVar2 != 0);
  FUN_1000_04ca();
  return;
}



// Address: 1000:04ef

void __cdecl16near FUN_1000_04ef(void)

{
  code *pcVar1;
  uint unaff_DI;
  bool bVar2;
  
  bVar2 = 0xfffd < unaff_DI;
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  if (!bVar2) {
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
    if (!bVar2) {
      pcVar1 = (code *)swi(0x21);
      (*pcVar1)();
      if (!bVar2) {
        return;
      }
    }
  }
  FUN_1000_0520();
  FUN_1000_0340();
  return;
}



// Address: 1000:0520

void __cdecl16near FUN_1000_0520(undefined2 param_1)

{
  code *pcVar1;
  char *pcVar2;
  int unaff_ES;
  int unaff_DS;
  
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  for (pcVar2 = (char *)(unaff_DS + 2); *pcVar2 != '\0'; pcVar2 = pcVar2 + 1) {
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
  }
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  if ((unaff_ES != 2) && (unaff_ES != 5)) {
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
    pcVar1 = (code *)swi(0x21);
    (*pcVar1)();
    return;
  }
  pcVar1 = (code *)swi(0x21);
  (*pcVar1)();
  return;
}



// Address: 1000:057a

void FUN_1000_057a(void)

{
                    /* WARNING: Could not recover jumptable at 0x00010583. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)DAT_1000_08e7 * 2 + 0x588))();
  return;
}



// Address: 1000:05f9

void __cdecl16near FUN_1000_05f9(void)

{
  char cVar1;
  char cVar2;
  uint uVar3;
  char *pcVar4;
  char *pcVar5;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  if (*(char *)0x80 == '\0') {
    return;
  }
  pcVar5 = (char *)0x869;
  uVar3 = (uint)*(byte *)0x80;
  pcVar4 = (char *)0x81;
  while (*pcVar4 == ' ') {
    pcVar4 = pcVar4 + 1;
    uVar3 = uVar3 - 1;
    if (uVar3 == 0) {
      return;
    }
  }
  cVar2 = '\0';
  do {
    cVar1 = *pcVar4;
    if ((cVar1 != ' ') && (cVar1 != '\r')) {
      cVar2 = -1;
      *pcVar5 = cVar1;
      pcVar5 = pcVar5 + 1;
    }
    pcVar4 = pcVar4 + 1;
    uVar3 = uVar3 - 1;
  } while (uVar3 != 0);
  if (cVar2 == '\0') {
    return;
  }
  *(undefined1 *)0x8c1 = 0xff;
  *pcVar5 = '.';
  pcVar5[1] = 'U';
  pcVar5[2] = 'S';
  pcVar5[3] = 'R';
  pcVar5[4] = '\0';
  return;
}



