/* Decompiled from chunk_01.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0021

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0021(void)

{
  char *pcVar1;
  char *pcVar2;
  char cVar3;
  undefined1 uVar4;
  char cVar5;
  int unaff_SI;
  char *pcVar6;
  char *pcVar7;
  undefined2 unaff_DS;
  undefined1 uVar8;
  int in_stack_00000000;
  int iVar9;
  
  while( true ) {
    iVar9 = unaff_SI + 2;
    (*_DAT_0000_2000)(iVar9);
    in_stack_00000000 = in_stack_00000000 + -1;
    if (in_stack_00000000 == 0) break;
    unaff_SI = iVar9 + 2;
  }
  FUN_0000_09d9();
  pcVar6 = (char *)0xbb;
  pcVar7 = (char *)0xae03;
  cVar3 = '\0';
  cVar5 = '\x01';
  do {
    pcVar1 = pcVar6;
    pcVar6 = pcVar6 + 1;
    if (*pcVar1 != '\0') {
      pcVar1 = pcVar7;
      pcVar7 = pcVar7 + 1;
      *pcVar1 = cVar5;
      cVar3 = cVar3 + '\x01';
    }
    cVar5 = cVar5 + '\x01';
  } while (cVar5 != '\b');
  *(char *)0xadfa = cVar3;
  pcVar6 = (char *)0xa1;
  pcVar7 = (char *)0xae0b;
  uRam0000ae0a = 0;
  cVar3 = '\0';
  cVar5 = '\x05';
  do {
    pcVar1 = pcVar6;
    pcVar6 = pcVar6 + 1;
    if (*pcVar1 != '\0') {
      pcVar2 = pcVar7;
      pcVar7 = pcVar7 + 1;
      *pcVar2 = *pcVar1;
      cVar3 = cVar3 + '\x01';
    }
    cVar5 = cVar5 + -1;
  } while (cVar5 != '\0');
  cVar5 = '\0';
  if (cVar3 != '\0') {
    cVar3 = cVar3 + '\x01';
  }
  *(char *)0xadfc = cVar3;
  FUN_0000_0647();
  FUN_0000_08b3();
  FUN_0000_06d5();
  FUN_0000_066d();
  FUN_0000_0756();
  FUN_0000_0a5c();
  *(char *)0xae01 = -cVar5;
  uVar4 = 0;
  if ((*(char *)0xadfa == '\0') && (uVar4 = 1, *(char *)0xadfc == '\0')) {
    uVar8 = 0;
    if (*(char *)0xadf8 == '\0') {
      uVar4 = 2;
      uVar8 = 0;
      if (*(char *)0xadfe != '\0') goto LAB_0000_00b8;
    }
    do {
      FUN_0000_0a5c();
    } while (!(bool)uVar8);
    return;
  }
LAB_0000_00b8:
  *(undefined1 *)0xadf9 = uVar4;
                    /* WARNING: Could not recover jumptable at 0x000000c4. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)*(byte *)0xadf9 * 2 + -0x5f3c))();
  return;
}



// Address: 0000:0647

void __cdecl16near FUN_0000_0647(void)

{
  char *pcVar1;
  char *pcVar2;
  char cVar3;
  char cVar4;
  char *pcVar5;
  char *pcVar6;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  pcVar5 = (char *)0xa6;
  pcVar6 = (char *)0xae11;
  *(undefined1 *)0xae10 = 0;
  cVar3 = '\0';
  cVar4 = '\x05';
  do {
    pcVar1 = pcVar5;
    pcVar5 = pcVar5 + 1;
    if (*pcVar1 != '\0') {
      pcVar2 = pcVar6;
      pcVar6 = pcVar6 + 1;
      *pcVar2 = *pcVar1;
      cVar3 = cVar3 + '\x01';
    }
    cVar4 = cVar4 + -1;
  } while (cVar4 != '\0');
  if (cVar3 != '\0') {
    cVar3 = cVar3 + '\x01';
  }
  *(char *)0xadfe = cVar3;
  return;
}



// Address: 0000:066d

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_066d(void)

{
  uint uVar1;
  int iVar2;
  int iVar3;
  undefined2 unaff_DS;
  
  if (*(char *)0xadfe == '\0') {
    FUN_0000_0a2f();
    return;
  }
  uVar1 = (uint)*(byte *)0xadfe;
  iVar2 = 0xe83;
  iVar3 = -0x51f0;
  do {
    iVar3 = iVar3 + 1;
    (*_DAT_0000_2036)(iVar2,iVar3);
    iVar2 = iVar2 + 0x500;
    uVar1 = uVar1 - 1;
  } while (uVar1 != 0);
  *(undefined1 *)0xadff = 0;
  *(undefined1 *)0xae00 = 0;
  if (*(char *)0xadf8 != '\0') {
    return;
  }
  (*_DAT_0000_202e)();
  (*_DAT_0000_2000)();
  FUN_0000_0a2f();
  return;
}



// Address: 0000:06d5

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_06d5(void)

{
  char *pcVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  char *pcVar5;
  undefined2 unaff_DS;
  
  if (*(char *)0xadfc == '\0') {
    FUN_0000_0a2f();
    return;
  }
  uVar2 = (uint)*(byte *)0xadfc;
  iVar3 = 0xe55;
  iVar4 = -0x51f6;
  do {
    iVar4 = iVar4 + 1;
    (*_DAT_0000_2034)(iVar3,iVar4);
    iVar3 = iVar3 + 0x500;
    uVar2 = uVar2 - 1;
  } while (uVar2 != 0);
  pcVar5 = (char *)0xae0a;
  iVar4 = 6;
  do {
    if (iVar4 == 0) break;
    iVar4 = iVar4 + -1;
    pcVar1 = pcVar5;
    pcVar5 = pcVar5 + 1;
  } while (*(char *)0x9e != *pcVar1);
  *(char *)0xadfd = '\x05' - (char)iVar4;
  (*_DAT_0000_202e)();
  FUN_0000_0a2f();
  FUN_0000_0a2f();
  return;
}



// Address: 0000:0756

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0756(void)

{
  char *pcVar1;
  int iVar2;
  int iVar3;
  char *pcVar4;
  undefined2 unaff_DS;
  
  if (*(char *)0x92 != '\0') {
    (*_DAT_0000_201c)();
    (*_DAT_0000_2038)();
    (*_DAT_0000_2038)();
    FUN_0000_0872();
  }
  if (*(char *)0x93 != '\0') {
    (*_DAT_0000_2020)();
    (*_DAT_0000_2038)();
    (*_DAT_0000_2038)();
    FUN_0000_0848();
  }
  if (*(char *)0x98 != '\0') {
    (*_DAT_0000_203a)();
    (*_DAT_0000_2022)();
    FUN_0000_09b7();
  }
  if (*(char *)0x99 != '\0') {
    (*_DAT_0000_203a)();
    (*_DAT_0000_2022)();
    FUN_0000_09b7();
  }
  pcVar4 = (char *)0x9a;
  iVar3 = 0x3089;
  iVar2 = 3;
  do {
    pcVar1 = pcVar4;
    pcVar4 = pcVar4 + 1;
    if (*pcVar1 != '\0') {
      (*_DAT_0000_203c)(pcVar4,iVar3);
      iVar3 = iVar3 + 0x600;
    }
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:0848

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_0848(void)

{
  FUN_0000_09b7();
  (*_DAT_0000_2022)();
                    /* WARNING: Could not recover jumptable at 0x0000086d. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*_DAT_0000_2022)();
  return;
}



// Address: 0000:0872

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0872(void)

{
  undefined2 unaff_DS;
  
  if (*(char *)0xe4 == '\0') {
    return;
  }
  (*_DAT_0000_2000)();
  (*_DAT_0000_2022)();
  FUN_0000_09b7();
                    /* WARNING: Could not recover jumptable at 0x000008ae. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*_DAT_0000_2022)();
  return;
}



// Address: 0000:08b3

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_08b3(void)

{
  char *pcVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  char *pcVar5;
  undefined2 unaff_DS;
  
  if (*(char *)0xadfa == '\0') {
    FUN_0000_0a2f();
    return;
  }
  uVar2 = (uint)*(byte *)0xadfa;
  iVar3 = 0xe1c;
  iVar4 = -0x51fd;
  do {
    iVar4 = iVar4 + 1;
    (*_DAT_0000_201e)(iVar3,iVar4);
    iVar3 = iVar3 + 0x800;
    uVar2 = uVar2 - 1;
  } while (uVar2 != 0);
  FUN_0000_092d();
  pcVar5 = (char *)0xae03;
  iVar4 = 7;
  do {
    if (iVar4 == 0) break;
    iVar4 = iVar4 + -1;
    pcVar1 = pcVar5;
    pcVar5 = pcVar5 + 1;
  } while (*(char *)0x9d != *pcVar1);
  *(char *)0xadfb = '\x06' - (char)iVar4;
  (*_DAT_0000_202e)();
  FUN_0000_0a2f();
  return;
}



// Address: 0000:092d

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_092d(void)

{
  undefined2 uVar1;
  char *pcVar2;
  int iVar3;
  char *pcVar4;
  undefined2 unaff_DS;
  char *pcVar5;
  
  iVar3 = 0xe2e;
  pcVar4 = (char *)0xae03;
  pcVar2 = (char *)(uint)*(byte *)0xadfa;
  do {
    pcVar5 = pcVar4 + 1;
    uVar1 = CONCAT11(*(undefined1 *)((byte)(*pcVar4 - 1) + 0xb4),
                     *(undefined1 *)((byte)(*pcVar4 - 1) + 0xab));
    (*_DAT_0000_2000)(iVar3,uVar1,iVar3,uVar1,iVar3,pcVar5,pcVar2);
    FUN_0000_09b7();
    iVar3 = iVar3 + 9;
    (*_DAT_0000_2022)();
    pcVar4 = (char *)0x994;
    FUN_0000_09b7();
    (*_DAT_0000_2022)();
    iVar3 = iVar3 + 0x800;
    pcVar2 = pcVar5 + -1;
  } while (pcVar2 != (char *)0x0);
  return;
}



// Address: 0000:09b7

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_09b7(void)

{
  (*_DAT_0000_2032)();
                    /* WARNING: Could not recover jumptable at 0x000009d4. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*_DAT_0000_2030)();
  return;
}



// Address: 0000:09d9

void __cdecl16near FUN_0000_09d9(void)

{
  int iVar1;
  
  iVar1 = 4;
  do {
    FUN_0000_0a2f();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0a2f

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0a2f(void)

{
  char *pcVar1;
  undefined2 in_AX;
  char cVar2;
  undefined2 in_CX;
  int in_BX;
  char *unaff_SI;
  undefined2 unaff_DS;
  
  while( true ) {
    pcVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    cVar2 = (char)((uint)in_AX >> 8);
    in_AX = CONCAT11(cVar2,*pcVar1);
    if (*pcVar1 == '\0') break;
    if (cVar2 != '\x01') {
      (*_DAT_0000_2022)(in_AX,in_CX,in_BX);
    }
    (*_DAT_0000_2022)();
    in_BX = in_BX + 8;
  }
  return;
}



// Address: 0000:0a5c

void __cdecl16near FUN_0000_0a5c(void)

{
  undefined2 unaff_DS;
  char cVar1;
  
  (*DAT_0000_0110)();
  (*DAT_0000_0112)();
  (*DAT_0000_0114)();
  (*DAT_0000_0116)();
  (*DAT_0000_0118)();
  cVar1 = '\0';
  if (*(char *)0xae01 == '\0') {
    if ((*(uint *)0xff18 & 1) != 0) {
      return;
    }
    return;
  }
  FUN_0000_0a8a();
  if (cVar1 != '\0') {
    return;
  }
  *(undefined1 *)0xae01 = 0;
  return;
}



// Address: 0000:0a8a

void __cdecl16near FUN_0000_0a8a(void)

{
  undefined2 unaff_DS;
  
  if ((*(uint *)0xff18 & 1) != 0) {
    return;
  }
  return;
}



