/* Decompiled from chunk_05.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0128

void __cdecl16near FUN_0000_0128(void)

{
  char *pcVar1;
  char cVar2;
  char cVar3;
  byte bVar4;
  undefined2 in_BX;
  int unaff_SI;
  int unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  cVar3 = *(char *)(unaff_SI + -1);
  if (cVar3 < '\0') {
    FUN_0000_0574();
    return;
  }
  if (*(char *)(unaff_DI + -1) == -4) {
    *(undefined1 *)(unaff_DI + -1) = 0xff;
  }
  else {
    pcVar1 = (char *)(unaff_DI + -1);
    *pcVar1 = *pcVar1 + '\x01';
    cVar2 = *pcVar1;
    *(undefined1 *)(unaff_DI + -1) = 0xfe;
    if (cVar2 != '\0') {
      *(char *)(unaff_DI + -1) = cVar3;
      FUN_0000_0272();
    }
  }
  bVar4 = *(byte *)0xc012 - 5;
  if (*(byte *)0xc012 < 5) {
    return;
  }
  if (3 < bVar4) {
    return;
  }
  (*(code *)*(undefined2 *)((uint)bVar4 * 2 + 0x3172))(in_BX);
  return;
}



// Address: 0000:0272

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0272(void)

{
  undefined2 uVar1;
  byte in_AL;
  undefined2 *puVar2;
  int iVar3;
  undefined2 *in_DX;
  undefined2 *puVar4;
  undefined2 *puVar5;
  undefined2 unaff_DS;
  
  if (in_AL == 0) {
    *in_DX = 0;
    in_DX[1] = 0;
    puVar2 = in_DX + 0x1000;
    if ((undefined2 *)0x7fff < puVar2) {
      puVar2 = in_DX + -0x2fb0;
    }
    *puVar2 = 0;
    puVar2[1] = 0;
    puVar4 = puVar2 + 0x1000;
    if ((undefined2 *)0x7fff < puVar4) {
      puVar4 = puVar2 + -0x2fb0;
    }
    *puVar4 = 0;
    puVar4[1] = 0;
    puVar2 = puVar4 + 0x1000;
    if ((undefined2 *)0x7fff < puVar2) {
      puVar2 = puVar4 + -0x2fb0;
    }
    *puVar2 = 0;
    puVar2[1] = 0;
    puVar4 = puVar2 + 0x1000;
    if ((undefined2 *)0x7fff < puVar4) {
      puVar4 = puVar2 + -0x2fb0;
    }
    *puVar4 = 0;
    puVar4[1] = 0;
    puVar2 = puVar4 + 0x1000;
    if ((undefined2 *)0x7fff < puVar2) {
      puVar2 = puVar4 + -0x2fb0;
    }
    *puVar2 = 0;
    puVar2[1] = 0;
    puVar4 = puVar2 + 0x1000;
    if ((undefined2 *)0x7fff < puVar4) {
      puVar4 = puVar2 + -0x2fb0;
    }
    *puVar4 = 0;
    puVar4[1] = 0;
    puVar2 = puVar4 + 0x1000;
    if ((undefined2 *)0x7fff < puVar2) {
      puVar2 = puVar4 + -0x2fb0;
    }
    *puVar2 = 0;
    puVar2[1] = 0;
    return;
  }
  iVar3 = (uint)in_AL * 2;
  if (*(int *)(iVar3 + 0x5262) == 0) {
    *(undefined2 *)(iVar3 + 0x5262) = in_DX;
    uVar1 = _DAT_0000_ff2c;
    puVar2 = (undefined2 *)((uint)(byte)(in_AL - 1) * 0x20 + -0x7fd0);
    iVar3 = 4;
    do {
      *in_DX = *puVar2;
      in_DX[1] = puVar2[1];
      puVar4 = in_DX + 0x1000;
      if ((undefined2 *)0x7fff < puVar4) {
        puVar4 = in_DX + -0x2fb0;
      }
      puVar5 = puVar2 + 3;
      *puVar4 = puVar2[2];
      puVar2 = puVar2 + 4;
      puVar4[1] = *puVar5;
      in_DX = puVar4 + 0x1000;
      if ((undefined2 *)0x7fff < in_DX) {
        in_DX = puVar4 + -0x2fb0;
      }
      iVar3 = iVar3 + -1;
    } while (iVar3 != 0);
    return;
  }
  puVar2 = (undefined2 *)*(undefined2 *)(iVar3 + 0x5262);
  *in_DX = *puVar2;
  in_DX[1] = puVar2[1];
  puVar4 = in_DX + 0x1000;
  if ((undefined2 *)0x7fff < puVar4) {
    puVar4 = in_DX + -0x2fb0;
  }
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar5) {
    puVar5 = puVar2 + -0x2fb0;
  }
  *puVar4 = *puVar5;
  puVar4[1] = puVar5[1];
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = puVar4 + -0x2fb0;
  }
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x7fff < puVar4) {
    puVar4 = puVar5 + -0x2fb0;
  }
  *puVar2 = *puVar4;
  puVar2[1] = puVar4[1];
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar5) {
    puVar5 = puVar2 + -0x2fb0;
  }
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = puVar4 + -0x2fb0;
  }
  *puVar5 = *puVar2;
  puVar5[1] = puVar2[1];
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x7fff < puVar4) {
    puVar4 = puVar5 + -0x2fb0;
  }
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar5) {
    puVar5 = puVar2 + -0x2fb0;
  }
  *puVar4 = *puVar5;
  puVar4[1] = puVar5[1];
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = puVar4 + -0x2fb0;
  }
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x7fff < puVar4) {
    puVar4 = puVar5 + -0x2fb0;
  }
  *puVar2 = *puVar4;
  puVar2[1] = puVar4[1];
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar5) {
    puVar5 = puVar2 + -0x2fb0;
  }
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = puVar4 + -0x2fb0;
  }
  *puVar5 = *puVar2;
  puVar5[1] = puVar2[1];
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x7fff < puVar4) {
    puVar4 = puVar5 + -0x2fb0;
  }
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar5) {
    puVar5 = puVar2 + -0x2fb0;
  }
  *puVar4 = *puVar5;
  puVar4[1] = puVar5[1];
  return;
}



// Address: 0000:0436

void __cdecl16near FUN_0000_0436(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe900 == -1) {
    return;
  }
  if (*(char *)0xe900 == -4) {
    return;
  }
  *(undefined1 *)0xe900 = 0xff;
  FUN_0000_16f1();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x25));
  if (*(char *)(unaff_SI + 0x25) < '\0') {
    uVar1 = FUN_0000_084b();
  }
  FUN_0000_0852(uVar1);
  FUN_0000_06a1();
  return;
}



// Address: 0000:0473

void __cdecl16near FUN_0000_0473(void)

{
  undefined1 uVar1;
  int in_BX;
  int unaff_SI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined1 *)(in_BX + -0x1700);
  *(undefined1 *)(in_BX + -0x1700) = 0xff;
  UNLOCK();
  *(undefined1 *)0x5255 = uVar1;
  *(undefined1 *)0x5256 = 0;
  *(undefined1 *)(in_BX + -0x16ff) = 0xff;
  FUN_0000_16f1();
  *(undefined2 *)0x5259 = *(undefined2 *)(unaff_SI + 0x24);
  FUN_0000_0852();
  thunk_FUN_0000_0676();
  return;
}



// Address: 0000:04b9

void __cdecl16near FUN_0000_04b9(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe91b == -1) {
    return;
  }
  if (*(char *)0xe91b == -4) {
    return;
  }
  *(undefined1 *)0xe91b = 0xff;
  FUN_0000_16f1();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x24));
  if (*(char *)(unaff_SI + 0x24) < '\0') {
    uVar1 = FUN_0000_084b();
  }
  FUN_0000_0852(uVar1);
  FUN_0000_06a1();
  return;
}



// Address: 0000:04f1

void __cdecl16near FUN_0000_04f1(void)

{
  undefined1 uVar1;
  int extraout_DX;
  int in_BX;
  int unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *unaff_DI;
  *unaff_DI = 0xff;
  UNLOCK();
  *(undefined1 *)0x5255 = uVar1;
  LOCK();
  uVar1 = unaff_DI[0x1c];
  unaff_DI[0x1c] = 0xff;
  UNLOCK();
  *(undefined1 *)0x5256 = uVar1;
  FUN_0000_16f1();
  FUN_0000_0852();
  if ((*(char *)0x5255 != -1) && (*(char *)0x5255 != -4)) {
    if ((char)extraout_DX < '\0') {
      FUN_0000_084b(in_BX * 4 + *(int *)0x5231,unaff_SI + 0x25);
    }
    FUN_0000_06a1();
  }
  if (((*(char *)0x5237 != '\x01') && (*(char *)0x5256 != -1)) && (*(char *)0x5256 != -4)) {
    if (extraout_DX < 0) {
      FUN_0000_084b();
    }
    FUN_0000_06a1();
  }
  return;
}



// Address: 0000:0574

void __cdecl16near FUN_0000_0574(void)

{
  undefined2 uVar1;
  undefined1 uVar2;
  undefined1 in_BL;
  int iVar3;
  undefined1 *unaff_SI;
  int unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + -1);
  *(undefined2 *)(unaff_DI + -1) = 0xfffe;
  UNLOCK();
  *(undefined2 *)0x5255 = uVar1;
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + 0x1b);
  *(undefined2 *)(unaff_DI + 0x1b) = 0xffff;
  UNLOCK();
  *(undefined2 *)0x5257 = uVar1;
  iVar3 = 0x5259;
  *(undefined1 *)0x525a = *unaff_SI;
  FUN_0000_16f1();
  *(undefined2 *)(iVar3 + 2) = *(undefined2 *)(unaff_SI + 0x23);
  *(undefined1 *)0x5238 = in_BL;
  *(char *)0x5239 = '\x12' - *(char *)0x5237;
  uVar2 = FUN_0000_0852();
  *(undefined1 *)0x5259 = uVar2;
  thunk_FUN_0000_0676();
  if (*(char *)0x5237 != '\x01') {
    thunk_FUN_0000_0676();
    if ((*(char *)0xff34 != '\0') && (*(char *)0xff2f != '\0')) {
      FUN_0000_08a3();
    }
  }
  return;
}



// Address: 0000:05ed

void __cdecl16near FUN_0000_05ed(void)

{
  char *pcVar1;
  char *pcVar2;
  char cVar3;
  int iVar4;
  char extraout_DL;
  int in_BX;
  char *pcVar5;
  char *unaff_SI;
  char *pcVar6;
  char *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  LOCK();
  cVar3 = unaff_DI[-1];
  unaff_DI[-1] = -2;
  UNLOCK();
  *(char *)0x5255 = cVar3;
  LOCK();
  cVar3 = unaff_DI[0x1b];
  unaff_DI[0x1b] = -1;
  UNLOCK();
  *(char *)0x5256 = cVar3;
  FUN_0000_16f1();
  cVar3 = FUN_0000_0852();
  if ((*(char *)0x5255 != -1) && (*(char *)0x5255 != -4)) {
    if (cVar3 < '\0') {
      FUN_0000_084b(in_BX * 4 + *(int *)0x5231,unaff_SI + 0x24);
    }
    FUN_0000_06a1();
  }
  if (((*(char *)0x5237 != '\x01') && (*(char *)0x5256 != -1)) && (*(char *)0x5256 != -4)) {
    if (extraout_DL < '\0') {
      FUN_0000_084b();
    }
    FUN_0000_06a1();
  }
  while( true ) {
    FUN_0000_16f1();
    *(int *)0x5231 = *(int *)0x5231 + 0x140;
    pcVar1 = (char *)0x5237;
    *pcVar1 = *pcVar1 + -1;
    if (*pcVar1 == '\0') {
      return;
    }
    FUN_0000_0f4a();
    if (unaff_SI[7] < '\0') {
      FUN_0000_04f1();
    }
    iVar4 = 6;
    pcVar2 = unaff_SI + 8;
    do {
      pcVar6 = unaff_DI;
      pcVar5 = pcVar2;
      if (*pcVar5 != *pcVar6) {
        FUN_0000_0128();
      }
      if (pcVar5[1] != pcVar6[1]) {
        FUN_0000_0128();
      }
      if (pcVar5[2] != pcVar6[2]) {
        FUN_0000_0128();
      }
      if (pcVar5[3] != pcVar6[3]) {
        FUN_0000_0128();
      }
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar5 + 4;
      unaff_DI = pcVar6 + 4;
    } while (iVar4 != 0);
    if (pcVar5[4] != pcVar6[4]) {
      FUN_0000_0128();
    }
    if (pcVar5[5] != pcVar6[5]) {
      FUN_0000_0128();
    }
    if (pcVar5[6] != pcVar6[6]) {
      FUN_0000_0128();
    }
    unaff_SI = pcVar5 + 8;
    unaff_DI = pcVar6 + 8;
    if (pcVar5[7] < '\0') break;
    if (pcVar5[7] != pcVar6[7]) {
      FUN_0000_0128();
    }
  }
  FUN_0000_05ed();
  return;
}



// Address: 0000:0673

void __cdecl16near thunk_FUN_0000_0676(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_084b(0x676);
      in_DX = extraout_DX;
    }
    FUN_0000_06a1(in_DX);
  }
  return;
}



// Address: 0000:0676

void __cdecl16near FUN_0000_0676(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_084b();
      in_DX = extraout_DX;
    }
    FUN_0000_06a1(in_DX);
  }
  return;
}



// Address: 0000:06a1

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_06a1(void)

{
  char in_AL;
  byte bVar1;
  undefined2 unaff_DS;
  
  bVar1 = *(byte *)0x523a;
  if ((in_AL != '\0') && (-1 < in_AL)) {
    bVar1 = bVar1 | 0x80;
  }
  _DAT_0000_522f = *(undefined2 *)((uint)(bVar1 & 0x7f) * 2 + 0x51d2);
  if (-1 < (char)bVar1) {
    FUN_0000_075d();
    FUN_0000_07ca();
    return;
  }
  FUN_0000_0719();
  FUN_0000_07ca();
  return;
}



// Address: 0000:0719

void __cdecl16near FUN_0000_0719(void)

{
  uint uVar1;
  int iVar2;
  uint *unaff_DI;
  undefined2 unaff_ES;
  undefined4 uVar3;
  
  FUN_0000_083d();
  iVar2 = 8;
  do {
    uVar3 = FUN_0000_219f();
    *unaff_DI = *unaff_DI & (uint)uVar3;
    uVar1 = FUN_0000_076d((int)((ulong)uVar3 >> 0x10));
    *unaff_DI = *unaff_DI | uVar1;
    uVar1 = FUN_0000_219f();
    unaff_DI[1] = unaff_DI[1] & uVar1;
    uVar1 = FUN_0000_076d();
    unaff_DI[1] = unaff_DI[1] | uVar1;
    unaff_DI = unaff_DI + 2;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:075d

void __cdecl16near FUN_0000_075d(void)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  int iVar3;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  
  iVar3 = 8;
  do {
    uVar2 = FUN_0000_076d();
    puVar1 = unaff_DI + 1;
    *unaff_DI = uVar2;
    uVar2 = FUN_0000_076d();
    unaff_DI = unaff_DI + 2;
    *puVar1 = uVar2;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:076d

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __cdecl16near FUN_0000_076d(void)

{
  uint in_AX;
  
  return CONCAT11(*(char *)((in_AX >> 0xc) + _DAT_0000_522f) << 4 |
                  *(byte *)((uint)((byte)(in_AX >> 8) & 0xf) + _DAT_0000_522f),
                  *(char *)((in_AX >> 4 & 0xf) + _DAT_0000_522f) << 4 |
                  *(byte *)((uint)((byte)in_AX & 0xf) + _DAT_0000_522f));
}



// Address: 0000:07ca

void __cdecl16near FUN_0000_07ca(void)

{
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 *puVar1;
  undefined2 *puVar2;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  *unaff_DI = *unaff_SI;
  unaff_DI[1] = unaff_SI[1];
  puVar2 = unaff_DI + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = unaff_DI + -0x2fb0;
  }
  *puVar2 = unaff_SI[2];
  puVar2[1] = unaff_SI[3];
  puVar1 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar1) {
    puVar1 = puVar2 + -0x2fb0;
  }
  *puVar1 = unaff_SI[4];
  puVar1[1] = unaff_SI[5];
  puVar2 = puVar1 + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = puVar1 + -0x2fb0;
  }
  *puVar2 = unaff_SI[6];
  puVar2[1] = unaff_SI[7];
  puVar1 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar1) {
    puVar1 = puVar2 + -0x2fb0;
  }
  *puVar1 = unaff_SI[8];
  puVar1[1] = unaff_SI[9];
  puVar2 = puVar1 + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = puVar1 + -0x2fb0;
  }
  *puVar2 = unaff_SI[10];
  puVar2[1] = unaff_SI[0xb];
  puVar1 = puVar2 + 0x1000;
  if ((undefined2 *)0x7fff < puVar1) {
    puVar1 = puVar2 + -0x2fb0;
  }
  *puVar1 = unaff_SI[0xc];
  puVar1[1] = unaff_SI[0xd];
  puVar2 = puVar1 + 0x1000;
  if ((undefined2 *)0x7fff < puVar2) {
    puVar2 = puVar1 + -0x2fb0;
  }
  *puVar2 = unaff_SI[0xe];
  puVar2[1] = unaff_SI[0xf];
  return;
}



// Address: 0000:083d

void __cdecl16near FUN_0000_083d(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  int iVar3;
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  for (iVar3 = 0x10; iVar3 != 0; iVar3 = iVar3 + -1) {
    puVar2 = unaff_DI;
    unaff_DI = unaff_DI + 1;
    puVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    *puVar2 = *puVar1;
  }
  return;
}



// Address: 0000:084b

undefined1 __cdecl16near FUN_0000_084b(void)

{
  byte in_AL;
  
  return *(undefined1 *)(ulong)((in_AL & 0x7f) + 0xed20);
}



// Address: 0000:0852

undefined2 __cdecl16near FUN_0000_0852(void)

{
  undefined1 uVar1;
  byte in_AL;
  char cVar2;
  int iVar3;
  char *pcVar4;
  int iVar5;
  undefined2 unaff_DS;
  
  uVar1 = *(undefined1 *)((in_AL & 0x7f) + 0xed20);
  iVar3 = (uint)(in_AL & 0x7f) * 0x10 + *(int *)0xc010;
  iVar5 = -0x5f90;
  if ((*(byte *)(iVar3 + 5) & 0x80) == 0) {
    iVar5 = -0x5fd0;
  }
  pcVar4 = (char *)((uint)(*(byte *)(iVar3 + 6) & 0xf) * 5 +
                   *(int *)((uint)(byte)((*(byte *)(iVar3 + 4) & 0x1f) * '\x02') + iVar5));
  cVar2 = *pcVar4;
  if ((*(char *)0xff34 == '\0') && ((*(byte *)(iVar3 + 5) & 0x20) != 0)) {
    cVar2 = cVar2 + '\x03';
  }
  *(char *)0x523a = cVar2;
  return CONCAT11((char)((uint)pcVar4 >> 8),uVar1);
}



// Address: 0000:08a3

void __cdecl16near FUN_0000_08a3(void)

{
  byte bVar1;
  byte *pbVar2;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  if (0xf < *(byte *)0x5239) {
    return;
  }
  bVar1 = (*pcRam0000011a)();
  if ((bVar1 & 0xf) < 0xe) {
    return;
  }
  bVar1 = 0;
  for (pbVar2 = (byte *)0xeda0; *pbVar2 != 0xff; pbVar2 = pbVar2 + 4) {
    bVar1 = bVar1 + 1;
  }
  if (0x1f < bVar1) {
    return;
  }
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x5238;
  if (bVar1 == 0xff) {
    bVar1 = 4;
  }
  if (0x1a < bVar1) {
    bVar1 = 0x1a;
  }
  *pbVar2 = bVar1;
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x5239;
  if (bVar1 == 0xff) {
    bVar1 = 0;
  }
  pbVar2[1] = bVar1;
  pbVar2[2] = 3;
  bVar1 = (*pcRam0000011a)();
  pbVar2[3] = *(byte *)(ulong)((bVar1 & 7) + 0x3915);
  pbVar2[4] = 0xff;
  return;
}



// Address: 0000:0f4a

void __cdecl16near FUN_0000_0f4a(void)

{
  byte bVar1;
  byte bVar2;
  undefined2 unaff_DS;
  
  bVar1 = 0x12 - *(char *)0x5237;
  if (*(char *)0xff43 == '\0') {
    if ((byte)(*(char *)0x84 - 2U) == bVar1) {
      FUN_0000_127e();
    }
    return;
  }
  bVar2 = *(char *)0x84 - 5;
  if (bVar1 < bVar2) {
    return;
  }
  if (bVar1 == bVar2) {
    FUN_0000_1076();
    FUN_0000_127e();
    return;
  }
  if ((byte)(*(char *)0x84 + 5U) != bVar1) {
    return;
  }
  FUN_0000_112d();
  return;
}



// Address: 0000:1076

void __cdecl16near FUN_0000_1076(void)

{
  undefined2 unaff_DS;
  
  if (*(char *)0xff44 == '\0') {
    return;
  }
  FUN_0000_10bb();
  *(undefined1 *)0xff44 = 0;
  return;
}



// Address: 0000:108f

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_108f(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  int iVar3;
  int iVar4;
  undefined2 *puVar5;
  undefined2 *puVar6;
  undefined2 *puVar7;
  undefined2 unaff_CS;
  
  puVar7 = (undefined2 *)0x5362;
  iVar3 = 0x20;
  puVar6 = _DAT_0000_523d;
  do {
    puVar5 = puVar6;
    for (iVar4 = 8; iVar4 != 0; iVar4 = iVar4 + -1) {
      puVar2 = puVar7;
      puVar7 = puVar7 + 1;
      puVar1 = puVar5;
      puVar5 = puVar5 + 1;
      *puVar2 = *puVar1;
    }
    puVar6 = puVar5 + 0xff8;
    if ((undefined2 *)0x7fff < puVar6) {
      puVar6 = puVar5 + -0x2fb8;
    }
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:10bb

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_10bb(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  int iVar3;
  int iVar4;
  undefined2 *puVar5;
  undefined2 *puVar6;
  undefined2 *puVar7;
  undefined2 unaff_DS;
  
  puVar5 = (undefined2 *)0x5362;
  iVar3 = 0x20;
  puVar7 = _DAT_0000_523d;
  do {
    puVar6 = puVar7;
    for (iVar4 = 8; iVar4 != 0; iVar4 = iVar4 + -1) {
      puVar2 = puVar6;
      puVar6 = puVar6 + 1;
      puVar1 = puVar5;
      puVar5 = puVar5 + 1;
      *puVar2 = *puVar1;
    }
    puVar7 = puVar6 + 0xff8;
    if ((undefined2 *)0x7fff < puVar7) {
      puVar7 = puVar6 + -0x2fb8;
    }
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:10e3

void __cdecl16near FUN_0000_10e3(void)

{
  int iVar1;
  int iVar2;
  byte *pbVar3;
  byte *pbVar4;
  undefined2 unaff_DS;
  
  pbVar3 = (byte *)((uint)(*(char *)0x84 + *(char *)0x5241 & 0x3f) * 0x24 +
                    (uint)(byte)(*(char *)0x83 + *(char *)0x5242 + 4) + *(int *)0xff31);
  FUN_0000_16f1();
  iVar1 = 4;
  do {
    iVar2 = 4;
    do {
      pbVar4 = pbVar3;
      *(undefined2 *)((uint)(*pbVar4 & 0x7f) * 2 + 0x5262) = 0;
      iVar2 = iVar2 + -1;
      pbVar3 = pbVar4 + 1;
    } while (iVar2 != 0);
    pbVar3 = pbVar4 + 0x21;
    FUN_0000_16f1();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:112d

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_112d(void)

{
  char *pcVar1;
  undefined2 uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  uint extraout_DX;
  uint extraout_DX_00;
  uint unaff_BP;
  char *pcVar6;
  uint *puVar7;
  uint *puVar8;
  uint *puVar9;
  undefined2 unaff_DS;
  
  if (*(char *)0xff43 != '\0') {
    *(undefined1 *)0xff44 = 0xff;
    FUN_0000_10e3();
    FUN_0000_108f();
    uVar2 = _DAT_0000_ff2c;
    _DAT_0000_523b = *(undefined2 *)((uint)(byte)(cRam00000092 - 1) * 2 + 0x4264);
    iVar3 = 4;
    pcVar6 = _DAT_0000_523f;
    puVar7 = _DAT_0000_523d;
    do {
      iVar4 = 4;
      puVar9 = puVar7;
      do {
        pcVar1 = pcVar6;
        pcVar6 = pcVar6 + 1;
        if (*pcVar1 == -1) {
          puVar9 = puVar9 + 0xa0;
        }
        else {
          iVar5 = 8;
          puVar8 = puVar9;
          do {
            FUN_0000_11d3();
            *puVar8 = *puVar8 & ~unaff_BP;
            *puVar8 = *puVar8 | extraout_DX;
            FUN_0000_11d3();
            puVar8[1] = puVar8[1] & unaff_BP;
            puVar8[1] = puVar8[1] | extraout_DX_00;
            puVar9 = puVar8 + 0x1000;
            if ((uint *)0x7fff < puVar9) {
              puVar9 = puVar8 + -0x2fb0;
            }
            iVar5 = iVar5 + -1;
            puVar8 = puVar9;
          } while (iVar5 != 0);
        }
        iVar4 = iVar4 + -1;
      } while (iVar4 != 0);
      puVar7 = puVar7 + 2;
      iVar3 = iVar3 + -1;
    } while (iVar3 != 0);
    return;
  }
  return;
}



// Address: 0000:11d3

undefined4 __cdecl16near FUN_0000_11d3(void)

{
  uint in_AX;
  uint uVar1;
  char cVar2;
  byte bVar3;
  
  uVar1 = 0;
  cVar2 = CARRY2(in_AX,in_AX) * '\x02' + CARRY2(in_AX * 2,in_AX * 2);
  if (cVar2 != '\0') {
    bVar3 = DAT_0000_523c;
    if (cVar2 != '\x03') {
      bVar3 = DAT_0000_523b;
    }
    uVar1 = (CONCAT11(bVar3,cVar2) & 0xf0ff) >> 8;
  }
  cVar2 = CARRY2(in_AX * 4,in_AX * 4) * '\x02' + CARRY2(in_AX * 8,in_AX * 8);
  if (cVar2 != '\0') {
    bVar3 = DAT_0000_523c;
    if (cVar2 != '\x03') {
      bVar3 = DAT_0000_523b;
    }
    uVar1 = (uint)(byte)((byte)uVar1 | bVar3 & 0xf);
  }
  cVar2 = CARRY2(in_AX * 0x10,in_AX * 0x10) * '\x02' + CARRY2(in_AX * 0x20,in_AX * 0x20);
  if (cVar2 != '\0') {
    bVar3 = DAT_0000_523c;
    if (cVar2 != '\x03') {
      bVar3 = DAT_0000_523b;
    }
    uVar1 = CONCAT11(bVar3,(char)uVar1) & 0xf0ff;
  }
  cVar2 = CARRY2(in_AX * 0x40,in_AX * 0x40) * '\x02' + CARRY2(in_AX * 0x80,in_AX * 0x80);
  if (cVar2 == '\0') {
    return CONCAT22(uVar1,in_AX * 0x100);
  }
  bVar3 = DAT_0000_523c;
  if (cVar2 != '\x03') {
    bVar3 = DAT_0000_523b;
  }
  return CONCAT22(CONCAT11((byte)(uVar1 >> 8) | bVar3 & 0xf,(char)uVar1),in_AX * 0x100);
}



// Address: 0000:127e

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_127e(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  undefined2 unaff_DS;
  int iVar4;
  
  if (*(char *)0xff37 != '\0') {
    return;
  }
  *(undefined1 *)0xff37 = 0xff;
  iVar1 = 3;
  iVar3 = _DAT_0000_5233;
  do {
    iVar2 = 3;
    do {
      iVar4 = iVar3;
      FUN_0000_07ca(iVar3);
      iVar3 = iVar4 + 4;
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    iVar3 = iVar4 + 0x138;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:16f1

void __cdecl16near FUN_0000_16f1(void)

{
  uint unaff_SI;
  
  if (unaff_SI < 0xe900) {
    return;
  }
  return;
}



// Address: 0000:219f

undefined2 __cdecl16near FUN_0000_219f(void)

{
  byte bVar1;
  int in_AX;
  undefined1 uVar2;
  int iVar3;
  byte in_DL;
  bool bVar4;
  
  iVar3 = 4;
  do {
    bVar4 = CARRY1(in_DL,in_DL);
    in_DL = in_DL * '\x02';
    uVar2 = (undefined1)((uint)(in_AX * 0x10) >> 8);
    bVar1 = (byte)(in_AX * 0x10) | -bVar4 & 0xfU;
    in_AX = CONCAT11(uVar2,bVar1);
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return CONCAT11(bVar1,uVar2);
}



