/* Decompiled from chunk_02.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:01a4

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 __cdecl16near FUN_0000_01a4(void)

{
  char cVar1;
  undefined2 in_CX;
  undefined1 uVar3;
  undefined2 uVar2;
  int iVar4;
  undefined2 unaff_SI;
  uint unaff_DI;
  uint uVar5;
  uint uVar6;
  
  DAT_0000_4aab = '\0';
  iVar4 = 8;
  do {
    DAT_0000_4aaa = DAT_0000_4aab;
    DAT_0000_ff1a = 0;
    uVar2 = in_CX;
    uVar6 = unaff_DI;
    do {
      (*_DAT_0000_4aae)(uVar6,unaff_SI);
      DAT_0000_4aaa = DAT_0000_4aaa + '\x01';
      uVar3 = (undefined1)((uint)uVar2 >> 8);
      uVar5 = unaff_DI + 0x2000;
      if (0x3fff < uVar5) {
        uVar5 = unaff_DI + 0xe050;
      }
      cVar1 = (char)uVar2 + -1;
      if (cVar1 == '\0') break;
      (*_DAT_0000_4aae)();
      DAT_0000_4aaa = DAT_0000_4aaa + '\x01';
      unaff_DI = uVar5 + 0x2000;
      if (0x3fff < unaff_DI) {
        unaff_DI = uVar5 + 0xe050;
      }
      uVar2 = CONCAT11(uVar3,cVar1 + -1);
    } while ((char)(cVar1 + -1) != '\0');
    unaff_DI = uVar6;
    DAT_0000_4aab = DAT_0000_4aab + '\x01';
    do {
    } while (DAT_0000_ff1a < 0x14);
    iVar4 = iVar4 + -1;
    if (iVar4 == 0) {
      return uVar3;
    }
  } while( true );
}



// Address: 0000:1a01

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int __cdecl16near FUN_0000_1a01(void)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  int in_AX;
  int iVar5;
  bool bVar6;
  bool bVar7;
  bool bVar8;
  bool bVar9;
  
  iVar5 = 8;
  do {
    bVar6 = (int)_DAT_0000_4aa8 < 0;
    uVar1 = _DAT_0000_4aa8 << 1 | (uint)bVar6;
    bVar7 = (int)_DAT_0000_4aa6 < 0;
    uVar2 = _DAT_0000_4aa6 << 1 | (uint)bVar7;
    bVar8 = (int)_DAT_0000_4aa4 < 0;
    uVar3 = _DAT_0000_4aa4 << 1 | (uint)bVar8;
    bVar9 = (int)_DAT_0000_4aa2 < 0;
    uVar4 = _DAT_0000_4aa2 << 1 | (uint)bVar9;
    _DAT_0000_4aa8 = uVar1 << 1 | (uint)((int)uVar1 < 0);
    _DAT_0000_4aa6 = uVar2 << 1 | (uint)((int)uVar2 < 0);
    _DAT_0000_4aa4 = uVar3 << 1 | (uint)((int)uVar3 < 0);
    _DAT_0000_4aa2 = uVar4 << 1 | (uint)((int)uVar4 < 0);
    in_AX = CONCAT11((char)((uint)(in_AX * 4) >> 8),
                     (byte)(in_AX * 4) |
                     *(byte *)((((((((uint)bVar6 * 2 + (uint)bVar7) * 2 + (uint)bVar8) * 2 +
                                  (uint)bVar9) * 2 + (uint)((int)uVar1 < 0)) * 2 +
                                (uint)((int)uVar2 < 0)) * 2 + (uint)((int)uVar3 < 0)) * 2 +
                               (uint)((int)uVar4 < 0) + _DAT_0000_4aa0));
    iVar5 = iVar5 + -1;
  } while (iVar5 != 0);
  return in_AX;
}



