/* Decompiled from chunk_06.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0243

void __cdecl16near FUN_0000_0243(void)

{
  undefined1 uVar1;
  undefined1 uVar2;
  int iVar3;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)&DAT_0000_ff1d == '\0') {
    return;
  }
  *(undefined1 *)&DAT_0000_ff1d = 0;
  iVar3 = (uint)(byte)((*(char *)0x83 + '\x04') * '\b' + 5) + *(int *)0xff2a;
  if ((*(byte *)0xc2 & 1) == 0) {
    if (((*(char *)(iVar3 + 8) != -3) && (*(char *)(iVar3 + 0x10) != -3)) &&
       (*(char *)(iVar3 + 0x18) != -3)) {
      return;
    }
    FUN_0000_0a98();
    if ((*(byte *)(unaff_SI + 6) & 0xc0) != 0) {
      return;
    }
    uVar1 = *(undefined1 *)(unaff_SI + 2);
    uVar2 = *(undefined1 *)(unaff_SI + 5);
    *(undefined1 *)(unaff_SI + 5) = 7;
    *(byte *)(unaff_SI + 2) = *(byte *)(unaff_SI + 2) | 0x80;
    *(byte *)(unaff_SI + 4) = *(byte *)(unaff_SI + 4) | 1;
    FUN_0000_035e();
    *(undefined1 *)(unaff_SI + 5) = uVar2;
    *(undefined1 *)(unaff_SI + 2) = uVar1;
    return;
  }
  if (((*(char *)(iVar3 + -8) != -3) && (*(char *)(iVar3 + -0x10) != -3)) &&
     (*(char *)(iVar3 + -0x18) != -3)) {
    return;
  }
  FUN_0000_0a98();
  if ((*(byte *)(unaff_SI + 6) & 0xc0) != 0) {
    return;
  }
  uVar1 = *(undefined1 *)(unaff_SI + 2);
  uVar2 = *(undefined1 *)(unaff_SI + 5);
  *(undefined1 *)(unaff_SI + 5) = 7;
  *(byte *)(unaff_SI + 2) = *(byte *)(unaff_SI + 2) & 0x7f;
  *(byte *)(unaff_SI + 4) = *(byte *)(unaff_SI + 4) | 1;
  FUN_0000_035e();
  *(undefined1 *)(unaff_SI + 5) = uVar2;
  *(undefined1 *)(unaff_SI + 2) = uVar1;
  return;
}



// Address: 0000:02f1

void __cdecl16near FUN_0000_02f1(void)

{
  int iVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  iVar1 = (uint)(byte)((*(char *)0x83 + '\x04') * '\b' + 5) + *(int *)0xff2a;
  if ((*(byte *)0xc2 & 1) != 0) {
    if (*(char *)(iVar1 + -0x10) != -3) {
      return;
    }
    FUN_0000_0a98();
    if ((*(byte *)(unaff_SI + 2) & 0x80) != 0) {
      return;
    }
    if ((*(byte *)(unaff_SI + 6) & 0x80) == 0) {
      return;
    }
    *(byte *)(unaff_SI + 4) = *(byte *)(unaff_SI + 4) | 1;
    *(undefined1 *)0x7c5c = 0xff;
    FUN_0000_035e();
    return;
  }
  if (*(char *)(iVar1 + 0x10) != -3) {
    return;
  }
  FUN_0000_0a98();
  if ((*(byte *)(unaff_SI + 2) & 0x80) == 0) {
    return;
  }
  if ((*(byte *)(unaff_SI + 6) & 0x80) == 0) {
    return;
  }
  *(byte *)(unaff_SI + 4) = *(byte *)(unaff_SI + 4) | 1;
  *(undefined1 *)0x7c5c = 0xff;
  FUN_0000_035e();
  return;
}



// Address: 0000:035e

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_035e(void)

{
  undefined1 *puVar1;
  undefined1 uVar2;
  undefined2 uVar3;
  int iVar4;
  int unaff_SI;
  undefined1 *puVar5;
  undefined2 unaff_DS;
  
  *(byte *)(unaff_SI + 6) = *(byte *)(unaff_SI + 6) & 0x7f;
  uVar2 = *(undefined1 *)(unaff_SI + 7);
  *(undefined1 *)0xff1a = 0x28;
  FUN_0000_08b3(uVar2);
  *(undefined1 *)0xff75 = 0x1e;
  uVar3 = 0x718;
  if ((*(byte *)0xc2 & 1) == 0) {
    uVar3 = 0xb18;
  }
  *(undefined2 *)0x7c4c = uVar3;
  (*_DAT_0000_2026)();
  *(undefined1 *)&DAT_0000_ff1d = 0;
  FUN_0000_03c9();
  (*_DAT_0000_2028)();
  *(undefined1 *)&DAT_0000_ff1d = 0;
  puVar5 = (undefined1 *)0xe000;
  for (iVar4 = 0xe0; iVar4 != 0; iVar4 = iVar4 + -1) {
    puVar1 = puVar5;
    puVar5 = puVar5 + 1;
    *puVar1 = 0xfe;
  }
  *(undefined1 *)0x7c5c = 0;
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  return;
}



// Address: 0000:03c9

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_03c9(void)

{
  char cVar1;
  undefined2 uVar2;
  char cVar3;
  undefined2 in_AX;
  byte in_CL;
  undefined1 uVar5;
  int iVar4;
  uint in_BX;
  undefined2 unaff_DS;
  
  *(byte *)0xe7 = *(byte *)0xe7 | 1;
  *(undefined2 *)0x7c50 = in_AX;
  *(undefined2 *)0x7c4e = in_AX;
  uVar2 = *(undefined2 *)((in_BX & 0xff) * 2 + *(int *)0xc00d);
  *(undefined1 *)0x7c53 = 0;
  *(undefined1 *)0x7c54 = 0;
  *(undefined1 *)0x7c55 = 0;
  *(undefined1 *)0x7c57 = 0;
  *(undefined2 *)0x7c58 = uVar2;
  FUN_0000_060d();
  *(byte *)0x7c56 = in_CL;
  if (7 < in_CL) {
    in_CL = 8;
  }
  cVar3 = in_CL * '\n' + '\x06';
  *(undefined2 *)0x7c5a = CONCAT11(0x2c,cVar3);
  *(undefined2 *)0x7c4e =
       CONCAT11((char)((uint)*(undefined2 *)0x7c4e >> 8),
                ((char)*(undefined2 *)0x7c4e + ('V' - cVar3)) -
                ((byte)((in_CL & 0xfe) * -8 + 0x40) >> 1));
  (*_DAT_0000_2000)();
LAB_0000_043b:
  cVar3 = *(char *)*(undefined2 *)0x7c58;
  *(int *)0x7c58 = (int)((char *)*(undefined2 *)0x7c58 + 1);
  if (cVar3 != '/') goto LAB_0000_044b;
  goto LAB_0000_04ea;
LAB_0000_044b:
  if (cVar3 == -0x7f) {
    FUN_0000_0659();
    return;
  }
  if (cVar3 == -0x7d) {
    FUN_0000_0689();
    return;
  }
  if (cVar3 == -0x7b) {
    FUN_0000_0699();
    return;
  }
  if (cVar3 == -0x79) {
    FUN_0000_06a6();
    return;
  }
  if (cVar3 == -0x77) {
    FUN_0000_06b1();
    return;
  }
  if (cVar3 == -0x75) {
    FUN_0000_0651();
    return;
  }
  if (cVar3 == -1) {
    FUN_0000_05a5();
    return;
  }
  uVar5 = (undefined1)((uint)*(undefined2 *)0x7c4e >> 8);
  (*_DAT_0000_2022)();
  cVar1 = *(char *)((byte)(cVar3 - 0x20) + 0x7be2);
  iVar4 = CONCAT11(uVar5,cVar1);
  *(char *)0x7c53 = *(char *)0x7c53 + cVar1;
  if ((cVar3 == ' ') && (FUN_0000_05ea(), 0xa7 < (uint)*(byte *)0x7c53 + iVar4)) {
LAB_0000_04ea:
    *(undefined1 *)0x7c53 = 0;
    *(char *)0x7c54 = *(char *)0x7c54 + '\x01';
    if (*(char *)0x7c54 == '\b') {
      *(char *)0x7c54 = *(char *)0x7c54 + -1;
      iVar4 = 10;
      do {
        (*_DAT_0000_2024)();
        iVar4 = iVar4 + -1;
      } while (iVar4 != 0);
    }
    *(char *)0x7c57 = *(char *)0x7c57 + '\x01';
    if ((6 < *(byte *)0x7c57) && (*(char *)0x7c56 != '\b')) {
      *(char *)0x7c56 = *(char *)0x7c56 + -7;
      (*_DAT_0000_2022)((*(uint *)0x7c4e >> 8) * 8 + 0x54);
      *(undefined1 *)&DAT_0000_ff1d = 0;
      *(undefined1 *)0xff1e = 0;
      do {
        FUN_0000_0747();
        FUN_0000_08b0();
        if ((*(char *)0x7c5c == '\0') && (*(char *)0xff1e != '\0')) {
          return;
        }
      } while (*(char *)&DAT_0000_ff1d == '\0');
      (*_DAT_0000_2000)();
      *(undefined1 *)&DAT_0000_ff1d = 0;
      *(undefined1 *)0x7c57 = 0;
      *(undefined1 *)0xff75 = 0x1d;
    }
  }
  goto LAB_0000_043b;
}



// Address: 0000:03ce

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_03ce(void)

{
  char cVar1;
  undefined2 uVar2;
  char cVar3;
  undefined2 in_AX;
  byte in_CL;
  undefined1 uVar5;
  int iVar4;
  uint in_BX;
  undefined2 unaff_DS;
  
  *(undefined2 *)0x7c50 = in_AX;
  *(undefined2 *)0x7c4e = in_AX;
  uVar2 = *(undefined2 *)((in_BX & 0xff) * 2 + *(int *)0xc00d);
  *(undefined1 *)0x7c53 = 0;
  *(undefined1 *)0x7c54 = 0;
  *(undefined1 *)0x7c55 = 0;
  *(undefined1 *)0x7c57 = 0;
  *(undefined2 *)0x7c58 = uVar2;
  FUN_0000_060d();
  *(byte *)0x7c56 = in_CL;
  if (7 < in_CL) {
    in_CL = 8;
  }
  cVar3 = in_CL * '\n' + '\x06';
  *(undefined2 *)0x7c5a = CONCAT11(0x2c,cVar3);
  *(undefined2 *)0x7c4e =
       CONCAT11((char)((uint)*(undefined2 *)0x7c4e >> 8),
                ((char)*(undefined2 *)0x7c4e + ('V' - cVar3)) -
                ((byte)((in_CL & 0xfe) * -8 + 0x40) >> 1));
  (*_DAT_0000_2000)();
LAB_0000_043b:
  cVar3 = *(char *)*(undefined2 *)0x7c58;
  *(int *)0x7c58 = (int)((char *)*(undefined2 *)0x7c58 + 1);
  if (cVar3 != '/') goto LAB_0000_044b;
  goto LAB_0000_04ea;
LAB_0000_044b:
  if (cVar3 == -0x7f) {
    FUN_0000_0659();
    return;
  }
  if (cVar3 == -0x7d) {
    FUN_0000_0689();
    return;
  }
  if (cVar3 == -0x7b) {
    FUN_0000_0699();
    return;
  }
  if (cVar3 == -0x79) {
    FUN_0000_06a6();
    return;
  }
  if (cVar3 == -0x77) {
    FUN_0000_06b1();
    return;
  }
  if (cVar3 == -0x75) {
    FUN_0000_0651();
    return;
  }
  if (cVar3 == -1) {
    FUN_0000_05a5();
    return;
  }
  uVar5 = (undefined1)((uint)*(undefined2 *)0x7c4e >> 8);
  (*_DAT_0000_2022)();
  cVar1 = *(char *)((byte)(cVar3 - 0x20) + 0x7be2);
  iVar4 = CONCAT11(uVar5,cVar1);
  *(char *)0x7c53 = *(char *)0x7c53 + cVar1;
  if ((cVar3 == ' ') && (FUN_0000_05ea(), 0xa7 < (uint)*(byte *)0x7c53 + iVar4)) {
LAB_0000_04ea:
    *(undefined1 *)0x7c53 = 0;
    *(char *)0x7c54 = *(char *)0x7c54 + '\x01';
    if (*(char *)0x7c54 == '\b') {
      *(char *)0x7c54 = *(char *)0x7c54 + -1;
      iVar4 = 10;
      do {
        (*_DAT_0000_2024)();
        iVar4 = iVar4 + -1;
      } while (iVar4 != 0);
    }
    *(char *)0x7c57 = *(char *)0x7c57 + '\x01';
    if ((6 < *(byte *)0x7c57) && (*(char *)0x7c56 != '\b')) {
      *(char *)0x7c56 = *(char *)0x7c56 + -7;
      (*_DAT_0000_2022)((*(uint *)0x7c4e >> 8) * 8 + 0x54);
      *(undefined1 *)&DAT_0000_ff1d = 0;
      *(undefined1 *)0xff1e = 0;
      do {
        FUN_0000_0747();
        FUN_0000_08b0();
        if ((*(char *)0x7c5c == '\0') && (*(char *)0xff1e != '\0')) {
          return;
        }
      } while (*(char *)&DAT_0000_ff1d == '\0');
      (*_DAT_0000_2000)();
      *(undefined1 *)&DAT_0000_ff1d = 0;
      *(undefined1 *)0x7c57 = 0;
      *(undefined1 *)0xff75 = 0x1d;
    }
  }
  goto LAB_0000_043b;
}



// Address: 0000:05a5

void __cdecl16near FUN_0000_05a5(void)

{
  undefined2 unaff_DS;
  
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  while( true ) {
    FUN_0000_0747();
    FUN_0000_08b0();
    if (*(char *)&DAT_0000_ff1d != '\0') {
      return;
    }
    if (*(char *)0xff1e != '\0') break;
    if (*(char *)0xff17 == '\0') {
      while( true ) {
        FUN_0000_0747();
        FUN_0000_08b0();
        if (*(char *)&DAT_0000_ff1d != '\0') {
          return;
        }
        if (*(char *)0xff1e != '\0') break;
        if (*(char *)0xff17 != '\0') {
          return;
        }
      }
      return;
    }
  }
  return;
}



// Address: 0000:05ea

void __cdecl16near FUN_0000_05ea(void)

{
  char *pcVar1;
  char cVar2;
  char *unaff_SI;
  undefined2 unaff_DS;
  
  while( true ) {
    pcVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    cVar2 = *pcVar1;
    if (cVar2 < '\0') {
      return;
    }
    if (cVar2 == ' ') break;
    if (cVar2 == '/') {
      return;
    }
  }
  return;
}



// Address: 0000:060d

void __cdecl16near FUN_0000_060d(void)

{
  char *pcVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int extraout_DX;
  char *unaff_SI;
  undefined2 unaff_DS;
  
  iVar3 = 0;
  iVar5 = 0;
  while( true ) {
    pcVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    cVar2 = *pcVar1;
    if (cVar2 < '\0') break;
    if (cVar2 == '/') {
      iVar3 = iVar3 + 1;
      iVar5 = 0;
    }
    else {
      iVar5 = iVar5 + (uint)*(byte *)((byte)(cVar2 - 0x20) + 0x7be2);
      if (cVar2 == ' ') {
        iVar4 = iVar3;
        FUN_0000_05ea();
        if (0xa7 < (uint)(extraout_DX + iVar4)) {
          iVar5 = 0;
          iVar3 = iVar3 + 1;
        }
      }
    }
  }
  if (iVar5 == 0) {
    return;
  }
  return;
}



// Address: 0000:0651

void FUN_0000_0651(void)

{
  undefined2 unaff_DS;
  
  *(byte *)0x4 = *(byte *)0x4 | 0x80;
  FUN_0000_0af1();
  return;
}



// Address: 0000:0659

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_0659(void)

{
  undefined2 unaff_DS;
  bool bVar1;
  uint in_stack_00000000;
  
  (*_DAT_0000_2000)(CONCAT11((char)((uint)*(undefined2 *)0x7c4c >> 8) * '\x02',
                             (char)*(undefined2 *)0x7c4c) + 0x193f);
  bVar1 = 0xfefc < in_stack_00000000;
  *(int *)0xff54 = in_stack_00000000 + 0x103;
  FUN_0000_14d7();
  if (bVar1) {
    FUN_0000_03c9();
    return;
  }
  FUN_0000_03c9();
  return;
}



// Address: 0000:0689

void FUN_0000_0689(void)

{
  undefined2 unaff_DS;
  
  *(byte *)0x34 = *(byte *)0x34 | 0x80;
  *(undefined1 *)0x9a = 0xff;
  FUN_0000_0af1();
  FUN_0000_05a5();
  return;
}



// Address: 0000:0699

void FUN_0000_0699(void)

{
  undefined2 unaff_DS;
  
  *(undefined1 *)0x7c5c = 0xff;
  FUN_0000_03c9();
  return;
}



// Address: 0000:06a6

void FUN_0000_06a6(void)

{
  FUN_0000_05a5();
  FUN_0000_03c9();
  return;
}



// Address: 0000:06b1

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_06b1(void)

{
  char *pcVar1;
  undefined2 unaff_DS;
  bool bVar2;
  uint in_stack_00000000;
  
  (*_DAT_0000_2000)(CONCAT11((char)((uint)*(undefined2 *)0x7c4c >> 8) * '\x02',
                             (char)*(undefined2 *)0x7c4c) + 0x1832);
  bVar2 = 0xfdfc < in_stack_00000000;
  *(int *)0xff54 = in_stack_00000000 + 0x203;
  FUN_0000_0712();
  if (bVar2) {
    FUN_0000_03c9();
    return;
  }
  if (*(uint *)0x8b < 0x9c4) {
    FUN_0000_03c9();
    return;
  }
  *(int *)0x8b = *(uint *)0x8b - 0x9c4;
  (*_DAT_0000_2014)();
  *(byte *)0x34 = *(byte *)0x34 | 0x40;
  for (pcVar1 = (char *)0xa1; *pcVar1 != '\0'; pcVar1 = pcVar1 + 1) {
  }
  *pcVar1 = '\x05';
  FUN_0000_0af1();
  FUN_0000_03c9();
  return;
}



// Address: 0000:0712

void __cdecl16near FUN_0000_0712(void)

{
  char cVar1;
  undefined2 unaff_DS;
  bool bVar2;
  
  *(undefined1 *)0xff52 = 2;
  *(undefined1 *)0xff53 = 2;
  FUN_0000_151e();
  *(undefined1 *)0xff56 = 0;
  bVar2 = false;
  cVar1 = '\0';
  FUN_0000_1348();
  if (bVar2) {
    cVar1 = '\x01';
  }
  if (cVar1 == '\0') {
    return;
  }
  return;
}



// Address: 0000:0747

void __cdecl16near FUN_0000_0747(void)

{
  byte bVar1;
  int iVar2;
  uint uVar3;
  undefined1 *puVar4;
  undefined1 *puVar5;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  bVar1 = (char)*(undefined2 *)0x7c4e + (char)*(undefined2 *)0x7c5a;
  if (bVar1 < 0x56) {
    return;
  }
  uVar3 = (uint)((byte)(bVar1 + 0xb2) / 8);
  puVar4 = (undefined1 *)((uint)(byte)((char)((uint)*(undefined2 *)0x7c4e >> 8) - 6) * 8 + -0x2000);
  do {
    iVar2 = 0x16;
    puVar5 = puVar4;
    do {
      *puVar5 = 0xff;
      puVar5 = puVar5 + 8;
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    puVar4 = puVar4 + 1;
    uVar3 = uVar3 - 1;
  } while (uVar3 != 0);
  return;
}



// Address: 0000:0785

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0785(void)

{
  undefined2 unaff_DS;
  bool bVar1;
  
  bVar1 = (uint)(byte)(*(char *)0x83 + 3) * 8 + *(int *)0xff2a == 0;
  FUN_0000_0872();
  if (bVar1) {
    return;
  }
  bVar1 = (uint)(byte)(*(char *)0x83 + 4) + *(int *)0x80 == 1;
  FUN_0000_0894();
  if (!bVar1) {
    return;
  }
  *(char *)0xe7 = *(char *)0xe7 + '\x01';
  *(byte *)0xe7 = *(byte *)0xe7 & 3;
  *(byte *)0xc2 = *(byte *)0xc2 | 1;
  if (10 < *(byte *)0x83) {
    *(char *)0x83 = *(char *)0x83 + -1;
    return;
  }
  if (*(int *)0x80 == 0) {
    *(char *)0x83 = *(char *)0x83 + -1;
    return;
  }
  *(int *)0x80 = *(int *)0x80 + -1;
  *(int *)0xff2a = *(int *)0xff2a + -8;
  (*_DAT_0000_3006)();
  if (*(char *)0x7c45 != '\x01') {
    return;
  }
  (*_DAT_0000_3008)();
  return;
}



// Address: 0000:07f8

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_07f8(void)

{
  undefined2 unaff_DS;
  bool bVar1;
  
  bVar1 = (uint)(byte)(*(char *)0x83 + 6) * 8 + *(int *)0xff2a == 0;
  FUN_0000_0872();
  if (bVar1) {
    return;
  }
  bVar1 = (uint)(byte)(*(char *)0x83 + 4) + *(int *)0x80 == -1;
  FUN_0000_0894();
  if (!bVar1) {
    return;
  }
  *(char *)0xe7 = *(char *)0xe7 + '\x01';
  *(byte *)0xe7 = *(byte *)0xe7 & 3;
  *(byte *)0xc2 = *(byte *)0xc2 & 0xfe;
  if (*(byte *)0x83 < 0x10) {
    *(char *)0x83 = *(char *)0x83 + '\x01';
    return;
  }
  if (*(int *)0xc002 + -0x23 == *(int *)0x80 + 1) {
    *(char *)0x83 = *(char *)0x83 + '\x01';
    return;
  }
  *(int *)0x80 = *(int *)0x80 + 1;
  *(int *)0xff2a = *(int *)0xff2a + 8;
  (*_DAT_0000_300a)();
  if (*(char *)0x7c45 != '\x01') {
    return;
  }
  (*_DAT_0000_300c)();
  return;
}



// Address: 0000:0872

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0872(void)

{
  byte in_AL;
  uint uVar1;
  byte *pbVar2;
  
  pbVar2 = (byte *)*(undefined2 *)0x8002;
  if (*pbVar2 != 0) {
    uVar1 = (uint)*pbVar2;
    do {
      pbVar2 = pbVar2 + 1;
      if (in_AL == *pbVar2) {
        return;
      }
      uVar1 = uVar1 - 1;
    } while (uVar1 != 0);
  }
  return;
}



// Address: 0000:0894

void __cdecl16near FUN_0000_0894(void)

{
  int in_BX;
  int *piVar1;
  undefined2 unaff_DS;
  
  piVar1 = (int *)*(undefined2 *)0xc00f;
  while( true ) {
    if (*piVar1 == -1) {
      return;
    }
    if ((*piVar1 == in_BX) && ((*(byte *)(piVar1 + 3) & 0x40) != 0)) break;
    piVar1 = piVar1 + 4;
  }
  return;
}



// Address: 0000:08b0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_08b0(void)

{
  undefined2 unaff_DS;
  undefined1 uVar1;
  
  FUN_0000_0b20();
  FUN_0000_0979();
  FUN_0000_0954();
  (*_DAT_0000_3004)();
  uVar1 = (char)((uint)*(byte *)0xff33 * 4 >> 8) != '\0';
  do {
    (*pcRam00000110)();
    (*pcRam00000112)();
    (*pcRam00000114)();
    (*pcRam00000116)();
    (*pcRam00000118)();
    (*pcRam0000011e)();
    if ((bool)uVar1) {
      FUN_0000_1596();
    }
    uVar1 = true;
  } while (*(byte *)0xff1a < 0xd1);
  *(undefined1 *)0xff1a = 0;
  return;
}



// Address: 0000:08b3

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_08b3(void)

{
  undefined2 unaff_DS;
  undefined1 uVar1;
  
  FUN_0000_0979();
  FUN_0000_0954();
  (*_DAT_0000_3004)();
  uVar1 = (char)((uint)*(byte *)0xff33 * 4 >> 8) != '\0';
  do {
    (*pcRam00000110)();
    (*pcRam00000112)();
    (*pcRam00000114)();
    (*pcRam00000116)();
    (*pcRam00000118)();
    (*pcRam0000011e)();
    if ((bool)uVar1) {
      FUN_0000_1596();
    }
    uVar1 = true;
  } while (*(byte *)0xff1a < 0xd1);
  *(undefined1 *)0xff1a = 0;
  return;
}



// Address: 0000:08f7

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_08f7(void)

{
  undefined1 *puVar1;
  int iVar2;
  undefined1 *puVar3;
  undefined2 unaff_DS;
  
  if ((*(uint *)&DAT_0000_ff18 & 1) == 0) {
    return;
  }
  *(undefined1 *)0xff75 = 0xb;
  (*_DAT_0000_2002)();
  FUN_0000_093c();
  (*_DAT_0000_a002)();
  FUN_0000_093c();
  (*_DAT_0000_2002)();
  FUN_0000_0aa9();
  (*_DAT_0000_3002)();
  puVar3 = (undefined1 *)0xe000;
  for (iVar2 = 0xe0; iVar2 != 0; iVar2 = iVar2 + -1) {
    puVar1 = puVar3;
    puVar3 = puVar3 + 1;
    *puVar1 = 0xfe;
  }
  FUN_0000_08b3();
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  return;
}



// Address: 0000:093c

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_093c(void)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  undefined2 uVar3;
  int iVar4;
  undefined2 *puVar5;
  undefined2 *puVar6;
  undefined2 unaff_DS;
  
  uVar3 = _DAT_0000_ff2c;
  puVar6 = (undefined2 *)0xc000;
  iVar4 = 0x800;
  puVar5 = (undefined2 *)&DAT_0000_a000;
  do {
    uVar2 = *puVar6;
    puVar1 = puVar6;
    puVar6 = puVar6 + 1;
    *puVar1 = *puVar5;
    *puVar5 = uVar2;
    iVar4 = iVar4 + -1;
    puVar5 = puVar5 + 1;
  } while (iVar4 != 0);
  return;
}



// Address: 0000:0954

void __cdecl16near FUN_0000_0954(void)

{
  uint uVar1;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  if (0x1a < *(byte *)0x83) {
    return;
  }
  uVar1 = (uint)(byte)(*(byte *)0x83 * '\b' + 5);
  *(undefined1 *)(uVar1 + 0xe000) = 0xff;
  *(undefined1 *)(uVar1 + 0xe001) = 0xff;
  *(undefined1 *)(uVar1 + 0xe002) = 0xff;
  *(undefined1 *)(uVar1 + 0xe008) = 0xff;
  *(undefined1 *)(uVar1 + 0xe009) = 0xff;
  *(undefined1 *)(uVar1 + 0xe00a) = 0xff;
  return;
}



// Address: 0000:0979

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0979(void)

{
  char cVar1;
  undefined2 *puVar2;
  int iVar3;
  int iVar4;
  char *pcVar5;
  int *piVar6;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  undefined1 *in_stack_00000000;
  char *pcVar7;
  
  puVar2 = (undefined2 *)((uint)(byte)(*(char *)0x83 + 4) * 8 + 5 + *(int *)0xff2a);
  *(undefined2 *)0x7c74 = *puVar2;
  *(undefined1 *)0x7c76 = *(undefined1 *)(puVar2 + 1);
  *(undefined2 *)0x7c77 = puVar2[4];
  *(undefined1 *)0x7c79 = *(undefined1 *)(puVar2 + 5);
  iVar4 = (uint)(byte)(*(char *)0x83 + 4) + *(int *)0x80;
  pcVar5 = (char *)0x7c74;
  iVar3 = 2;
  do {
    cVar1 = *pcVar5;
    pcVar7 = pcVar5;
    if (cVar1 == -3) {
      FUN_0000_0a98(pcVar5,iVar4);
      for (; cVar1 = pcVar5[3], cVar1 == -3; pcVar5 = pcVar5 + 8) {
        FUN_0000_0a9c();
      }
    }
    *pcVar7 = cVar1;
    pcVar5 = pcVar7 + 3;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  (*_DAT_0000_300e)();
  *(int *)0x7c49 = (int)puVar2 + -1;
  uRam00007c7a = in_stack_00000000[-8];
  uRam00007c7b = *in_stack_00000000;
  uRam00007c7c = in_stack_00000000[8];
  piVar6 = (int *)*(undefined2 *)0xc00f;
  do {
    cVar1 = FUN_0000_0a7b();
    if (cVar1 != '\0') {
      (*_DAT_0000_3014)();
      (*_DAT_0000_3010)();
      piVar6 = (int *)0xa14;
    }
    piVar6 = piVar6 + 4;
  } while (*piVar6 != -1);
  (*_DAT_0000_3012)();
  return;
}



// Address: 0000:0a7b

undefined1 __cdecl16near FUN_0000_0a7b(void)

{
  int iVar1;
  int iVar2;
  int *unaff_SI;
  char *pcVar3;
  undefined2 unaff_DS;
  
  iVar1 = 3;
  iVar2 = *(int *)0x7c49;
  pcVar3 = (char *)0x7c7a;
  do {
    if (*pcVar3 == -3) {
      if (iVar2 == *unaff_SI) {
        return (char)iVar1;
      }
    }
    pcVar3 = pcVar3 + 1;
    iVar2 = iVar2 + 1;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return 0;
}



// Address: 0000:0a98

void FUN_0000_0a98(void)

{
  int in_DX;
  int *piVar1;
  undefined2 unaff_DS;
  
  for (piVar1 = (int *)*(undefined2 *)0xc00f; in_DX != *piVar1; piVar1 = piVar1 + 4) {
  }
  return;
}



// Address: 0000:0a9c

void __cdecl16near FUN_0000_0a9c(void)

{
  int in_DX;
  int *unaff_SI;
  undefined2 unaff_DS;
  
  for (; in_DX != *unaff_SI; unaff_SI = unaff_SI + 4) {
  }
  return;
}



// Address: 0000:0aa6

void FUN_0000_0aa6(void)

{
  undefined2 unaff_DS;
  
  FUN_0000_0da2();
  (*(code *)*(undefined2 *)0x6ae9)();
  return;
}



// Address: 0000:0aa9

void __cdecl16near FUN_0000_0aa9(void)

{
  undefined2 unaff_DS;
  
  (*(code *)*(undefined2 *)0x6ae9)();
  return;
}



// Address: 0000:0ab3

void __cdecl16near FUN_0000_0ab3(void)

{
  int unaff_CS;
  undefined2 unaff_DS;
  
  *(int *)0x6aeb = unaff_CS + 0x2000;
  (*pcRam0000010c)();
  return;
}



// Address: 0000:0af1

void __cdecl16near FUN_0000_0af1(void)

{
  byte *pbVar1;
  undefined1 *puVar2;
  undefined2 *puVar3;
  undefined2 *puVar4;
  undefined2 unaff_DS;
  
  puVar3 = (undefined2 *)*(undefined2 *)0xc015;
  while( true ) {
    pbVar1 = (byte *)*puVar3;
    if ((byte)((byte)pbVar1 & (byte)((uint)pbVar1 >> 8)) == 0xff) break;
    puVar4 = (undefined2 *)((int)puVar3 + 3);
    if ((*(byte *)(puVar3 + 1) & *pbVar1) == 0) {
      while (puVar3 = puVar4 + 1, (byte)((byte)*puVar4 & (byte)((uint)*puVar4 >> 8)) != 0xff) {
        puVar4 = (undefined2 *)((int)puVar4 + 3);
      }
    }
    else {
      while( true ) {
        puVar3 = puVar4 + 1;
        puVar2 = (undefined1 *)*puVar4;
        if ((byte)((byte)puVar2 & (byte)((uint)puVar2 >> 8)) == 0xff) break;
        *puVar2 = *(undefined1 *)puVar3;
        puVar4 = (undefined2 *)((int)puVar4 + 3);
      }
    }
  }
  return;
}



// Address: 0000:0b20

void FUN_0000_0b20(void)

{
  int extraout_DX;
  int *piVar1;
  undefined2 unaff_DS;
  
  FUN_0000_0c52();
  for (piVar1 = (int *)*(undefined2 *)0xc00f; *piVar1 != -1; piVar1 = piVar1 + 4) {
    (*(code *)*(undefined2 *)((uint)*(byte *)((int)piVar1 + 5) * 2 + 0x6b41))();
    *piVar1 = extraout_DX;
  }
  FUN_0000_0c2f();
  return;
}



// Address: 0000:0c2f

void __cdecl16near FUN_0000_0c2f(void)

{
  undefined1 uVar1;
  int iVar2;
  int *piVar3;
  undefined2 unaff_DS;
  
  for (piVar3 = (int *)*(undefined2 *)0xc00f; *piVar3 != -1; piVar3 = piVar3 + 4) {
    iVar2 = *piVar3 * 8;
    uVar1 = *(undefined1 *)(iVar2 + -0x3fe4);
    *(undefined1 *)(iVar2 + -0x3fe4) = 0xfd;
    *(undefined1 *)((int)piVar3 + 3) = uVar1;
  }
  return;
}



// Address: 0000:0c52

void __cdecl16near FUN_0000_0c52(void)

{
  int *piVar1;
  undefined2 unaff_DS;
  
  for (piVar1 = (int *)*(undefined2 *)0xc00f; *piVar1 != -1; piVar1 = piVar1 + 4) {
    if (*(char *)((int)piVar1 + 3) != -3) {
      *(char *)(*piVar1 * 8 + -0x3fe4) = *(char *)((int)piVar1 + 3);
    }
  }
  return;
}



// Address: 0000:0c76

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0c76(void)

{
  (*_DAT_0000_200e)();
  (*_DAT_0000_200e)();
  (*_DAT_0000_200e)();
  (*_DAT_0000_200e)();
  return;
}



// Address: 0000:0cb9

/* WARNING (jumptable): Unable to track spacebase fully for stack */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: This function may have set the stack pointer */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0cb9(void)

{
  undefined1 *puVar1;
  code *pcVar2;
  char *pcVar3;
  byte bVar4;
  int iVar5;
  undefined1 *puVar6;
  undefined1 *puVar7;
  undefined1 *puVar8;
  undefined1 *puVar9;
  undefined1 *puVar10;
  undefined1 *puVar11;
  undefined1 *puVar12;
  undefined1 *puVar13;
  undefined1 *puVar14;
  undefined1 *puVar15;
  undefined1 *puVar16;
  undefined1 *puVar17;
  int *piVar18;
  int *piVar19;
  undefined1 *puVar20;
  undefined2 *puVar21;
  undefined1 *puVar22;
  char *pcVar23;
  byte *pbVar24;
  undefined1 *puVar25;
  undefined2 uVar26;
  undefined2 unaff_CS;
  undefined2 unaff_SS;
  undefined2 uVar27;
  undefined2 unaff_DS;
  
  if (*(char *)0x83 == -1) {
    FUN_0000_0c52();
    *(undefined1 *)0xff1a = 0x28;
    FUN_0000_08b3();
    for (pbVar24 = (byte *)*(undefined2 *)0xc007; (*pbVar24 & 1) == 0; pbVar24 = pbVar24 + 4) {
    }
    if ((*pbVar24 & 0xfe) != 0) {
      FUN_0000_0ffc();
      return;
    }
    FUN_0000_0d34();
    *(undefined1 *)0x83 = 0x1a;
    *(int *)0x80 = *(int *)0xc002 + -0x24;
  }
  else {
    if (*(char *)0x83 != '\x1b') {
      return;
    }
    FUN_0000_0c52();
    *(undefined1 *)0xff1a = 0x28;
    FUN_0000_08b3();
    for (pbVar24 = (byte *)*(undefined2 *)0xc007; (*pbVar24 & 1) != 0; pbVar24 = pbVar24 + 4) {
    }
    if ((*pbVar24 & 0xfe) != 0) {
      FUN_0000_0ffc();
      return;
    }
    FUN_0000_0d34();
    *(undefined1 *)0x83 = 0;
    *(undefined2 *)0x80 = 0;
  }
  *(undefined2 *)0x1ffe = unaff_CS;
  uVar27 = *(undefined2 *)0x1ffe;
  *(undefined2 *)0x1ffe = 0xc5;
  FUN_0000_0af1();
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  *(undefined1 *)0xe4 = 0;
  *(undefined1 *)0x9f = 0;
  pcVar2 = _DAT_0000_2004;
  puVar6 = (undefined1 *)0x1ffe;
  *(undefined2 *)0x1ffe = 0xdf;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2004;
  puVar7 = puVar6 + -2;
  *(undefined2 *)(puVar6 + -2) = 0xeb;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2004;
  puVar8 = puVar7 + -2;
  *(undefined2 *)(puVar7 + -2) = 0xf7;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2012;
  puVar9 = puVar8 + -2;
  *(undefined2 *)(puVar8 + -2) = 0xfc;
  (*pcVar2)();
  *(undefined2 *)(puVar9 + -2) = 0xff;
  FUN_0000_0c76();
  pcVar2 = _DAT_0000_2006;
  puVar10 = puVar9 + -2;
  *(undefined2 *)(puVar9 + -2) = 0x104;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2008;
  puVar11 = puVar10 + -2;
  *(undefined2 *)(puVar10 + -2) = 0x109;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2014;
  puVar12 = puVar11 + -2;
  *(undefined2 *)(puVar11 + -2) = 0x10e;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2016;
  puVar13 = puVar12 + -2;
  *(undefined2 *)(puVar12 + -2) = 0x113;
  (*pcVar2)();
  if (*(char *)0x9d != '\0') {
    pcVar2 = _DAT_0000_2004;
    puVar14 = puVar13 + -2;
    *(undefined2 *)(puVar13 + -2) = 0x126;
    (*pcVar2)();
    pcVar2 = _DAT_0000_2018;
    puVar13 = puVar14 + -2;
    *(undefined2 *)(puVar14 + -2) = 299;
    (*pcVar2)();
  }
  if (*(char *)0x93 != '\0') {
    pcVar2 = _DAT_0000_2004;
    puVar15 = puVar13 + -2;
    *(undefined2 *)(puVar13 + -2) = 0x13e;
    (*pcVar2)();
    pcVar2 = _DAT_0000_201a;
    puVar13 = puVar15 + -2;
    *(undefined2 *)(puVar15 + -2) = 0x143;
    (*pcVar2)();
  }
  pcVar23 = (char *)*(undefined2 *)0xc000;
  do {
    pcVar3 = pcVar23;
    pcVar23 = pcVar3 + 1;
  } while (*pcVar23 != -1);
  *(char *)0x7c46 = pcVar3[3];
  pcVar2 = _DAT_0000_2010;
  puVar16 = puVar13 + -2;
  *(undefined2 *)(puVar13 + -2) = 0x15b;
  (*pcVar2)();
  *(int *)0xff2a = (uint)*(byte *)0x80 * 8 + -0x3fe9;
  *(undefined2 *)(puVar16 + -2) = 0x16f;
  FUN_0000_0c2f();
  if (*(char *)0xe8 != '\0') {
    *(undefined1 *)0xe8 = 0;
    *(undefined2 *)(puVar16 + -2) = 0x17e;
    FUN_0000_0ab3();
    *(undefined2 *)(puVar16 + -2) = 0x61fc;
    *(undefined2 *)(puVar16 + -4) = 0x6eaf;
    *(undefined2 *)(puVar16 + -6) = 0;
    pcVar2 = pcRam0000010c;
    puVar17 = puVar16 + -6;
    *(undefined2 *)(puVar16 + -6) = 0x195;
    (*pcVar2)();
    pcVar2 = _DAT_0000_2040;
    *(undefined2 *)(puVar17 + -2) = 0x19a;
    (*pcVar2)();
    pcVar2 = (code *)swi(0x60);
    (*pcVar2)();
    *(undefined1 *)0x7c42 = 0xff;
                    /* WARNING: Could not recover jumptable at 0x000001a4. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*_DAT_0000_a004)();
    return;
  }
  *(undefined2 *)(puVar16 + -2) = 0;
  uVar26 = *(undefined2 *)(puVar16 + -2);
  puVar25 = (undefined1 *)0xe000;
  for (iVar5 = 0xe0; iVar5 != 0; iVar5 = iVar5 + -1) {
    puVar1 = puVar25;
    puVar25 = puVar25 + 1;
    *puVar1 = 0xfe;
  }
  piVar18 = (int *)(puVar16 + -2);
  *(undefined2 *)(puVar16 + -2) = 0x1b8;
  FUN_0000_08b0();
  if (*(char *)0x7c44 != '\0') {
    *(undefined2 *)&DAT_0000_7c47 = 0x6781;
    if ((*(byte *)0xc2 & 1) == 0) {
      *(undefined2 *)&DAT_0000_7c47 = 0x67f4;
    }
    iVar5 = 4;
    piVar19 = piVar18;
    do {
      *(int *)((int)piVar19 + -2) = iVar5;
      pcVar2 = _DAT_0000_7c47;
      puVar20 = (undefined1 *)((int)piVar19 + -4);
      *(undefined2 *)((int)piVar19 + -4) = 0x1db;
      (*pcVar2)();
      piVar18 = (int *)(puVar20 + -2);
      *(undefined2 *)(puVar20 + -2) = 0x1de;
      FUN_0000_08b0();
      piVar19 = piVar18 + 1;
      iVar5 = *piVar18 + -1;
    } while (iVar5 != 0);
    pcVar2 = _DAT_0000_7c47;
    *piVar18 = 0x1e6;
    (*pcVar2)();
  }
  *(undefined1 *)0x7c4b = 0;
  if (*(char *)0x49 != '\0') {
    puVar21 = (undefined2 *)((int)piVar18 + -2);
    *(undefined2 *)((int)piVar18 + -2) = uVar27;
    pcVar2 = (code *)swi(0x60);
    (*pcVar2)();
    uVar27 = *puVar21;
    piVar18 = puVar21 + 1;
  }
  puVar22 = (undefined1 *)((int)piVar18 + -2);
  *(undefined2 *)((int)piVar18 + -2) = 0x203;
  FUN_0000_08b0();
  *(undefined2 *)(puVar22 + -2) = 0x206;
  FUN_0000_08f7();
  *(undefined2 *)(puVar22 + -2) = 0x209;
  FUN_0000_0cb9();
  *(undefined2 *)(puVar22 + -2) = 0x20c;
  FUN_0000_0243();
  if (*(char *)0x7c4b == '\0') {
    *(undefined2 *)(puVar22 + -2) = 0x216;
    FUN_0000_02f1();
  }
  *(undefined1 *)0x7c4b = 0;
  *(undefined2 *)(puVar22 + -2) = 0x61fc;
  pcVar2 = (code *)swi(0x61);
  bVar4 = (*pcVar2)();
  if (bVar4 == 1) {
    FUN_0000_0e2d();
    return;
  }
  if ((bVar4 & 0xc) == 4) {
    FUN_0000_0785();
    return;
  }
  if ((bVar4 & 0xc) == 8) {
    FUN_0000_07f8();
    return;
  }
  *(byte *)0xe7 = *(byte *)0xe7 | 1;
  *(undefined1 *)0x7c4b = 0xff;
  return;
}



// Address: 0000:0d34

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0d34(undefined2 param_1,undefined2 param_2)

{
  byte in_AL;
  char cVar1;
  undefined2 *unaff_SI;
  undefined2 unaff_DS;
  
  *(byte *)0xc4 = in_AL | 0x80;
  (*pcRam0000010c)(*unaff_SI);
  (*pcRam0000010c)();
  (*_DAT_0000_3026)();
  cVar1 = (char)((uint)param_2 >> 8);
  if (cVar1 != *(char *)0x7c46) {
    *(char *)0x7c46 = cVar1;
    FUN_0000_0da2();
  }
  return;
}



// Address: 0000:0da2

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_0da2(void)

{
  undefined2 uVar1;
  
  uVar1 = _DAT_0000_ff2c;
  (*pcRam0000010c)();
  *(int *)0x8000 = *(int *)0x8000 + -0x8000;
  *(int *)0x8002 = *(int *)0x8002 + -0x8000;
  *(int *)0x8004 = *(int *)0x8004 + -0x8000;
                    /* WARNING: Could not recover jumptable at 0x00000dcd. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*_DAT_0000_3024)();
  return;
}



// Address: 0000:0df3

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0df3(void)

{
  (*pcRam0000010c)();
  (*_DAT_0000_3026)();
  return;
}



// Address: 0000:0e2d

/* WARNING (jumptable): Unable to track spacebase fully for stack */
/* WARNING: Unable to track spacebase fully for stack */
/* WARNING: This function may have set the stack pointer */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0e2d(void)

{
  undefined1 *puVar1;
  code *pcVar2;
  byte bVar3;
  int iVar4;
  undefined1 *puVar5;
  undefined1 *puVar6;
  undefined1 *puVar7;
  undefined1 *puVar8;
  undefined1 *puVar9;
  undefined1 *puVar10;
  undefined1 *puVar11;
  undefined1 *puVar12;
  undefined1 *puVar13;
  undefined1 *puVar14;
  undefined1 *puVar15;
  undefined1 *puVar16;
  undefined1 *puVar17;
  undefined1 *puVar18;
  undefined1 *puVar19;
  int *piVar20;
  undefined1 *puVar21;
  undefined2 *puVar22;
  undefined1 *puVar23;
  char *pcVar24;
  char *pcVar25;
  int *piVar26;
  undefined1 *puVar27;
  undefined2 uVar28;
  undefined2 unaff_SS;
  undefined2 uVar29;
  undefined2 unaff_DS;
  
  *(byte *)0xe7 = *(byte *)0xe7 | 1;
  iVar4 = *(int *)0x80 + (uint)*(byte *)0x83;
  piVar26 = (int *)*(undefined2 *)0xc009;
  while( true ) {
    if (*piVar26 == -1) {
      return;
    }
    if (((*piVar26 == iVar4 + 4) || (*piVar26 == iVar4 + 5)) || (*piVar26 == iVar4 + 3)) break;
    piVar26 = (int *)((int)piVar26 + 3);
  }
  *(undefined1 *)0xe7 = 4;
  FUN_0000_0c52();
  *(undefined1 *)0xff1a = 0x28;
  FUN_0000_08b3();
  if (*(byte *)(piVar26 + 1) != 0xff) {
    if (7 < *(byte *)(piVar26 + 1)) {
      FUN_0000_0ffc();
      return;
    }
    *(undefined1 *)0xff24 = 4;
    (*pcRam0000010c)();
    (*_DAT_0000_2040)();
    pcVar2 = (code *)swi(0x60);
    (*pcVar2)();
    *(undefined1 *)0x7c42 = 0xff;
    (*_DAT_0000_a000)();
    (*_DAT_0000_2002)();
    *(undefined1 *)0x7c42 = 0;
    (*_DAT_0000_2012)();
    FUN_0000_0c76();
    (*_DAT_0000_2010)();
    FUN_0000_0aa6();
    (*_DAT_0000_3002)();
    puVar27 = (undefined1 *)0xe000;
    for (iVar4 = 0xe0; iVar4 != 0; iVar4 = iVar4 + -1) {
      puVar1 = puVar27;
      puVar27 = puVar27 + 1;
      *puVar1 = 0xfe;
    }
    FUN_0000_0af1();
    *(undefined1 *)0xff1a = 0x28;
    FUN_0000_08b3();
    *(undefined1 *)&DAT_0000_ff1d = 0;
    *(undefined1 *)0xff1e = 0;
    *(undefined1 *)0xe7 = 1;
    pcVar2 = (code *)swi(0x60);
    (*pcVar2)();
    return;
  }
  *(undefined1 *)0xe7 = 4;
  FUN_0000_08b3();
  if ((*(byte *)0x45 & 0x80) == 0) {
    *(undefined1 *)0x7c5c = 0xff;
    FUN_0000_03ce();
    *(undefined1 *)0x7c5c = 0;
    *(byte *)0x45 = *(byte *)0x45 | 0x80;
  }
  *(undefined1 *)0xff24 = 4;
  *(undefined1 *)0xc4 = 0x86;
  (*pcRam0000010c)();
  (*pcRam0000010c)();
  do {
  } while (*(char *)0xff26 == '\0');
  (*pcRam0000010c)();
  *(undefined2 *)0x80 = 0x84;
  *(undefined1 *)0x83 = 0xd;
  (*_DAT_0000_2040)();
  uRam00007c43 = 0xff;
  (*_DAT_0000_3026)();
  *(undefined2 *)0x1ffe = 0;
  uVar29 = *(undefined2 *)0x1ffe;
  *(undefined2 *)0x1ffe = 0x54;
  FUN_0000_0df3();
  *(undefined1 *)0xe7 = 0;
  if (*(char *)0x49 != '\0') {
    *(undefined1 *)0xe8 = 0;
  }
  pcVar2 = _DAT_0000_2002;
  puVar5 = (undefined1 *)0x1ffe;
  *(undefined2 *)0x1ffe = 0x6a;
  (*pcVar2)();
  pcVar25 = (char *)(*(int *)0xc000 + 1);
  do {
    pcVar24 = pcVar25;
    pcVar25 = pcVar24 + 1;
  } while (*pcVar24 != -1);
  *(char *)0x7c45 = pcVar24[1];
  *(char *)0x7c46 = pcVar24[2];
  *(undefined1 *)0x7c44 = 0;
  if (*(char *)0xe8 == '\0') {
    if (((*(byte *)0x7c45 & 1) != 0) && (*(char *)0x7c43 == '\0')) {
      *(undefined1 *)0x7c44 = 0xff;
    }
    *(undefined2 *)(puVar5 + -2) = 0x9e;
    FUN_0000_0ab3();
    puVar6 = puVar5 + -2;
    *(undefined2 *)(puVar5 + -2) = 0xa1;
    FUN_0000_0aa6();
    pcVar2 = _DAT_0000_3002;
    puVar7 = puVar6 + -2;
    *(undefined2 *)(puVar6 + -2) = 0xa6;
    (*pcVar2)();
    if (*(char *)0x49 == '\0') {
      *(undefined2 *)(puVar7 + -2) = uVar29;
      pcVar2 = (code *)swi(0x60);
      (*pcVar2)();
    }
  }
  *(undefined2 *)0x1ffe = 0;
  uVar29 = *(undefined2 *)0x1ffe;
  *(undefined2 *)0x1ffe = 0xc5;
  FUN_0000_0af1();
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  *(undefined1 *)0xe4 = 0;
  *(undefined1 *)0x9f = 0;
  pcVar2 = _DAT_0000_2004;
  puVar8 = (undefined1 *)0x1ffe;
  *(undefined2 *)0x1ffe = 0xdf;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2004;
  puVar9 = puVar8 + -2;
  *(undefined2 *)(puVar8 + -2) = 0xeb;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2004;
  puVar10 = puVar9 + -2;
  *(undefined2 *)(puVar9 + -2) = 0xf7;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2012;
  puVar11 = puVar10 + -2;
  *(undefined2 *)(puVar10 + -2) = 0xfc;
  (*pcVar2)();
  *(undefined2 *)(puVar11 + -2) = 0xff;
  FUN_0000_0c76();
  pcVar2 = _DAT_0000_2006;
  puVar12 = puVar11 + -2;
  *(undefined2 *)(puVar11 + -2) = 0x104;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2008;
  puVar13 = puVar12 + -2;
  *(undefined2 *)(puVar12 + -2) = 0x109;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2014;
  puVar14 = puVar13 + -2;
  *(undefined2 *)(puVar13 + -2) = 0x10e;
  (*pcVar2)();
  pcVar2 = _DAT_0000_2016;
  puVar15 = puVar14 + -2;
  *(undefined2 *)(puVar14 + -2) = 0x113;
  (*pcVar2)();
  if (*(char *)0x9d != '\0') {
    pcVar2 = _DAT_0000_2004;
    puVar16 = puVar15 + -2;
    *(undefined2 *)(puVar15 + -2) = 0x126;
    (*pcVar2)();
    pcVar2 = _DAT_0000_2018;
    puVar15 = puVar16 + -2;
    *(undefined2 *)(puVar16 + -2) = 299;
    (*pcVar2)();
  }
  if (*(char *)0x93 != '\0') {
    pcVar2 = _DAT_0000_2004;
    puVar17 = puVar15 + -2;
    *(undefined2 *)(puVar15 + -2) = 0x13e;
    (*pcVar2)();
    pcVar2 = _DAT_0000_201a;
    puVar15 = puVar17 + -2;
    *(undefined2 *)(puVar17 + -2) = 0x143;
    (*pcVar2)();
  }
  pcVar25 = (char *)*(undefined2 *)0xc000;
  do {
    pcVar24 = pcVar25;
    pcVar25 = pcVar24 + 1;
  } while (*pcVar25 != -1);
  *(char *)0x7c46 = pcVar24[3];
  pcVar2 = _DAT_0000_2010;
  puVar18 = puVar15 + -2;
  *(undefined2 *)(puVar15 + -2) = 0x15b;
  (*pcVar2)();
  *(int *)0xff2a = (uint)*(byte *)0x80 * 8 + -0x3fe9;
  *(undefined2 *)(puVar18 + -2) = 0x16f;
  FUN_0000_0c2f();
  if (*(char *)0xe8 != '\0') {
    *(undefined1 *)0xe8 = 0;
    *(undefined2 *)(puVar18 + -2) = 0x17e;
    FUN_0000_0ab3();
    *(undefined2 *)(puVar18 + -2) = 0x61fc;
    *(undefined2 *)(puVar18 + -4) = 0x6eaf;
    *(undefined2 *)(puVar18 + -6) = 0;
    pcVar2 = pcRam0000010c;
    puVar19 = puVar18 + -6;
    *(undefined2 *)(puVar18 + -6) = 0x195;
    (*pcVar2)();
    pcVar2 = _DAT_0000_2040;
    *(undefined2 *)(puVar19 + -2) = 0x19a;
    (*pcVar2)();
    pcVar2 = (code *)swi(0x60);
    (*pcVar2)();
    *(undefined1 *)0x7c42 = 0xff;
                    /* WARNING: Could not recover jumptable at 0x000001a4. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*_DAT_0000_a004)();
    return;
  }
  *(undefined2 *)(puVar18 + -2) = 0;
  uVar28 = *(undefined2 *)(puVar18 + -2);
  puVar27 = (undefined1 *)0xe000;
  for (iVar4 = 0xe0; iVar4 != 0; iVar4 = iVar4 + -1) {
    puVar1 = puVar27;
    puVar27 = puVar27 + 1;
    *puVar1 = 0xfe;
  }
  piVar20 = (int *)(puVar18 + -2);
  *(undefined2 *)(puVar18 + -2) = 0x1b8;
  FUN_0000_08b0();
  if (*(char *)0x7c44 != '\0') {
    *(undefined2 *)&DAT_0000_7c47 = 0x6781;
    if ((*(byte *)0xc2 & 1) == 0) {
      *(undefined2 *)&DAT_0000_7c47 = 0x67f4;
    }
    iVar4 = 4;
    piVar26 = piVar20;
    do {
      *(int *)((int)piVar26 + -2) = iVar4;
      pcVar2 = _DAT_0000_7c47;
      puVar21 = (undefined1 *)((int)piVar26 + -4);
      *(undefined2 *)((int)piVar26 + -4) = 0x1db;
      (*pcVar2)();
      piVar20 = (int *)(puVar21 + -2);
      *(undefined2 *)(puVar21 + -2) = 0x1de;
      FUN_0000_08b0();
      piVar26 = piVar20 + 1;
      iVar4 = *piVar20 + -1;
    } while (iVar4 != 0);
    pcVar2 = _DAT_0000_7c47;
    *piVar20 = 0x1e6;
    (*pcVar2)();
  }
  *(undefined1 *)0x7c4b = 0;
  if (*(char *)0x49 != '\0') {
    puVar22 = (undefined2 *)((int)piVar20 + -2);
    *(undefined2 *)((int)piVar20 + -2) = uVar29;
    pcVar2 = (code *)swi(0x60);
    (*pcVar2)();
    uVar29 = *puVar22;
    piVar20 = puVar22 + 1;
  }
  puVar23 = (undefined1 *)((int)piVar20 + -2);
  *(undefined2 *)((int)piVar20 + -2) = 0x203;
  FUN_0000_08b0();
  *(undefined2 *)(puVar23 + -2) = 0x206;
  FUN_0000_08f7();
  *(undefined2 *)(puVar23 + -2) = 0x209;
  FUN_0000_0cb9();
  *(undefined2 *)(puVar23 + -2) = 0x20c;
  FUN_0000_0243();
  if (*(char *)0x7c4b == '\0') {
    *(undefined2 *)(puVar23 + -2) = 0x216;
    FUN_0000_02f1();
  }
  *(undefined1 *)0x7c4b = 0;
  *(undefined2 *)(puVar23 + -2) = 0x61fc;
  pcVar2 = (code *)swi(0x61);
  bVar3 = (*pcVar2)();
  if (bVar3 == 1) {
    FUN_0000_0e2d();
    return;
  }
  if ((bVar3 & 0xc) == 4) {
    FUN_0000_0785();
    return;
  }
  if ((bVar3 & 0xc) == 8) {
    FUN_0000_07f8();
    return;
  }
  *(byte *)0xe7 = *(byte *)0xe7 | 1;
  *(undefined1 *)0x7c4b = 0xff;
  return;
}



// Address: 0000:0ffc

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_0ffc(void)

{
  undefined2 uVar1;
  uint in_AX;
  undefined2 *puVar2;
  int iVar3;
  undefined2 unaff_DS;
  int in_stack_00000000;
  
  puVar2 = (undefined2 *)((in_AX & 0xff) * 5 + *(int *)0xc00b);
  uVar1 = *puVar2;
  *(byte *)0x82 = *(char *)(puVar2 + 1) - 10U & 0x3f;
  *(char *)0xc3 = -(*(byte *)((int)puVar2 + 3) & 1);
  *(undefined1 *)0xc4 = *(undefined1 *)(puVar2 + 2);
  (*pcRam0000010c)(uVar1);
  iVar3 = in_stack_00000000 + -0x10;
  if (iVar3 < 0) {
    iVar3 = iVar3 + *(int *)0xc002;
  }
  *(int *)0x80 = iVar3;
  *(undefined1 *)0x6 = 0xff;
  (*_DAT_0000_2040)();
                    /* WARNING: Could not recover jumptable at 0x00001041. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*pcRam0000010c)();
  return;
}



// Address: 0000:1046

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1046(void)

{
  undefined2 unaff_DS;
  undefined1 in_CF;
  
  (*pcRam00000110)();
  (*pcRam00000112)();
  (*pcRam0000011e)();
  if ((bool)in_CF) {
    FUN_0000_1596();
  }
  if (*(char *)0x7c42 == '\0') {
    return;
  }
  (*_DAT_0000_a002)();
  return;
}



// Address: 0000:1174

/* WARNING: Instruction at (ram,0x00001183) overlaps instruction at (ram,0x00001181)
    */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1174(void)

{
  int *piVar1;
  char *pcVar2;
  uint in_CX;
  int iVar3;
  char in_DL;
  int in_BX;
  int unaff_SI;
  int unaff_DI;
  undefined2 unaff_DS;
  bool in_CF;
  char in_SF;
  char in_OF;
  
  do {
  } while (in_OF != in_SF);
  piVar1 = (int *)(in_BX + unaff_SI + 0x523e);
  iVar3 = *piVar1;
  *piVar1 = *piVar1 + 1;
  if (SCARRY2(iVar3,1) == *piVar1 < 0) {
    if (in_CF) {
      if (*(byte *)0xff4f < 5) {
        return;
      }
      *(char *)0xff4f = *(char *)0xff4f + -1;
      iVar3 = 10;
      do {
        FUN_0000_1046();
        (*_DAT_0000_2024)();
        iVar3 = iVar3 + -1;
      } while (iVar3 != 0);
      return;
    }
  }
  else {
    pcVar2 = (char *)(in_BX + unaff_DI + -0x19);
    *pcVar2 = *pcVar2 + in_DL;
  }
  FUN_0000_126d();
  FUN_0000_1192();
  if (1 < in_CX) {
    FUN_0000_11c0();
  }
  return;
}



// Address: 0000:1192

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1192(void)

{
  int iVar1;
  undefined2 unaff_DS;
  
  if (*(byte *)0xff4f < 5) {
    return;
  }
  *(char *)0xff4f = *(char *)0xff4f + -1;
  iVar1 = 10;
  do {
    FUN_0000_1046();
    (*_DAT_0000_2024)();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:11c0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_11c0(void)

{
  undefined2 unaff_DS;
  
  (*_DAT_0000_2022)();
  FUN_0000_11e3();
  (*_DAT_0000_2000)();
  *(undefined1 *)0x7c52 = 0;
  return;
}



// Address: 0000:11e3

void __cdecl16near FUN_0000_11e3(void)

{
  undefined2 unaff_DS;
  
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  do {
    FUN_0000_1046();
  } while (*(char *)&DAT_0000_ff1d == '\0' && *(char *)0xff1e == '\0');
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  *(undefined1 *)0xff75 = 0x1d;
  return;
}



// Address: 0000:1228

void __cdecl16near FUN_0000_1228(void)

{
  byte *pbVar1;
  byte bVar2;
  byte in_AH;
  int iVar3;
  byte *unaff_SI;
  undefined2 unaff_DS;
  
  iVar3 = 0;
  while( true ) {
    pbVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    bVar2 = *pbVar1;
    if (((((bVar2 == 0) || (bVar2 == 0xff)) || (bVar2 == 0x20)) ||
        ((bVar2 == 0x2f || (bVar2 == 0xd)))) || (bVar2 == 0xc)) break;
    in_AH = bVar2;
    if (0x1f < bVar2) {
      iVar3 = iVar3 + 1;
    }
  }
  if (iVar3 != 1) {
    return;
  }
  if ((in_AH != 0x2e) && (in_AH != 0x2c)) {
    return;
  }
  return;
}



// Address: 0000:126d

void __cdecl16near FUN_0000_126d(void)

{
  char *pcVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  char *pcVar6;
  undefined2 unaff_DS;
  
  iVar3 = 0;
  iVar5 = 0;
  pcVar6 = (char *)*(undefined2 *)0xff4c;
  do {
    while( true ) {
      pcVar1 = pcVar6 + 1;
      cVar2 = *pcVar6;
      if (cVar2 == '\0') goto LAB_0000_12c4;
      if (cVar2 == -1) break;
      if (cVar2 == '\f') goto LAB_0000_12c4;
      pcVar6 = pcVar1;
      if (cVar2 == '/') {
        iVar5 = 0;
        iVar3 = iVar3 + 1;
      }
      else if (cVar2 == '\r') {
        iVar5 = 0;
        iVar3 = iVar3 + 1;
      }
      else {
        iVar5 = iVar5 + (uint)*(byte *)((byte)(cVar2 - 0x20) + 0x7be2);
        if ((cVar2 == ' ') && (iVar4 = iVar3, FUN_0000_1228(), 0xcf < (uint)(iVar5 + iVar4))) {
          iVar5 = 0;
          iVar3 = iVar3 + 1;
        }
      }
    }
    pcVar6 = pcVar6 + 2;
  } while (*pcVar1 != -1);
LAB_0000_12c4:
  if (iVar5 != 0) {
    return;
  }
  return;
}



// Address: 0000:1348

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1348(void)

{
  code *pcVar1;
  byte bVar2;
  int iVar3;
  byte bVar4;
  undefined2 unaff_DS;
  undefined2 in_stack_00000000;
  
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  FUN_0000_146d();
  FUN_0000_1046();
  *(undefined1 *)0xff1a = 0;
  if (*(char *)0xff1e != '\0') {
    return;
  }
  if (*(char *)&DAT_0000_ff1d != '\0') {
    *(undefined1 *)0xff75 = 0x1f;
    return;
  }
  pcVar1 = (code *)swi(0x61);
  bVar2 = (*pcVar1)();
  bVar4 = (byte)in_stack_00000000;
  if ((bVar2 & 3) == 1) {
    if (bVar4 != 0) {
      FUN_0000_147f();
      return;
    }
    if (*(char *)0xff56 == '\0') {
      return;
    }
    *(char *)0xff56 = *(char *)0xff56 + -1;
    (*_DAT_0000_301a)(in_stack_00000000);
    iVar3 = 10;
    do {
      (*_DAT_0000_301e)();
      do {
        FUN_0000_1046();
      } while (*(byte *)0xff1a < 4);
      *(undefined1 *)0xff1a = 0;
      iVar3 = iVar3 + -1;
    } while (iVar3 != 0);
    return;
  }
  if ((bVar2 & 3) != 2) {
    return;
  }
  if (bVar4 < (byte)(*(char *)0xff52 - 1U)) {
    FUN_0000_14ab();
    return;
  }
  if ((byte)(*(char *)0xff53 - 1U) < (byte)(bVar4 + *(char *)0xff56 + 1)) {
    return;
  }
  *(char *)0xff56 = *(char *)0xff56 + '\x01';
  (*_DAT_0000_301a)(in_stack_00000000);
  iVar3 = 10;
  do {
    (*_DAT_0000_3020)();
    do {
      FUN_0000_1046();
    } while (*(byte *)0xff1a < 4);
    *(undefined1 *)0xff1a = 0;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:146d

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_146d(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000147a. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*_DAT_0000_3018)();
  return;
}



// Address: 0000:147f

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_147f(void)

{
  int iVar1;
  int iVar2;
  uint in_BX;
  undefined2 unaff_DS;
  
  iVar1 = (in_BX & 0xff) * 10 + *(int *)0xff54 + 0x100;
  iVar2 = 10;
  do {
    *(undefined1 *)0xff1a = 0;
    iVar1 = iVar1 + -1;
    (*_DAT_0000_3018)(iVar1);
    do {
      FUN_0000_1046();
    } while (*(byte *)0xff1a < 4);
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:14ab

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_14ab(void)

{
  int iVar1;
  int iVar2;
  uint in_BX;
  undefined2 unaff_DS;
  
  iVar1 = (in_BX & 0xff) * 10 + *(int *)0xff54 + 0x100;
  iVar2 = 10;
  do {
    *(undefined1 *)0xff1a = 0;
    iVar1 = iVar1 + 1;
    (*_DAT_0000_3018)(iVar1);
    do {
      FUN_0000_1046();
    } while (*(byte *)0xff1a < 4);
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:14d7

void __cdecl16near FUN_0000_14d7(void)

{
  undefined1 uVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  char cVar4;
  undefined2 unaff_DS;
  bool bVar5;
  
  uVar1 = *(undefined1 *)0xff52;
  uVar3 = *(undefined1 *)0xff53;
  uVar2 = *(undefined1 *)0xff56;
  *(undefined1 *)0xff52 = 2;
  *(undefined1 *)0xff53 = 2;
  FUN_0000_151e();
  *(undefined1 *)0xff56 = 0;
  bVar5 = false;
  cVar4 = '\0';
  FUN_0000_1348();
  if (bVar5) {
    cVar4 = '\x01';
  }
  *(undefined1 *)0xff56 = uVar2;
  *(undefined1 *)0xff52 = uVar1;
  *(undefined1 *)0xff53 = uVar3;
  if (cVar4 == '\0') {
    return;
  }
  return;
}



// Address: 0000:151e

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_151e(void)

{
  int in_CX;
  char cVar1;
  
  cVar1 = '\0';
  do {
    (*_DAT_0000_2038)(cVar1);
    cVar1 = cVar1 + '\x01';
    in_CX = in_CX + -1;
  } while (in_CX != 0);
  return;
}



// Address: 0000:1596

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_1596(void)

{
  char *pcVar1;
  undefined1 *puVar2;
  char *pcVar3;
  code *pcVar4;
  int iVar5;
  char *pcVar6;
  undefined1 *puVar7;
  char *pcVar8;
  undefined2 unaff_DS;
  bool bVar9;
  undefined2 uStack0008;
  
  uStack0008 = unaff_DS;
  do {
    pcVar4 = (code *)swi(0x60);
    (*pcVar4)();
    (*pcRam0000010c)();
    *(undefined1 *)0xff57 = 0;
    FUN_0000_1699();
    if (DAT_0000_7c64 == '\0') {
      pcVar6 = (char *)0xff6c;
      pcVar8 = (char *)0x7c67;
      iVar5 = 8;
      do {
        pcVar1 = pcVar6;
        pcVar6 = pcVar6 + 1;
        if (*pcVar1 == '\0') break;
        pcVar3 = pcVar8;
        pcVar8 = pcVar8 + 1;
        *pcVar3 = *pcVar1;
        iVar5 = iVar5 + -1;
      } while (iVar5 != 0);
      *pcVar8 = '.';
      pcVar8[1] = 'U';
      pcVar8[2] = 'S';
      pcVar8[3] = 'R';
      pcVar8[4] = '\0';
      DAT_0000_ff78 = 0xff;
    }
    else {
      puVar7 = (undefined1 *)0xff6c;
      for (iVar5 = 8; iVar5 != 0; iVar5 = iVar5 + -1) {
        puVar2 = puVar7;
        puVar7 = puVar7 + 1;
        *puVar2 = 0;
      }
    }
    bVar9 = false;
    (*pcRam0000010c)();
    DAT_0000_ff78 = 0;
    if (!bVar9) {
      (*pcRam0000010c)();
      (*_DAT_0000_2042)();
      pcVar4 = (code *)swi(0x60);
      (*pcVar4)();
      pcVar4 = (code *)swi(0x60);
      (*pcVar4)();
                    /* WARNING: Could not recover jumptable at 0x0000162f. Too many branches */
                    /* WARNING: Treating indirect jump as call */
      (*(code *)*(undefined2 *)0x7686)();
      return;
    }
    (*_DAT_0000_2000)();
    uStack0008 = 0;
    (*_DAT_0000_202a)();
    DAT_0000_ff1d = '\0';
    do {
      (*pcRam00000110)();
    } while (DAT_0000_ff1d == '\0');
    DAT_0000_ff1d = 0;
  } while( true );
}



// Address: 0000:1616

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_0000_1616(void)

{
  code *pcVar1;
  undefined2 unaff_DS;
  
  (*pcRam0000010c)();
  (*_DAT_0000_2042)();
  pcVar1 = (code *)swi(0x60);
  (*pcVar1)();
  pcVar1 = (code *)swi(0x60);
  (*pcVar1)();
                    /* WARNING: Could not recover jumptable at 0x0000162f. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)0x7686)();
  return;
}



// Address: 0000:1699

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1699(void)

{
  char *pcVar1;
  char cVar2;
  undefined2 *puVar3;
  undefined1 *puVar4;
  undefined1 *puVar5;
  undefined2 *puVar6;
  byte bVar7;
  int iVar8;
  undefined2 *puVar9;
  char *pcVar10;
  undefined2 *puVar11;
  undefined1 *puVar12;
  char *pcVar13;
  undefined1 *puVar14;
  undefined2 unaff_CS;
  
  (*pcRam0000011c)();
  pcVar1 = (char *)0xe000;
  *pcVar1 = *pcVar1 + '\x01';
  if (*pcVar1 == '\0') {
    *(char *)0xe000 = *(char *)0xe000 + -1;
  }
  puVar9 = (undefined2 *)0xe1fd;
  puVar11 = (undefined2 *)0xe1ff;
  for (iVar8 = 0xff; iVar8 != 0; iVar8 = iVar8 + -1) {
    puVar6 = puVar11;
    puVar11 = puVar11 + -1;
    puVar3 = puVar9;
    puVar9 = puVar9 + -1;
    *puVar6 = *puVar3;
  }
  *(undefined2 *)0xe001 = 0x77ba;
  (*_DAT_0000_2000)();
  (*_DAT_0000_2000)();
  puVar12 = (undefined1 *)0x7c67;
  for (iVar8 = 8; iVar8 != 0; iVar8 = iVar8 + -1) {
    puVar4 = puVar12;
    puVar12 = puVar12 + 1;
    *puVar4 = 0x60;
  }
  *puVar12 = 0xff;
  *(undefined1 *)&DAT_0000_7c5e = 0;
  pcVar10 = (char *)0xff6c;
  pcVar13 = (char *)0x7c67;
  iVar8 = 8;
  do {
    pcVar1 = pcVar10;
    pcVar10 = pcVar10 + 1;
    cVar2 = *pcVar1;
    if (cVar2 == '\0') break;
    *(char *)&DAT_0000_7c5e = *(char *)&DAT_0000_7c5e + '\x01';
    pcVar1 = pcVar13;
    pcVar13 = pcVar13 + 1;
    *pcVar1 = cVar2;
    iVar8 = iVar8 + -1;
  } while (iVar8 != 0);
  *(undefined1 *)&DAT_0000_7c5f = *(undefined1 *)&DAT_0000_7c5e;
  pcVar10 = (char *)0x7c67;
  iVar8 = 8;
  do {
    pcVar1 = pcVar10;
    pcVar10 = pcVar10 + 1;
    if (*pcVar1 != '`') goto LAB_0000_1729;
    iVar8 = iVar8 + -1;
  } while (iVar8 != 0);
  puVar12 = (undefined1 *)0x77ba;
  puVar14 = (undefined1 *)0x7c67;
  for (iVar8 = 8; iVar8 != 0; iVar8 = iVar8 + -1) {
    puVar5 = puVar14;
    puVar14 = puVar14 + 1;
    puVar4 = puVar12;
    puVar12 = puVar12 + 1;
    *puVar5 = *puVar4;
  }
LAB_0000_1729:
  (*_DAT_0000_202a)();
  *(undefined2 *)0x7c60 = 0x60;
  *(undefined1 *)0x7c62 = 0x56;
  *(undefined2 *)0xff54 = 0x343b;
  *(undefined2 *)0xff6a = 10;
  bVar7 = *(byte *)0xe000;
  if (bVar7 == 0) {
                    /* WARNING: Could not recover jumptable at 0x000017a7. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*(code *)(ulong)_DAT_0000_ff00)();
    return;
  }
  if (4 < bVar7) {
    bVar7 = 5;
  }
  if (bVar7 != 0) {
    FUN_0000_180b();
  }
  *(undefined1 *)0xff53 = *(undefined1 *)0xe000;
  *(undefined1 *)0xff52 = 5;
  FUN_0000_183c();
  puVar12 = (undefined1 *)0xff6c;
  for (iVar8 = 8; iVar8 != 0; iVar8 = iVar8 + -1) {
    puVar4 = puVar12;
    puVar12 = puVar12 + 1;
    *puVar4 = 0;
  }
  if (*(char *)&DAT_0000_7c5f == '\0') {
    return;
  }
  pcVar10 = (char *)0x7c67;
  pcVar13 = (char *)0xff6c;
  while( true ) {
    pcVar1 = pcVar10;
    pcVar10 = pcVar10 + 1;
    cVar2 = *pcVar1;
    if (cVar2 == -1) {
      return;
    }
    if (cVar2 == '`') break;
    pcVar1 = pcVar13;
    pcVar13 = pcVar13 + 1;
    *pcVar1 = cVar2;
  }
  return;
}



// Address: 0000:17c7

void __cdecl16near FUN_0000_17c7(void)

{
  char *pcVar1;
  int iVar2;
  char *pcVar3;
  undefined1 in_ZF;
  
  DAT_0000_7c64 = 0;
  pcVar3 = (char *)0x7c67;
  iVar2 = 8;
  do {
    if (iVar2 == 0) break;
    iVar2 = iVar2 + -1;
    pcVar1 = pcVar3;
    pcVar3 = pcVar3 + 1;
    in_ZF = *pcVar1 == '-';
  } while (!(bool)in_ZF);
  if (!(bool)in_ZF) {
    return;
  }
  DAT_0000_7c64 = 0xff;
  DAT_0000_7c5e = 0;
  return;
}



// Address: 0000:17e9

void __cdecl16near FUN_0000_17e9(void)

{
  undefined1 *puVar1;
  int iVar2;
  undefined1 *puVar3;
  
  if (DAT_0000_7c64 == '\0') {
    return;
  }
  DAT_0000_7c64 = 0;
  puVar3 = (undefined1 *)0x7c67;
  for (iVar2 = 8; iVar2 != 0; iVar2 = iVar2 + -1) {
    puVar1 = puVar3;
    puVar3 = puVar3 + 1;
    *puVar1 = 0x60;
  }
  DAT_0000_7c5f = 0;
  return;
}



// Address: 0000:180b

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_180b(void)

{
  uint in_AX;
  uint uVar1;
  int in_CX;
  undefined2 unaff_SI;
  undefined2 uVar2;
  
  uVar1 = in_AX & 0xff;
  do {
    (*_DAT_0000_301a)(uVar1,unaff_SI);
    uVar2 = 0x1832;
    (*_DAT_0000_301c)();
    uVar1 = CONCAT11((char)((uint)uVar2 >> 8) + '\x01',(char)uVar2 + '\x01');
    in_CX = in_CX + -1;
  } while (in_CX != 0);
  return;
}



// Address: 0000:183c

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_183c(void)

{
  undefined1 *puVar1;
  char *pcVar2;
  undefined1 *puVar3;
  code *pcVar4;
  byte bVar5;
  uint uVar6;
  int iVar7;
  int unaff_SI;
  undefined1 *puVar8;
  char *pcVar9;
  undefined1 *puVar10;
  char *pcVar11;
  undefined2 unaff_DS;
  char cVar12;
  
  FUN_0000_17c7();
  *(undefined1 *)0xff74 = 0xff;
  *(undefined1 *)0xff29 = 0;
  *(undefined1 *)&DAT_0000_ff1d = 0;
  *(undefined1 *)0xff1e = 0;
  *(undefined1 *)0xff56 = 0;
  *(undefined1 *)0x7c63 = 0;
  if (*(char *)0xff53 != '\0') {
    (*_DAT_0000_6014)();
  }
  FUN_0000_1b1e();
  FUN_0000_1ab1();
  do {
    while (*(undefined1 *)0xff1a = 0, (_DAT_0000_ff18 & 1) != 0) {
      pcVar9 = (char *)0x7c67;
      iVar7 = 8;
      do {
        pcVar2 = pcVar9;
        pcVar9 = pcVar9 + 1;
        if (*pcVar2 != '`') {
          *(undefined1 *)0xff75 = 0x1f;
          *(undefined1 *)0xff74 = 0;
          *(undefined1 *)0xff1e = 0;
          return;
        }
        iVar7 = iVar7 + -1;
      } while (iVar7 != 0);
      puVar8 = (undefined1 *)0x77ba;
      puVar10 = (undefined1 *)0x7c67;
      for (iVar7 = 8; iVar7 != 0; iVar7 = iVar7 + -1) {
        puVar3 = puVar10;
        puVar10 = puVar10 + 1;
        puVar1 = puVar8;
        puVar8 = puVar8 + 1;
        *puVar3 = *puVar1;
      }
      FUN_0000_17c7();
      FUN_0000_1b1e();
      *(undefined1 *)0xff75 = 1;
      do {
      } while ((_DAT_0000_ff18 & 1) != 0);
    }
    if (*(char *)&DAT_0000_ff1d == '\0') {
      if (*(char *)0xff29 != '\0') {
        *(undefined1 *)0xff75 = 1;
        cVar12 = *(char *)0xff29;
        *(undefined1 *)0xff29 = 0;
        if (cVar12 == '\r') {
          return;
        }
        if (cVar12 != '\b') {
          FUN_0000_17e9(cVar12,0x786f);
          bVar5 = *(byte *)&DAT_0000_7c5e;
          if (*(char *)(bVar5 + 0x7c67) == '`') {
            *(char *)&DAT_0000_7c5f = *(char *)&DAT_0000_7c5f + '\x01';
          }
          *(char *)(bVar5 + 0x7c67) = cVar12;
          FUN_0000_1b1e();
          *(undefined1 *)0xff75 = 1;
          FUN_0000_1ab1();
          return;
        }
        FUN_0000_1b48();
        return;
      }
      pcVar4 = (code *)swi(0x61);
      bVar5 = (*pcVar4)();
      if ((bVar5 & 8) != 0) {
        *(undefined1 *)0xff75 = 1;
        FUN_0000_1ab1();
        do {
          pcVar4 = (code *)swi(0x61);
          uVar6 = (*pcVar4)();
        } while ((uVar6 & 8) != 0);
        *(undefined1 *)0xff29 = 0;
        return;
      }
      if ((bVar5 & 4) != 0) {
        *(undefined1 *)0xff75 = 1;
        FUN_0000_1ab1();
        do {
          pcVar4 = (code *)swi(0x61);
          uVar6 = (*pcVar4)();
        } while ((uVar6 & 4) != 0);
        *(undefined1 *)0xff29 = 0;
        return;
      }
      if (*(char *)0xff53 == '\0') {
        return;
      }
      if ((bVar5 & 3) == 1) {
        if (*(char *)0x7c63 != '\0') {
          (*_DAT_0000_6018)();
          *(char *)0x7c63 = *(char *)0x7c63 + -1;
          return;
        }
        if (*(char *)0xff56 != '\0') {
          *(char *)0xff56 = *(char *)0xff56 + -1;
          (*_DAT_0000_301a)(unaff_SI);
          iVar7 = 10;
          do {
            (*_DAT_0000_301e)();
            do {
            } while (*(byte *)0xff1a < 4);
            *(undefined1 *)0xff1a = 0;
            iVar7 = iVar7 + -1;
          } while (iVar7 != 0);
          return;
        }
        return;
      }
      if ((bVar5 & 3) != 2) {
        return;
      }
      if ((byte)(*(char *)0x7c63 + *(char *)0xff56 + 1U) <= (byte)(*(char *)0xff53 - 1U)) {
        if ((byte)(*(char *)0xff52 - 1U) <= *(byte *)0x7c63) {
          *(char *)0xff56 = *(char *)0xff56 + '\x01';
          (*_DAT_0000_301a)(unaff_SI);
          iVar7 = 10;
          do {
            (*_DAT_0000_3020)();
            do {
            } while (*(byte *)0xff1a < 4);
            *(undefined1 *)0xff1a = 0;
            iVar7 = iVar7 + -1;
          } while (iVar7 != 0);
          return;
        }
        (*_DAT_0000_601a)();
        *(char *)0x7c63 = *(char *)0x7c63 + '\x01';
        return;
      }
      return;
    }
    *(undefined1 *)0xff75 = 1;
    pcVar9 = (char *)*(undefined2 *)((uint)(byte)(*(char *)0xff56 + *(char *)0x7c63) * 2 + unaff_SI)
    ;
    puVar8 = (undefined1 *)0x7c67;
    for (iVar7 = 8; iVar7 != 0; iVar7 = iVar7 + -1) {
      puVar1 = puVar8;
      puVar8 = puVar8 + 1;
      *puVar1 = 0x60;
    }
    *puVar8 = 0xff;
    *(undefined1 *)&DAT_0000_7c5e = 0;
    pcVar11 = (char *)0x7c67;
    iVar7 = 8;
    do {
      pcVar2 = pcVar9;
      pcVar9 = pcVar9 + 1;
      cVar12 = *pcVar2;
      if (cVar12 == '\0') break;
      *(char *)&DAT_0000_7c5e = *(char *)&DAT_0000_7c5e + '\x01';
      pcVar2 = pcVar11;
      pcVar11 = pcVar11 + 1;
      *pcVar2 = cVar12;
      iVar7 = iVar7 + -1;
    } while (iVar7 != 0);
    *(undefined1 *)&DAT_0000_7c5f = *(undefined1 *)&DAT_0000_7c5e;
    FUN_0000_17c7();
    *(undefined1 *)&DAT_0000_ff1d = 0;
    (*_DAT_0000_2000)();
    FUN_0000_1b1e();
    FUN_0000_1ab1();
  } while( true );
}



// Address: 0000:1ab1

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1ab1(void)

{
  char unaff_SI;
  undefined2 unaff_DS;
  
  (*_DAT_0000_2000)();
  *(char *)&DAT_0000_7c5e = *(char *)&DAT_0000_7c5e + unaff_SI;
  if ((*(byte *)&DAT_0000_7c5e & 0x80) != 0) {
    *(undefined1 *)&DAT_0000_7c5e = 0;
  }
  if (7 < *(byte *)&DAT_0000_7c5e) {
    *(char *)&DAT_0000_7c5e = *(char *)&DAT_0000_7c5e + -1;
  }
  if (*(byte *)&DAT_0000_7c5f <= *(byte *)&DAT_0000_7c5e) {
    *(byte *)&DAT_0000_7c5e = *(byte *)&DAT_0000_7c5f;
  }
  (*_DAT_0000_2022)();
  return;
}



// Address: 0000:1b1e

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1b1e(void)

{
  (*_DAT_0000_2000)();
  (*_DAT_0000_202a)();
  return;
}



// Address: 0000:1b48

void __cdecl16near FUN_0000_1b48(void)

{
  undefined1 *puVar1;
  undefined1 *puVar2;
  uint uVar3;
  byte bVar4;
  undefined1 *puVar5;
  undefined1 *puVar6;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  FUN_0000_17e9();
  bVar4 = *(byte *)&DAT_0000_7c5e;
  if (bVar4 == 0) {
    bVar4 = 1;
  }
  puVar5 = (undefined1 *)(bVar4 + 0x7c67);
  puVar6 = (undefined1 *)(bVar4 + 0x7c66);
  for (uVar3 = (uint)(byte)(8 - bVar4); uVar3 != 0; uVar3 = uVar3 - 1) {
    puVar2 = puVar6;
    puVar6 = puVar6 + 1;
    puVar1 = puVar5;
    puVar5 = puVar5 + 1;
    *puVar2 = *puVar1;
  }
  if (*(char *)&DAT_0000_7c5f != '\0') {
    *(char *)&DAT_0000_7c5f = *(char *)&DAT_0000_7c5f + -1;
  }
  *(undefined1 *)0x7c6e = 0x60;
  FUN_0000_1ab1();
  FUN_0000_1b1e();
  return;
}



