/* Decompiled from chunk_07.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:00d4

void FUN_0000_00d4(void)

{
  undefined2 unaff_DS;
  
                    /* WARNING: Could not recover jumptable at 0x000000e0. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)*(byte *)0x499 * 2 + 0xde))();
  return;
}



// Address: 0000:0352

void FUN_0000_0352(void)

{
  undefined2 unaff_DS;
  
                    /* WARNING: Could not recover jumptable at 0x0000035e. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)*(byte *)0x499 * 2 + 0x35c))();
  return;
}



// Address: 0000:0458

void __cdecl16near FUN_0000_0458(void)

{
  byte *pbVar1;
  byte bVar2;
  byte bVar3;
  byte *unaff_SI;
  byte *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  while( true ) {
    pbVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    bVar2 = *pbVar1;
    if (bVar2 == 0) break;
    bVar3 = bVar2 & 0xf0;
    if (bVar3 == *(byte *)0x497) {
      bVar3 = bVar2 & 0xf;
      bVar2 = 0xaa;
    }
    else if (bVar3 == 0x40) {
      bVar3 = bVar2 & 0xf;
      bVar2 = 0;
    }
    else if ((*(char *)0x498 == '\0') || (bVar3 != 0xd0)) {
      bVar3 = 1;
    }
    else {
      bVar3 = bVar2 & 0xf;
      bVar2 = 0xff;
    }
    do {
      pbVar1 = unaff_DI;
      unaff_DI = unaff_DI + 1;
      *pbVar1 = bVar2;
      bVar3 = bVar3 - 1;
    } while (bVar3 != 0);
  }
  return;
}



