/* Decompiled from chunk_38.bin */
/* Generated by Ghidra */

// Address: 0000:0000

/* WARNING: Control flow encountered bad instruction data */

void FUN_0000_0000(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



