/* Decompiled from chunk_24.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:011f

/* WARNING: This function may have set the stack pointer */

void FUN_0000_011f(void)

{
  byte *pbVar1;
  uint *puVar2;
  char *pcVar3;
  uint uVar4;
  int iVar5;
  byte bVar6;
  undefined2 in_AX;
  char cVar10;
  uint uVar8;
  code *pcVar9;
  byte bVar11;
  uint in_CX;
  char in_DL;
  int in_BX;
  char *pcVar12;
  int unaff_BP;
  byte *unaff_SI;
  byte *pbVar13;
  int unaff_DI;
  undefined2 unaff_SS;
  undefined2 unaff_DS;
  byte in_AF;
  char cVar7;
  
  unaff_SI[in_BX] = unaff_SI[in_BX];
  bVar6 = (byte)in_AX;
  unaff_SI[-0x3ff1] = unaff_SI[-0x3ff1] + bVar6;
  pbVar1 = (byte *)(in_BX + unaff_DI + 0x78);
  *pbVar1 = *pbVar1 | bVar6;
  unaff_SI[-0x7ff9] = unaff_SI[-0x7ff9] + bVar6;
  unaff_SI[in_BX + 0x78] = unaff_SI[in_BX + 0x78] | bVar6;
  unaff_SI[6] = unaff_SI[6] + bVar6;
  *unaff_SI = *unaff_SI + bVar6;
  pbVar1 = unaff_SI + in_BX;
  *pbVar1 = *pbVar1 << 2 | *pbVar1 >> 6;
  pbVar1 = unaff_SI;
  bVar11 = *pbVar1;
  *pbVar1 = *pbVar1 + bVar6;
  unaff_SI[in_BX] = unaff_SI[in_BX] + bVar6 + CARRY1(bVar11,bVar6);
  pbVar13 = (byte *)((uint)unaff_SI & in_CX);
  pbVar13[unaff_BP] = pbVar13[unaff_BP] + 0x7e;
  pbVar13[in_BX] = pbVar13[in_BX] ^ bVar6;
  bVar11 = 9 < (bVar6 & 0xf) | in_AF;
  cVar10 = (char)((uint)in_AX >> 8);
  bVar6 = bVar6 + bVar11 * '\x06';
  cVar7 = bVar6 + (0x90 < (bVar6 & 0xf0) | bVar11 * (0xf9 < bVar6)) * '`';
  *(uint *)(pbVar13 + in_BX) = *(uint *)(pbVar13 + in_BX) ^ CONCAT11(cVar10,cVar7);
  pcVar12 = (char *)CONCAT11((char)((uint)in_BX >> 8) + *(char *)(unaff_BP + unaff_DI + 0x10),
                             (char)in_BX);
  *pcVar12 = *pcVar12 + cVar10;
  *(char *)(unaff_BP + unaff_DI) = *(char *)(unaff_BP + unaff_DI) + 'y';
  *"" = *"" + in_DL;
  *(undefined1 **)(pcVar12 + unaff_DI + -0x28) = &stack0x0000 + *(int *)(pcVar12 + unaff_DI + -0x28)
  ;
  *(char *)0x801d = *(char *)0x801d + in_DL;
  *(undefined1 **)(pcVar12 + (int)pbVar13 + -0x28) =
       &stack0x0000 + *(int *)(pcVar12 + (int)pbVar13 + -0x28);
  uVar8 = (int)(char)in_CX + 1U | 0x8c;
  *(uint *)(pcVar12 + unaff_DI) = *(int *)(pcVar12 + unaff_DI) + uVar8;
  pcVar12 = pcVar12 + (uint)(uVar8 < 0x80) + *(int *)(pcVar12 + (int)pbVar13 + 0x100);
  *(uint *)(pcVar12 + (int)pbVar13 + 0x1a00) = *(uint *)(pcVar12 + (int)pbVar13 + 0x1a00) & uVar8;
  pcVar12[(int)pbVar13] = pcVar12[(int)pbVar13] - (char)uVar8;
  puVar2 = (uint *)(pcVar12 + (int)pbVar13 + 0x80);
  uVar4 = *puVar2;
  *puVar2 = (uint)(&stack0xfffe + *puVar2);
  cVar10 = pcVar12[(int)pbVar13];
  pcVar12[unaff_DI] = pcVar12[unaff_DI] + (char)uVar8;
  bVar11 = (cVar7 - cVar10) - CARRY2(uVar4,(uint)&stack0xfffe) | *pbVar13;
  pcVar12[(int)pbVar13] = pcVar12[(int)pbVar13] + (char)*(undefined2 *)0x80;
  iVar5 = *(int *)0xc0;
  cVar10 = (char)((uint)pcVar12 >> 8);
  bVar6 = (byte)pcVar12 | *pbVar13;
  pcVar12 = (char *)CONCAT11(cVar10,bVar6);
  pcVar3 = pcVar12 + (int)pbVar13;
  *pcVar3 = *pcVar3 + (char)iVar5;
  pcVar3 = pcVar12;
  *pcVar3 = *pcVar3 + bVar11;
  pcVar12 = (char *)CONCAT11(cVar10,bVar6 + cVar10);
  pbVar1 = (byte *)(pcVar12 + (int)pbVar13);
  *pbVar1 = *pbVar1 << 7 | *pbVar1 >> 1;
  pcVar9 = (code *)((iVar5 << 1 | (uint)(iVar5 < 0)) + 1);
  *pcVar12 = *pcVar12 + bVar11;
  pcVar12[(int)pbVar13] = pcVar12[(int)pbVar13] + (char)pcVar9;
                    /* WARNING: Could not recover jumptable at 0x000001a0. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*pcVar9)();
  return;
}



