/* Decompiled from chunk_15.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0090

void __cdecl16near FUN_0000_0090(void)

{
  char *pcVar1;
  int iVar2;
  byte bVar3;
  char cVar4;
  char *pcVar5;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  bool bVar6;
  
  bVar3 = *(byte *)((byte)(*(char *)0xc006 - 1) + 0xc9);
  pcVar5 = (char *)0xb20f;
  cVar4 = '\0';
  iVar2 = 8;
  do {
    bVar6 = CARRY1(bVar3,bVar3);
    bVar3 = bVar3 * '\x02';
    if (bVar6) {
      pcVar1 = pcVar5;
      pcVar5 = pcVar5 + 1;
      *pcVar1 = '\b' - (char)iVar2;
      cVar4 = cVar4 + '\x01';
    }
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  *(char *)0xb20e = cVar4;
  return;
}



// Address: 0000:00bc

void FUN_0000_00bc(void)

{
  byte in_AL;
  
                    /* WARNING: Could not recover jumptable at 0x000000c2. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)in_AL * 2 + -0x5f3d))();
  return;
}



// Address: 0000:05c3

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_05c3(void)

{
  int iVar1;
  int iVar2;
  char cVar3;
  undefined2 uVar4;
  char cVar5;
  
  uVar4 = 0x717;
  iVar1 = 8;
  do {
    iVar2 = 0xc;
    do {
      (*_DAT_0000_3016)(uVar4);
      cVar5 = (char)((uint)uVar4 >> 8);
      cVar3 = (char)uVar4;
      uVar4 = CONCAT11(cVar5 + '\x01',cVar3);
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar4 = CONCAT11(cVar5 + -0xb,cVar3 + '\b');
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



