/* Decompiled from chunk_04.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0136

void __cdecl16near FUN_0000_0136(void)

{
  char *pcVar1;
  char cVar2;
  char cVar3;
  byte bVar4;
  undefined2 in_BX;
  int unaff_SI;
  int unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  cVar3 = *(char *)(unaff_SI + -1);
  if (cVar3 < '\0') {
    FUN_0000_046b();
    return;
  }
  if (*(char *)(unaff_DI + -1) == -4) {
    *(undefined1 *)(unaff_DI + -1) = 0xff;
  }
  else {
    pcVar1 = (char *)(unaff_DI + -1);
    *pcVar1 = *pcVar1 + '\x01';
    cVar2 = *pcVar1;
    *(undefined1 *)(unaff_DI + -1) = 0xfe;
    if (cVar2 != '\0') {
      *(char *)(unaff_DI + -1) = cVar3;
      FUN_0000_027e();
    }
  }
  bVar4 = *(byte *)0xc012 - 5;
  if (*(byte *)0xc012 < 5) {
    return;
  }
  if (3 < bVar4) {
    return;
  }
  (*(code *)*(undefined2 *)((uint)bVar4 * 2 + 0x317e))(in_BX);
  return;
}



// Address: 0000:027e

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_027e(void)

{
  undefined2 uVar1;
  byte in_AL;
  int iVar2;
  int iVar3;
  undefined2 *in_DX;
  undefined2 *puVar4;
  undefined2 *puVar5;
  undefined2 *puVar6;
  undefined2 unaff_DS;
  
  if (in_AL == 0) {
    iVar2 = 8;
    do {
      *in_DX = 0;
      puVar4 = in_DX + 0x1000;
      if ((undefined2 *)0x5fff < puVar4) {
        *puVar4 = 0;
        puVar4 = in_DX + -0x1fd3;
      }
      iVar2 = iVar2 + -1;
      in_DX = puVar4;
    } while (iVar2 != 0);
    return;
  }
  iVar2 = (uint)in_AL * 2;
  if (*(int *)(iVar2 + 0x5016) == 0) {
    *(undefined2 *)(iVar2 + 0x5016) = in_DX;
    uVar1 = _DAT_0000_ff2c;
    iVar2 = 8;
    puVar4 = (undefined2 *)((uint)(byte)(in_AL - 1) * 0x10 + -0x7fd0);
    do {
      *in_DX = *puVar4;
      puVar6 = in_DX + 0x1000;
      if ((undefined2 *)0x5fff < puVar6) {
        *puVar6 = *puVar4;
        puVar6 = in_DX + -0x1fd3;
      }
      iVar2 = iVar2 + -1;
      puVar4 = puVar4 + 1;
      in_DX = puVar6;
    } while (iVar2 != 0);
    return;
  }
  iVar3 = 8;
  puVar4 = (undefined2 *)*(undefined2 *)(iVar2 + 0x5016);
  do {
    *in_DX = *puVar4;
    puVar6 = in_DX + 0x1000;
    if ((undefined2 *)0x5fff < puVar6) {
      *puVar6 = *puVar4;
      puVar6 = in_DX + -0x1fd3;
    }
    puVar5 = puVar4 + 0x1000;
    if ((undefined2 *)0x5fff < puVar5) {
      puVar5 = puVar4 + -0x1fd3;
    }
    iVar3 = iVar3 + -1;
    puVar4 = puVar5;
    in_DX = puVar6;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:0327

void __cdecl16near FUN_0000_0327(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe900 == -1) {
    return;
  }
  if (*(char *)0xe900 == -4) {
    return;
  }
  *(undefined1 *)0xe900 = 0xff;
  FUN_0000_1534();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x25));
  if (*(char *)(unaff_SI + 0x25) < '\0') {
    uVar1 = FUN_0000_06d8();
  }
  FUN_0000_06df(uVar1);
  FUN_0000_05a7();
  return;
}



// Address: 0000:0364

void __cdecl16near FUN_0000_0364(void)

{
  undefined1 uVar1;
  int in_BX;
  int unaff_SI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined1 *)(in_BX + -0x1700);
  *(undefined1 *)(in_BX + -0x1700) = 0xff;
  UNLOCK();
  *(undefined1 *)0x5009 = uVar1;
  *(undefined1 *)0x500a = 0;
  *(undefined1 *)(in_BX + -0x16ff) = 0xff;
  FUN_0000_1534();
  *(undefined2 *)0x500d = *(undefined2 *)(unaff_SI + 0x24);
  FUN_0000_06df();
  thunk_FUN_0000_057d();
  return;
}



// Address: 0000:03a8

void __cdecl16near FUN_0000_03a8(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe91b == -1) {
    return;
  }
  if (*(char *)0xe91b == -4) {
    return;
  }
  *(undefined1 *)0xe91b = 0xff;
  FUN_0000_1534();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x24));
  if (*(char *)(unaff_SI + 0x24) < '\0') {
    uVar1 = FUN_0000_06d8();
  }
  FUN_0000_06df(uVar1);
  FUN_0000_05a7();
  return;
}



// Address: 0000:03e0

void __cdecl16near FUN_0000_03e0(void)

{
  undefined1 uVar1;
  int extraout_DX;
  int in_BX;
  int unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *unaff_DI;
  *unaff_DI = 0xff;
  UNLOCK();
  *(undefined1 *)0x5009 = uVar1;
  LOCK();
  uVar1 = unaff_DI[0x1c];
  unaff_DI[0x1c] = 0xff;
  UNLOCK();
  *(undefined1 *)0x500a = uVar1;
  FUN_0000_1534();
  FUN_0000_06df();
  if ((*(char *)0x5009 != -1) && (*(char *)0x5009 != -4)) {
    if ((char)extraout_DX < '\0') {
      FUN_0000_06d8(in_BX * 2 + *(int *)0x4fe4,unaff_SI + 0x25);
    }
    FUN_0000_05a7();
  }
  if (((*(char *)0x4fea != '\x01') && (*(char *)0x500a != -1)) && (*(char *)0x500a != -4)) {
    if (extraout_DX < 0) {
      FUN_0000_06d8();
    }
    FUN_0000_05a7();
  }
  return;
}



// Address: 0000:046b

void __cdecl16near FUN_0000_046b(void)

{
  undefined2 uVar1;
  undefined1 uVar2;
  undefined1 in_BL;
  int iVar3;
  undefined1 *unaff_SI;
  int unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + -1);
  *(undefined2 *)(unaff_DI + -1) = 0xfffe;
  UNLOCK();
  *(undefined2 *)0x5009 = uVar1;
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + 0x1b);
  *(undefined2 *)(unaff_DI + 0x1b) = 0xffff;
  UNLOCK();
  *(undefined2 *)0x500b = uVar1;
  iVar3 = 0x500d;
  *(undefined1 *)0x500e = *unaff_SI;
  FUN_0000_1534();
  *(undefined2 *)(iVar3 + 2) = *(undefined2 *)(unaff_SI + 0x23);
  *(undefined1 *)0x4feb = in_BL;
  *(char *)0x4fec = '\x12' - *(char *)0x4fea;
  uVar2 = FUN_0000_06df();
  *(undefined1 *)0x500d = uVar2;
  thunk_FUN_0000_057d();
  if (((*(char *)0x4fea != '\x01') && (thunk_FUN_0000_057d(), *(char *)0xff34 != '\0')) &&
     (*(char *)0xff2f != '\0')) {
    FUN_0000_0730();
  }
  return;
}



// Address: 0000:04ec

void __cdecl16near FUN_0000_04ec(void)

{
  char *pcVar1;
  char *pcVar2;
  char cVar3;
  int iVar4;
  char extraout_DL;
  int in_BX;
  char *pcVar5;
  char *unaff_SI;
  char *pcVar6;
  char *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  LOCK();
  cVar3 = unaff_DI[-1];
  unaff_DI[-1] = -2;
  UNLOCK();
  *(char *)0x5009 = cVar3;
  LOCK();
  cVar3 = unaff_DI[0x1b];
  unaff_DI[0x1b] = -1;
  UNLOCK();
  *(char *)0x500a = cVar3;
  FUN_0000_1534();
  cVar3 = FUN_0000_06df();
  if ((*(char *)0x5009 != -1) && (*(char *)0x5009 != -4)) {
    if (cVar3 < '\0') {
      FUN_0000_06d8(in_BX * 2 + *(int *)0x4fe4,unaff_SI + 0x24);
    }
    FUN_0000_05a7();
  }
  if (((*(char *)0x4fea != '\x01') && (*(char *)0x500a != -1)) && (*(char *)0x500a != -4)) {
    if (extraout_DL < '\0') {
      FUN_0000_06d8();
    }
    FUN_0000_05a7();
  }
  while( true ) {
    FUN_0000_1534();
    *(int *)0x4fe4 = *(int *)0x4fe4 + 0x40b4;
    if (0x5fff < *(uint *)0x4fe4) {
      *(int *)0x4fe4 = *(int *)0x4fe4 + -0x5fa6;
    }
    pcVar1 = (char *)0x4fea;
    *pcVar1 = *pcVar1 + -1;
    if (*pcVar1 == '\0') {
      return;
    }
    FUN_0000_0d9e();
    if (unaff_SI[7] < '\0') {
      FUN_0000_03e0();
    }
    iVar4 = 6;
    pcVar2 = unaff_SI + 8;
    do {
      pcVar6 = unaff_DI;
      pcVar5 = pcVar2;
      if (*pcVar5 != *pcVar6) {
        FUN_0000_0136();
      }
      if (pcVar5[1] != pcVar6[1]) {
        FUN_0000_0136();
      }
      if (pcVar5[2] != pcVar6[2]) {
        FUN_0000_0136();
      }
      if (pcVar5[3] != pcVar6[3]) {
        FUN_0000_0136();
      }
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar5 + 4;
      unaff_DI = pcVar6 + 4;
    } while (iVar4 != 0);
    if (pcVar5[4] != pcVar6[4]) {
      FUN_0000_0136();
    }
    if (pcVar5[5] != pcVar6[5]) {
      FUN_0000_0136();
    }
    if (pcVar5[6] != pcVar6[6]) {
      FUN_0000_0136();
    }
    unaff_SI = pcVar5 + 8;
    unaff_DI = pcVar6 + 8;
    if (pcVar5[7] < '\0') break;
    if (pcVar5[7] != pcVar6[7]) {
      FUN_0000_0136();
    }
  }
  FUN_0000_04ec();
  return;
}



// Address: 0000:057a

void __cdecl16near thunk_FUN_0000_057d(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_06d8(0x57d);
      in_DX = extraout_DX;
    }
    FUN_0000_05a7(in_DX);
  }
  return;
}



// Address: 0000:057d

void __cdecl16near FUN_0000_057d(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_06d8();
      in_DX = extraout_DX;
    }
    FUN_0000_05a7(in_DX);
  }
  return;
}



// Address: 0000:05a7

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_05a7(void)

{
  char in_AL;
  byte bVar1;
  undefined2 unaff_DS;
  
  bVar1 = *(byte *)0x4fed;
  if ((in_AL != '\0') && (-1 < in_AL)) {
    bVar1 = bVar1 | 0x80;
  }
  _DAT_0000_4fe2 = *(undefined2 *)((uint)(bVar1 & 0x7f) * 2 + 0x4f86);
  if (-1 < (char)bVar1) {
    FUN_0000_0649();
    FUN_0000_06b1();
    return;
  }
  FUN_0000_061b();
  FUN_0000_06b1();
  return;
}



// Address: 0000:061b

void __cdecl16near FUN_0000_061b(void)

{
  uint uVar1;
  int iVar2;
  uint *unaff_BP;
  uint *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  FUN_0000_06ca();
  iVar2 = 8;
  do {
    *unaff_DI = *unaff_DI & *unaff_BP;
    uVar1 = FUN_0000_0654();
    *unaff_DI = *unaff_DI | uVar1;
    unaff_BP = unaff_BP + 1;
    unaff_DI = unaff_DI + 1;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:0649

void __cdecl16near FUN_0000_0649(void)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  int iVar3;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  
  iVar3 = 8;
  do {
    uVar2 = FUN_0000_0654();
    puVar1 = unaff_DI;
    unaff_DI = unaff_DI + 1;
    *puVar1 = uVar2;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:0654

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __cdecl16near FUN_0000_0654(void)

{
  uint in_AX;
  
  return CONCAT11(*(char *)((in_AX >> 0xc) + _DAT_0000_4fe2) << 4 |
                  *(byte *)((uint)((byte)(in_AX >> 8) & 0xf) + _DAT_0000_4fe2),
                  *(char *)((in_AX >> 4 & 0xf) + _DAT_0000_4fe2) << 4 |
                  *(byte *)((uint)((byte)in_AX & 0xf) + _DAT_0000_4fe2));
}



// Address: 0000:06b1

void __cdecl16near FUN_0000_06b1(void)

{
  int iVar1;
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 *puVar2;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  iVar1 = 8;
  do {
    *unaff_DI = *unaff_SI;
    puVar2 = unaff_DI + 0x1000;
    if ((undefined2 *)0x5fff < puVar2) {
      *puVar2 = *unaff_SI;
      puVar2 = unaff_DI + -0x1fd3;
    }
    iVar1 = iVar1 + -1;
    unaff_SI = unaff_SI + 1;
    unaff_DI = puVar2;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:06ca

void __cdecl16near FUN_0000_06ca(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  int iVar3;
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  for (iVar3 = 8; iVar3 != 0; iVar3 = iVar3 + -1) {
    puVar2 = unaff_DI;
    unaff_DI = unaff_DI + 1;
    puVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    *puVar2 = *puVar1;
  }
  return;
}



// Address: 0000:06d8

undefined1 __cdecl16near FUN_0000_06d8(void)

{
  byte in_AL;
  
  return *(undefined1 *)(ulong)((in_AL & 0x7f) + 0xed20);
}



// Address: 0000:06df

undefined2 __cdecl16near FUN_0000_06df(void)

{
  undefined1 uVar1;
  byte in_AL;
  char cVar2;
  int iVar3;
  char *pcVar4;
  int iVar5;
  undefined2 unaff_DS;
  
  uVar1 = *(undefined1 *)((in_AL & 0x7f) + 0xed20);
  iVar3 = (uint)(in_AL & 0x7f) * 0x10 + *(int *)0xc010;
  iVar5 = -0x5f90;
  if ((*(byte *)(iVar3 + 5) & 0x80) == 0) {
    iVar5 = -0x5fd0;
  }
  pcVar4 = (char *)((uint)(*(byte *)(iVar3 + 6) & 0xf) * 5 +
                   *(int *)((uint)(byte)((*(byte *)(iVar3 + 4) & 0x1f) * '\x02') + iVar5));
  cVar2 = *pcVar4;
  if ((*(char *)0xff34 == '\0') && ((*(byte *)(iVar3 + 5) & 0x20) != 0)) {
    cVar2 = cVar2 + '\x03';
  }
  *(char *)0x4fed = cVar2;
  return CONCAT11((char)((uint)pcVar4 >> 8),uVar1);
}



// Address: 0000:0730

void __cdecl16near FUN_0000_0730(void)

{
  byte bVar1;
  byte *pbVar2;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  if (0xf < *(byte *)0x4fec) {
    return;
  }
  bVar1 = (*pcRam0000011a)();
  if ((bVar1 & 0xf) < 0xe) {
    return;
  }
  bVar1 = 0;
  for (pbVar2 = (byte *)0xeda0; *pbVar2 != 0xff; pbVar2 = pbVar2 + 4) {
    bVar1 = bVar1 + 1;
  }
  if (0x1f < bVar1) {
    return;
  }
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x4feb;
  if (bVar1 == 0xff) {
    bVar1 = 4;
  }
  if (0x1a < bVar1) {
    bVar1 = 0x1a;
  }
  *pbVar2 = bVar1;
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x4fec;
  if (bVar1 == 0xff) {
    bVar1 = 0;
  }
  pbVar2[1] = bVar1;
  pbVar2[2] = 3;
  bVar1 = (*pcRam0000011a)();
  pbVar2[3] = *(byte *)(ulong)((bVar1 & 3) + 0x37a2);
  pbVar2[4] = 0xff;
  return;
}



// Address: 0000:0d9e

void __cdecl16near FUN_0000_0d9e(void)

{
  byte bVar1;
  byte bVar2;
  undefined2 unaff_DS;
  
  bVar1 = 0x12 - *(char *)0x4fea;
  if (*(char *)0xff43 == '\0') {
    if ((byte)(*(char *)0x84 - 2U) == bVar1) {
      FUN_0000_1068();
    }
    return;
  }
  bVar2 = *(char *)0x84 - 5;
  if (bVar1 < bVar2) {
    return;
  }
  if (bVar1 == bVar2) {
    FUN_0000_0f19();
    FUN_0000_1068();
    return;
  }
  if ((byte)(*(char *)0x84 + 5U) != bVar1) {
    return;
  }
  FUN_0000_0fd9();
  return;
}



// Address: 0000:0f19

void __cdecl16near FUN_0000_0f19(void)

{
  undefined2 unaff_DS;
  
  if (*(char *)0xff44 == '\0') {
    return;
  }
  FUN_0000_0f5b();
  *(undefined1 *)0xff44 = 0;
  return;
}



// Address: 0000:0f32

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0f32(void)

{
  int iVar1;
  undefined2 *puVar2;
  undefined2 *puVar3;
  undefined2 *puVar4;
  undefined2 unaff_CS;
  
  puVar4 = (undefined2 *)0x5116;
  iVar1 = 0x20;
  puVar2 = _DAT_0000_4fef;
  do {
    *puVar4 = *puVar2;
    puVar4[1] = puVar2[1];
    puVar3 = puVar4 + 3;
    puVar4[2] = puVar2[2];
    puVar4 = puVar4 + 4;
    *puVar3 = puVar2[3];
    puVar3 = puVar2 + 0x1000;
    if ((undefined2 *)0x5fff < puVar3) {
      puVar3 = puVar2 + -0x1fd3;
    }
    iVar1 = iVar1 + -1;
    puVar2 = puVar3;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0f5b

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0f5b(void)

{
  int iVar1;
  undefined2 *puVar2;
  undefined2 *puVar3;
  undefined2 *puVar4;
  undefined2 unaff_CS;
  
  puVar2 = (undefined2 *)0x5116;
  iVar1 = 0x20;
  puVar3 = _DAT_0000_4fef;
  do {
    *puVar3 = *puVar2;
    puVar3[1] = puVar2[1];
    puVar3[2] = puVar2[2];
    puVar3[3] = puVar2[3];
    puVar4 = puVar3 + 0x1000;
    if ((undefined2 *)0x5fff < puVar4) {
      *puVar4 = *puVar2;
      puVar3[0x1001] = puVar2[1];
      puVar3[0x1002] = puVar2[2];
      puVar3[0x1003] = puVar2[3];
      puVar4 = puVar3 + -0x1fd3;
    }
    puVar2 = puVar2 + 4;
    iVar1 = iVar1 + -1;
    puVar3 = puVar4;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0f8f

void __cdecl16near FUN_0000_0f8f(void)

{
  int iVar1;
  int iVar2;
  byte *pbVar3;
  byte *pbVar4;
  undefined2 unaff_DS;
  
  pbVar3 = (byte *)((uint)(*(char *)0x84 + *(char *)0x4ff3 & 0x3f) * 0x24 +
                    (uint)(byte)(*(char *)0x83 + *(char *)0x4ff4 + 4) + *(int *)0xff31);
  FUN_0000_1534();
  iVar1 = 4;
  do {
    iVar2 = 4;
    do {
      pbVar4 = pbVar3;
      *(undefined2 *)((uint)(*pbVar4 & 0x7f) * 2 + 0x5016) = 0;
      iVar2 = iVar2 + -1;
      pbVar3 = pbVar4 + 1;
    } while (iVar2 != 0);
    pbVar3 = pbVar4 + 0x21;
    FUN_0000_1534();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0fd9

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0fd9(void)

{
  byte *pbVar1;
  uint *puVar2;
  uint uVar3;
  undefined2 uVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  byte *pbVar8;
  uint *puVar9;
  uint *puVar10;
  uint *puVar11;
  uint *puVar12;
  undefined2 unaff_DS;
  
  if (*(char *)0xff43 != '\0') {
    *(undefined1 *)0xff44 = 0xff;
    FUN_0000_0f8f();
    FUN_0000_0f32();
    uVar4 = _DAT_0000_ff2c;
    iVar5 = 4;
    pbVar8 = _DAT_0000_4ff1;
    puVar10 = _DAT_0000_4fef;
    do {
      iVar6 = 4;
      puVar11 = puVar10;
      do {
        pbVar1 = pbVar8;
        pbVar8 = pbVar8 + 1;
        if (*pbVar1 == 0xff) {
          puVar12 = puVar11 + 0x205a;
          if ((uint *)0x5fff < puVar12) {
            puVar12 = puVar11 + -0xf79;
          }
        }
        else {
          puVar9 = (uint *)((uint)*pbVar1 * 0x10 + *(int *)0xb000);
          iVar7 = 8;
          do {
            puVar2 = puVar9;
            puVar9 = puVar9 + 1;
            uVar3 = *puVar2;
            *puVar11 = *puVar11 | uVar3;
            puVar12 = puVar11 + 0x1000;
            if ((uint *)0x5fff < puVar12) {
              *puVar12 = *puVar12 | uVar3;
              puVar12 = puVar11 + -0x1fd3;
            }
            iVar7 = iVar7 + -1;
            puVar11 = puVar12;
          } while (iVar7 != 0);
        }
        iVar6 = iVar6 + -1;
        puVar11 = puVar12;
      } while (iVar6 != 0);
      puVar10 = puVar10 + 1;
      iVar5 = iVar5 + -1;
    } while (iVar5 != 0);
    return;
  }
  return;
}



// Address: 0000:1068

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1068(void)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  undefined2 unaff_DS;
  
  if (*(char *)0xff37 != '\0') {
    return;
  }
  *(undefined1 *)0xff37 = 0xff;
  iVar1 = 3;
  uVar4 = _DAT_0000_4fe6;
  do {
    iVar2 = 3;
    do {
      uVar3 = uVar4;
      FUN_0000_06b1();
      iVar2 = iVar2 + -1;
      uVar4 = uVar3 + 2;
    } while (iVar2 != 0);
    uVar4 = uVar3 + 0x40b0;
    if (0x5fff < uVar4) {
      uVar4 = uVar3 + 0xe10a;
    }
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:1534

void __cdecl16near FUN_0000_1534(void)

{
  uint unaff_SI;
  
  if (unaff_SI < 0xe900) {
    return;
  }
  return;
}



// Address: 0000:1540

void __cdecl16near FUN_0000_1540(void)

{
  uint unaff_SI;
  
  if (0xdfff < unaff_SI) {
    return;
  }
  return;
}



