/* Decompiled from chunk_13.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:00b1

void FUN_0000_00b1(void)

{
  byte in_AL;
  
                    /* WARNING: Could not recover jumptable at 0x000000b7. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)in_AL * 2 + -0x5f48))();
  return;
}



// Address: 0000:06a7

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_06a7(void)

{
  int iVar1;
  int iVar2;
  char cVar3;
  undefined2 uVar4;
  char cVar5;
  
  uVar4 = 0x717;
  iVar1 = 8;
  do {
    iVar2 = 0xc;
    do {
      (*_DAT_0000_3016)(uVar4);
      cVar5 = (char)((uint)uVar4 >> 8);
      cVar3 = (char)uVar4;
      uVar4 = CONCAT11(cVar5 + '\x01',cVar3);
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar4 = CONCAT11(cVar5 + -0xb,cVar3 + '\b');
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:072c

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_072c(void)

{
  int iVar1;
  int iVar2;
  char cVar3;
  undefined2 uVar4;
  char cVar5;
  undefined2 unaff_DS;
  
  if (*(char *)0xad21 == '\0') {
    return;
  }
  if (*(uint *)0xff50 < 0x1e) {
    return;
  }
  *(undefined2 *)0xff50 = 0;
  *(char *)0xad22 = *(char *)0xad22 + '\x01';
  uVar4 = 0x91f;
  iVar1 = 5;
  do {
    iVar2 = 8;
    do {
      (*_DAT_0000_3016)(uVar4);
      cVar5 = (char)((uint)uVar4 >> 8);
      cVar3 = (char)uVar4;
      uVar4 = CONCAT11(cVar5 + '\x01',cVar3);
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar4 = CONCAT11(cVar5 + -7,cVar3 + '\b');
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



