/* Decompiled from chunk_09.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:008d

void FUN_0000_008d(void)

{
  undefined2 unaff_DS;
  
                    /* WARNING: Could not recover jumptable at 0x00000095. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)*(byte *)&DAT_0000_3388 * 2 + 0x3395))();
  return;
}



// Address: 0000:0368

void __cdecl16near FUN_0000_0368(void)

{
  byte *pbVar1;
  byte bVar2;
  byte bVar3;
  byte *unaff_SI;
  byte *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  while( true ) {
    pbVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    bVar3 = *pbVar1;
    if (bVar3 == 0) break;
    if ((bVar3 & 0xf0) == 0x10) {
      bVar2 = bVar3 & 0xf;
      bVar3 = 0;
    }
    else if ((bVar3 & 0xf0) == 0x40) {
      bVar2 = bVar3 & 0xf;
      bVar3 = 0xaa;
    }
    else {
      bVar2 = 1;
    }
    do {
      pbVar1 = unaff_DI;
      unaff_DI = unaff_DI + 1;
      *pbVar1 = bVar3;
      bVar2 = bVar2 - 1;
    } while (bVar2 != 0);
  }
  return;
}



// Address: 0000:0399

void FUN_0000_0399(void)

{
                    /* WARNING: Could not recover jumptable at 0x000003a6. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)DAT_0000_3388 * 2 + 0x36a5))();
  return;
}



