/* Decompiled from chunk_04.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:01a0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int __cdecl16near FUN_0000_01a0(void)

{
  char cVar1;
  undefined2 in_CX;
  byte bVar3;
  undefined2 uVar2;
  int iVar4;
  undefined2 unaff_SI;
  uint unaff_DI;
  uint uVar5;
  uint uVar6;
  
  DAT_0000_4c0a = '\0';
  iVar4 = 8;
  do {
    DAT_0000_4c09 = DAT_0000_4c0a;
    DAT_0000_ff1a = 0;
    uVar2 = in_CX;
    uVar6 = unaff_DI;
    do {
      (*_DAT_0000_4c0f)(uVar6,unaff_SI);
      DAT_0000_4c09 = DAT_0000_4c09 + '\x01';
      bVar3 = (byte)((uint)uVar2 >> 8);
      uVar5 = unaff_DI + 0x2000;
      if (0x7fff < uVar5) {
        uVar5 = unaff_DI + 0xa0a0;
      }
      cVar1 = (char)uVar2 + -1;
      if (cVar1 == '\0') break;
      (*_DAT_0000_4c0f)();
      DAT_0000_4c09 = DAT_0000_4c09 + '\x01';
      unaff_DI = uVar5 + 0x2000;
      if (0x7fff < unaff_DI) {
        unaff_DI = uVar5 + 0xa0a0;
      }
      uVar2 = CONCAT11(bVar3,cVar1 + -1);
    } while ((char)(cVar1 + -1) != '\0');
    unaff_DI = uVar6;
    DAT_0000_4c0a = DAT_0000_4c0a + '\x01';
    do {
    } while (DAT_0000_ff1a < 0x14);
    iVar4 = iVar4 + -1;
    if (iVar4 == 0) {
      return (uint)bVar3 * 2;
    }
  } while( true );
}



// Address: 0000:1ae8

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __cdecl16near FUN_0000_1ae8(void)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  byte bVar5;
  int in_AX;
  undefined1 uVar6;
  int iVar7;
  bool bVar8;
  bool bVar9;
  bool bVar10;
  bool bVar11;
  
  iVar7 = 4;
  do {
    bVar8 = (int)_DAT_0000_4c05 < 0;
    uVar1 = _DAT_0000_4c05 << 1 | (uint)bVar8;
    bVar9 = (int)_DAT_0000_4c03 < 0;
    uVar2 = _DAT_0000_4c03 << 1 | (uint)bVar9;
    bVar10 = (int)_DAT_0000_4c01 < 0;
    uVar3 = _DAT_0000_4c01 << 1 | (uint)bVar10;
    bVar11 = (int)_DAT_0000_4bff < 0;
    uVar4 = _DAT_0000_4bff << 1 | (uint)bVar11;
    _DAT_0000_4c05 = uVar1 << 1 | (uint)((int)uVar1 < 0);
    _DAT_0000_4c03 = uVar2 << 1 | (uint)((int)uVar2 < 0);
    _DAT_0000_4c01 = uVar3 << 1 | (uint)((int)uVar3 < 0);
    _DAT_0000_4bff = uVar4 << 1 | (uint)((int)uVar4 < 0);
    uVar6 = (undefined1)((uint)(in_AX * 0x10) >> 8);
    bVar5 = (byte)(in_AX * 0x10) |
            *(byte *)((((((((uint)bVar8 * 2 + (uint)bVar9) * 2 + (uint)bVar10) * 2 + (uint)bVar11) *
                         2 + (uint)((int)uVar1 < 0)) * 2 + (uint)((int)uVar2 < 0)) * 2 +
                      (uint)((int)uVar3 < 0)) * 2 + (uint)((int)uVar4 < 0) + _DAT_0000_4bfd);
    in_AX = CONCAT11(uVar6,bVar5);
    iVar7 = iVar7 + -1;
  } while (iVar7 != 0);
  return CONCAT11(bVar5,uVar6);
}



// Address: 0000:1be0

int __cdecl16near FUN_0000_1be0(void)

{
  uint in_BX;
  
  return (in_BX >> 2 & 0x3f) * 0xa0 +
         (uint)((byte)((byte)((byte)in_BX << 7) >> 1 | ((byte)in_BX >> 1) << 7) >> 1) * 0x100 +
         (uint)(byte)((char)(in_BX >> 8) * '\x02');
}



