/* Decompiled from chunk_02.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0128

void __cdecl16near FUN_0000_0128(void)

{
  char *pcVar1;
  char cVar2;
  char cVar3;
  byte bVar4;
  undefined2 in_BX;
  int unaff_SI;
  int unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  cVar3 = *(char *)(unaff_SI + -1);
  if (cVar3 < '\0') {
    FUN_0000_049b();
    return;
  }
  if (*(char *)(unaff_DI + -1) == -4) {
    *(undefined1 *)(unaff_DI + -1) = 0xff;
  }
  else {
    pcVar1 = (char *)(unaff_DI + -1);
    *pcVar1 = *pcVar1 + '\x01';
    cVar2 = *pcVar1;
    *(undefined1 *)(unaff_DI + -1) = 0xfe;
    if (cVar2 != '\0') {
      *(char *)(unaff_DI + -1) = cVar3;
      FUN_0000_0270();
    }
  }
  bVar4 = *(byte *)0xc012 - 5;
  if (*(byte *)0xc012 < 5) {
    return;
  }
  if (3 < bVar4) {
    return;
  }
  (*(code *)*(undefined2 *)((uint)bVar4 * 2 + 0x3170))(in_BX);
  return;
}



// Address: 0000:0270

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 __cdecl16near FUN_0000_0270(void)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  undefined1 *puVar3;
  undefined2 uVar4;
  byte in_AL;
  undefined2 *puVar5;
  int iVar6;
  undefined2 *in_DX;
  undefined2 unaff_DS;
  
  if (in_AL == 0) {
    out(0x3c4,0x702);
    *in_DX = 0;
    in_DX[0x28] = 0;
    in_DX[0x50] = 0;
    in_DX[0x78] = 0;
    in_DX[0xa0] = 0;
    in_DX[200] = 0;
    in_DX[0xf0] = 0;
    in_DX[0x118] = 0;
    return 0x3c40000;
  }
  iVar6 = (uint)in_AL * 2;
  if (*(int *)(iVar6 + 0x5097) == 0) {
    *(undefined2 *)(iVar6 + 0x5097) = in_DX;
    uVar4 = _DAT_0000_ff2c;
    puVar5 = (undefined2 *)((uint)in_AL * 0x30 + -0x8000);
    out(0x3c4,2);
    iVar6 = 4;
    do {
      out(0x3c5,1);
      *in_DX = *puVar5;
      out(0x3c5,2);
      *in_DX = puVar5[1];
      out(0x3c5,4);
      *in_DX = puVar5[2];
      out(0x3c5,1);
      in_DX[0x28] = puVar5[3];
      out(0x3c5,2);
      puVar1 = puVar5 + 5;
      uVar2 = puVar5[4];
      in_DX[0x28] = uVar2;
      out(0x3c5,4);
      puVar5 = puVar5 + 6;
      in_DX[0x28] = *puVar1;
      in_DX = in_DX + 0x50;
      iVar6 = iVar6 + -1;
    } while (iVar6 != 0);
    return CONCAT22(0x3c5,CONCAT11((char)((uint)uVar2 >> 8),4));
  }
  puVar3 = (undefined1 *)*(undefined2 *)(iVar6 + 0x5097);
  out(0x3c4,0x702);
  out(0x3ce,0x105);
  *(undefined1 *)in_DX = *puVar3;
  *(undefined1 *)((int)in_DX + 1) = puVar3[1];
  *(undefined1 *)(in_DX + 0x28) = puVar3[0x50];
  *(undefined1 *)((int)in_DX + 0x51) = puVar3[0x51];
  *(undefined1 *)(in_DX + 0x50) = puVar3[0xa0];
  *(undefined1 *)((int)in_DX + 0xa1) = puVar3[0xa1];
  *(undefined1 *)(in_DX + 0x78) = puVar3[0xf0];
  *(undefined1 *)((int)in_DX + 0xf1) = puVar3[0xf1];
  *(undefined1 *)(in_DX + 0xa0) = puVar3[0x140];
  *(undefined1 *)((int)in_DX + 0x141) = puVar3[0x141];
  *(undefined1 *)(in_DX + 200) = puVar3[400];
  *(undefined1 *)((int)in_DX + 0x191) = puVar3[0x191];
  *(undefined1 *)(in_DX + 0xf0) = puVar3[0x1e0];
  *(undefined1 *)((int)in_DX + 0x1e1) = puVar3[0x1e1];
  *(undefined1 *)(in_DX + 0x118) = puVar3[0x230];
  *(undefined1 *)((int)in_DX + 0x231) = puVar3[0x231];
  out(0x3ce,5);
  return 0x3ce0005;
}



// Address: 0000:0361

void __cdecl16near FUN_0000_0361(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe900 == -1) {
    return;
  }
  if (*(char *)0xe900 == -4) {
    return;
  }
  *(undefined1 *)0xe900 = 0xff;
  FUN_0000_16a9();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x25));
  if (*(char *)(unaff_SI + 0x25) < '\0') {
    uVar1 = FUN_0000_0799();
  }
  FUN_0000_07a0(uVar1);
  FUN_0000_05c3();
  return;
}



// Address: 0000:039e

void __cdecl16near FUN_0000_039e(void)

{
  undefined1 uVar1;
  int in_BX;
  int unaff_SI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined1 *)(in_BX + -0x1700);
  *(undefined1 *)(in_BX + -0x1700) = 0xff;
  UNLOCK();
  *(undefined1 *)0x508a = uVar1;
  *(undefined1 *)0x508b = 0;
  *(undefined1 *)(in_BX + -0x16ff) = 0xff;
  FUN_0000_16a9();
  *(undefined2 *)0x508e = *(undefined2 *)(unaff_SI + 0x24);
  FUN_0000_07a0();
  thunk_FUN_0000_0599();
  return;
}



// Address: 0000:03e2

void __cdecl16near FUN_0000_03e2(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe91b == -1) {
    return;
  }
  if (*(char *)0xe91b == -4) {
    return;
  }
  *(undefined1 *)0xe91b = 0xff;
  FUN_0000_16a9();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x24));
  if (*(char *)(unaff_SI + 0x24) < '\0') {
    uVar1 = FUN_0000_0799();
  }
  FUN_0000_07a0(uVar1);
  FUN_0000_05c3();
  return;
}



// Address: 0000:041a

void __cdecl16near FUN_0000_041a(void)

{
  undefined1 uVar1;
  int extraout_DX;
  int in_BX;
  int unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *unaff_DI;
  *unaff_DI = 0xff;
  UNLOCK();
  *(undefined1 *)0x508a = uVar1;
  LOCK();
  uVar1 = unaff_DI[0x1c];
  unaff_DI[0x1c] = 0xff;
  UNLOCK();
  *(undefined1 *)0x508b = uVar1;
  FUN_0000_16a9();
  FUN_0000_07a0();
  if ((*(char *)0x508a != -1) && (*(char *)0x508a != -4)) {
    if ((char)extraout_DX < '\0') {
      FUN_0000_0799(in_BX * 2 + *(int *)0x5069,unaff_SI + 0x25);
    }
    FUN_0000_05c3();
  }
  if (((*(char *)0x506d != '\x01') && (*(char *)0x508b != -1)) && (*(char *)0x508b != -4)) {
    if (extraout_DX < 0) {
      FUN_0000_0799();
    }
    FUN_0000_05c3();
  }
  return;
}



// Address: 0000:049b

void __cdecl16near FUN_0000_049b(void)

{
  undefined2 uVar1;
  undefined1 uVar2;
  undefined1 in_BL;
  int iVar3;
  undefined1 *unaff_SI;
  int unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + -1);
  *(undefined2 *)(unaff_DI + -1) = 0xfffe;
  UNLOCK();
  *(undefined2 *)0x508a = uVar1;
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + 0x1b);
  *(undefined2 *)(unaff_DI + 0x1b) = 0xffff;
  UNLOCK();
  *(undefined2 *)0x508c = uVar1;
  iVar3 = 0x508e;
  *(undefined1 *)0x508f = *unaff_SI;
  FUN_0000_16a9();
  *(undefined2 *)(iVar3 + 2) = *(undefined2 *)(unaff_SI + 0x23);
  *(undefined1 *)0x506e = in_BL;
  *(char *)0x506f = '\x12' - *(char *)0x506d;
  uVar2 = FUN_0000_07a0();
  *(undefined1 *)0x508e = uVar2;
  thunk_FUN_0000_0599();
  if (*(char *)0x506d != '\x01') {
    thunk_FUN_0000_0599();
    if ((*(char *)0xff34 != '\0') && (*(char *)0xff2f != '\0')) {
      FUN_0000_07f1();
    }
  }
  return;
}



// Address: 0000:0512

void __cdecl16near FUN_0000_0512(void)

{
  char *pcVar1;
  char *pcVar2;
  char cVar3;
  int iVar4;
  char extraout_DL;
  int in_BX;
  char *pcVar5;
  char *unaff_SI;
  char *pcVar6;
  char *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  LOCK();
  cVar3 = unaff_DI[-1];
  unaff_DI[-1] = -2;
  UNLOCK();
  *(char *)0x508a = cVar3;
  LOCK();
  cVar3 = unaff_DI[0x1b];
  unaff_DI[0x1b] = -1;
  UNLOCK();
  *(char *)0x508b = cVar3;
  FUN_0000_16a9();
  cVar3 = FUN_0000_07a0();
  if ((*(char *)0x508a != -1) && (*(char *)0x508a != -4)) {
    if (cVar3 < '\0') {
      FUN_0000_0799(in_BX * 2 + *(int *)0x5069,unaff_SI + 0x24);
    }
    FUN_0000_05c3();
  }
  if (((*(char *)0x506d != '\x01') && (*(char *)0x508b != -1)) && (*(char *)0x508b != -4)) {
    if (extraout_DL < '\0') {
      FUN_0000_0799();
    }
    FUN_0000_05c3();
  }
  while( true ) {
    FUN_0000_16a9();
    *(int *)0x5069 = *(int *)0x5069 + 0x280;
    pcVar1 = (char *)0x506d;
    *pcVar1 = *pcVar1 + -1;
    if (*pcVar1 == '\0') {
      return;
    }
    FUN_0000_0e7a();
    if (unaff_SI[7] < '\0') {
      FUN_0000_041a();
    }
    iVar4 = 6;
    pcVar2 = unaff_SI + 8;
    do {
      pcVar6 = unaff_DI;
      pcVar5 = pcVar2;
      if (*pcVar5 != *pcVar6) {
        FUN_0000_0128();
      }
      if (pcVar5[1] != pcVar6[1]) {
        FUN_0000_0128();
      }
      if (pcVar5[2] != pcVar6[2]) {
        FUN_0000_0128();
      }
      if (pcVar5[3] != pcVar6[3]) {
        FUN_0000_0128();
      }
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar5 + 4;
      unaff_DI = pcVar6 + 4;
    } while (iVar4 != 0);
    if (pcVar5[4] != pcVar6[4]) {
      FUN_0000_0128();
    }
    if (pcVar5[5] != pcVar6[5]) {
      FUN_0000_0128();
    }
    if (pcVar5[6] != pcVar6[6]) {
      FUN_0000_0128();
    }
    unaff_SI = pcVar5 + 8;
    unaff_DI = pcVar6 + 8;
    if (pcVar5[7] < '\0') break;
    if (pcVar5[7] != pcVar6[7]) {
      FUN_0000_0128();
    }
  }
  FUN_0000_0512();
  return;
}



// Address: 0000:0596

void __cdecl16near thunk_FUN_0000_0599(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_0799(0x599);
      in_DX = extraout_DX;
    }
    FUN_0000_05c3(in_DX);
  }
  return;
}



// Address: 0000:0599

void __cdecl16near FUN_0000_0599(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_0799();
      in_DX = extraout_DX;
    }
    FUN_0000_05c3(in_DX);
  }
  return;
}



// Address: 0000:05c3

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_05c3(void)

{
  char in_AL;
  byte bVar1;
  undefined2 unaff_DS;
  
  bVar1 = *(byte *)0x5070;
  if ((in_AL != '\0') && (-1 < in_AL)) {
    bVar1 = bVar1 | 0x80;
  }
  _DAT_0000_5067 = *(undefined2 *)((uint)(bVar1 & 0x7f) * 2 + 0x505a);
  if (-1 < (char)bVar1) {
    FUN_0000_06cb();
    FUN_0000_0730();
    return;
  }
  FUN_0000_062f();
  FUN_0000_0730();
  return;
}



// Address: 0000:062f

undefined4 __cdecl16near FUN_0000_062f(void)

{
  undefined2 *puVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  undefined1 uVar5;
  undefined1 uVar6;
  uint uVar4;
  int iVar7;
  undefined2 *unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  FUN_0000_0768();
  out(0x3c4,0x702);
  out(0x3ce,0x205);
  iVar7 = 8;
  do {
    puVar1 = unaff_SI + 1;
    uVar5 = (undefined1)((uint)*unaff_SI >> 8);
    uVar2 = (undefined1)*unaff_SI;
    unaff_SI = unaff_SI + 2;
    uVar6 = (undefined1)((uint)*puVar1 >> 8);
    uVar3 = (undefined1)*puVar1;
    out(0x3ce,3);
    out(0x3ce,8);
    uVar4 = CONCAT11(uVar2,uVar5) | CONCAT11(uVar3,uVar6);
    uVar4 = uVar4 | uVar4 << 1 | (uVar4 & 0x7fff) >> 1;
    out(0x3cf,(char)(uVar4 >> 8));
    LOCK();
    *unaff_DI = 0;
    UNLOCK();
    out(0x3cf,(char)uVar4);
    LOCK();
    unaff_DI[1] = 0;
    UNLOCK();
    out(0x3ce,0x1003);
    out(0x3ce,8);
    out(0x3cf,uVar2);
    LOCK();
    *unaff_DI = DAT_0000_5067;
    UNLOCK();
    out(0x3cf,uVar5);
    LOCK();
    unaff_DI[1] = DAT_0000_5067;
    UNLOCK();
    out(0x3cf,uVar3);
    LOCK();
    *unaff_DI = DAT_0000_5068;
    UNLOCK();
    out(0x3cf,uVar6);
    LOCK();
    unaff_DI[1] = DAT_0000_5068;
    UNLOCK();
    unaff_DI = unaff_DI + 2;
    iVar7 = iVar7 + -1;
  } while (iVar7 != 0);
  out(0x3ce,3);
  out(0x3ce,5);
  out(0x3ce,0xff08);
  return 0x3ceff08;
}



// Address: 0000:06cb

undefined4 __cdecl16near FUN_0000_06cb(void)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  int iVar3;
  undefined2 *unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  out(0x3c4,0x702);
  out(0x3ce,0x205);
  iVar3 = 8;
  do {
    out(0x3ce,3);
    out(0x3ce,0xff08);
    LOCK();
    *unaff_DI = 0;
    UNLOCK();
    LOCK();
    unaff_DI[1] = 0;
    UNLOCK();
    out(0x3ce,0x1003);
    out(0x3ce,8);
    puVar1 = unaff_SI + 1;
    uVar2 = *unaff_SI;
    out(0x3cf,(char)uVar2);
    LOCK();
    *unaff_DI = DAT_0000_5067;
    UNLOCK();
    out(0x3cf,(char)((uint)uVar2 >> 8));
    LOCK();
    unaff_DI[1] = DAT_0000_5067;
    UNLOCK();
    unaff_SI = unaff_SI + 2;
    uVar2 = *puVar1;
    out(0x3cf,(char)uVar2);
    LOCK();
    *unaff_DI = DAT_0000_5068;
    UNLOCK();
    out(0x3cf,(char)((uint)uVar2 >> 8));
    LOCK();
    unaff_DI[1] = DAT_0000_5068;
    UNLOCK();
    unaff_DI = unaff_DI + 2;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  out(0x3ce,3);
  out(0x3ce,5);
  out(0x3ce,0xff08);
  return 0x3ceff08;
}



// Address: 0000:0730

undefined4 __cdecl16near FUN_0000_0730(void)

{
  undefined1 *unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  out(0x3c4,0x702);
  out(0x3ce,0x105);
  *unaff_DI = *unaff_SI;
  unaff_DI[1] = unaff_SI[1];
  unaff_DI[0x50] = unaff_SI[2];
  unaff_DI[0x51] = unaff_SI[3];
  unaff_DI[0xa0] = unaff_SI[4];
  unaff_DI[0xa1] = unaff_SI[5];
  unaff_DI[0xf0] = unaff_SI[6];
  unaff_DI[0xf1] = unaff_SI[7];
  unaff_DI[0x140] = unaff_SI[8];
  unaff_DI[0x141] = unaff_SI[9];
  unaff_DI[400] = unaff_SI[10];
  unaff_DI[0x191] = unaff_SI[0xb];
  unaff_DI[0x1e0] = unaff_SI[0xc];
  unaff_DI[0x1e1] = unaff_SI[0xd];
  unaff_DI[0x230] = unaff_SI[0xe];
  unaff_DI[0x231] = unaff_SI[0xf];
  out(0x3ce,5);
  return 0x3ce0005;
}



// Address: 0000:0768

undefined4 __cdecl16near FUN_0000_0768(void)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  int iVar3;
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  out(0x3c4,2);
  iVar3 = 8;
  do {
    out(0x3c5,1);
    *unaff_DI = *unaff_SI;
    out(0x3c5,2);
    puVar1 = unaff_SI + 2;
    uVar2 = unaff_SI[1];
    *unaff_DI = uVar2;
    out(0x3c5,4);
    unaff_SI = unaff_SI + 3;
    *unaff_DI = *puVar1;
    iVar3 = iVar3 + -1;
    unaff_DI = unaff_DI + 1;
  } while (iVar3 != 0);
  return CONCAT22(0x3c5,CONCAT11((char)((uint)uVar2 >> 8),4));
}



// Address: 0000:0799

undefined1 __cdecl16near FUN_0000_0799(void)

{
  byte in_AL;
  
  return *(undefined1 *)(ulong)((in_AL & 0x7f) + 0xed20);
}



// Address: 0000:07a0

undefined2 __cdecl16near FUN_0000_07a0(void)

{
  undefined1 uVar1;
  byte in_AL;
  char cVar2;
  int iVar3;
  char *pcVar4;
  int iVar5;
  undefined2 unaff_DS;
  
  uVar1 = *(undefined1 *)((in_AL & 0x7f) + 0xed20);
  iVar3 = (uint)(in_AL & 0x7f) * 0x10 + *(int *)0xc010;
  iVar5 = -0x5f90;
  if ((*(byte *)(iVar3 + 5) & 0x80) == 0) {
    iVar5 = -0x5fd0;
  }
  pcVar4 = (char *)((uint)(*(byte *)(iVar3 + 6) & 0xf) * 5 +
                   *(int *)((uint)(byte)((*(byte *)(iVar3 + 4) & 0x1f) * '\x02') + iVar5));
  cVar2 = *pcVar4;
  if ((*(char *)0xff34 == '\0') && ((*(byte *)(iVar3 + 5) & 0x20) != 0)) {
    cVar2 = cVar2 + '\x03';
  }
  *(char *)0x5070 = cVar2;
  return CONCAT11((char)((uint)pcVar4 >> 8),uVar1);
}



// Address: 0000:07f1

void __cdecl16near FUN_0000_07f1(void)

{
  byte bVar1;
  byte *pbVar2;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  if (0xf < *(byte *)0x506f) {
    return;
  }
  bVar1 = (*pcRam0000011a)();
  if ((bVar1 & 0xf) < 0xe) {
    return;
  }
  bVar1 = 0;
  for (pbVar2 = (byte *)0xeda0; *pbVar2 != 0xff; pbVar2 = pbVar2 + 4) {
    bVar1 = bVar1 + 1;
  }
  if (0x1f < bVar1) {
    return;
  }
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x506e;
  if (bVar1 == 0xff) {
    bVar1 = 4;
  }
  if (0x1a < bVar1) {
    bVar1 = 0x1a;
  }
  *pbVar2 = bVar1;
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x506f;
  if (bVar1 == 0xff) {
    bVar1 = 0;
  }
  pbVar2[1] = bVar1;
  pbVar2[2] = 3;
  bVar1 = (*pcRam0000011a)();
  pbVar2[3] = *(byte *)(ulong)((bVar1 & 3) + 0x3863);
  pbVar2[4] = 0xff;
  return;
}



// Address: 0000:0e7a

void __cdecl16near FUN_0000_0e7a(void)

{
  byte bVar1;
  byte bVar2;
  undefined2 unaff_DS;
  
  bVar1 = 0x12 - *(char *)0x506d;
  if (*(char *)0xff43 == '\0') {
    if ((byte)(*(char *)0x84 - 2U) == bVar1) {
      FUN_0000_11b2();
    }
    return;
  }
  bVar2 = *(char *)0x84 - 5;
  if (bVar1 < bVar2) {
    return;
  }
  if (bVar1 == bVar2) {
    FUN_0000_0fa4();
    FUN_0000_11b2();
    return;
  }
  if ((byte)(*(char *)0x84 + 5U) != bVar1) {
    return;
  }
  FUN_0000_106d();
  return;
}



// Address: 0000:0fa4

void __cdecl16near FUN_0000_0fa4(void)

{
  undefined2 unaff_DS;
  
  if (*(char *)0xff44 == '\0') {
    return;
  }
  FUN_0000_0ff1();
  *(undefined1 *)0xff44 = 0;
  return;
}



// Address: 0000:0fbf

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 __cdecl16near FUN_0000_0fbf(void)

{
  undefined1 *puVar1;
  int iVar2;
  undefined1 *puVar3;
  undefined1 *puVar4;
  
  puVar4 = (undefined1 *)0x3f20;
  out(0x3c4,0x702);
  out(0x3ce,0x105);
  iVar2 = 0x20;
  puVar3 = _DAT_0000_5072;
  do {
    *puVar4 = *puVar3;
    puVar4[1] = puVar3[1];
    puVar4[2] = puVar3[2];
    puVar4[3] = puVar3[3];
    puVar4[4] = puVar3[4];
    puVar4[5] = puVar3[5];
    puVar1 = puVar4 + 7;
    puVar4[6] = puVar3[6];
    puVar4 = puVar4 + 8;
    *puVar1 = puVar3[7];
    puVar3 = puVar3 + 0x50;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  out(0x3ce,5);
  return 0x3ce0005;
}



// Address: 0000:0ff1

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 __cdecl16near FUN_0000_0ff1(void)

{
  undefined1 *puVar1;
  int iVar2;
  undefined1 *puVar3;
  undefined1 *puVar4;
  
  puVar3 = (undefined1 *)0x3f20;
  out(0x3c4,0x702);
  out(0x3ce,0x105);
  iVar2 = 0x20;
  puVar4 = _DAT_0000_5072;
  do {
    *puVar4 = *puVar3;
    puVar4[1] = puVar3[1];
    puVar4[2] = puVar3[2];
    puVar4[3] = puVar3[3];
    puVar4[4] = puVar3[4];
    puVar4[5] = puVar3[5];
    puVar1 = puVar3 + 7;
    puVar4[6] = puVar3[6];
    puVar3 = puVar3 + 8;
    puVar4[7] = *puVar1;
    puVar4 = puVar4 + 0x50;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  out(0x3ce,5);
  return 0x3ce0005;
}



// Address: 0000:1023

void __cdecl16near FUN_0000_1023(void)

{
  int iVar1;
  int iVar2;
  byte *pbVar3;
  byte *pbVar4;
  undefined2 unaff_DS;
  
  pbVar3 = (byte *)((uint)(*(char *)0x84 + *(char *)0x5076 & 0x3f) * 0x24 +
                    (uint)(byte)(*(char *)0x83 + *(char *)0x5077 + 4) + *(int *)0xff31);
  FUN_0000_16a9();
  iVar1 = 4;
  do {
    iVar2 = 4;
    do {
      pbVar4 = pbVar3;
      *(undefined2 *)((uint)(*pbVar4 & 0x7f) * 2 + 0x5097) = 0;
      iVar2 = iVar2 + -1;
      pbVar3 = pbVar4 + 1;
    } while (iVar2 != 0);
    pbVar3 = pbVar4 + 0x21;
    FUN_0000_16a9();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:106d

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 __cdecl16near FUN_0000_106d(void)

{
  byte *pbVar1;
  undefined2 uVar2;
  undefined1 uVar3;
  undefined2 uVar4;
  undefined2 in_AX;
  int iVar5;
  int iVar6;
  undefined2 in_DX;
  int iVar7;
  byte *pbVar8;
  undefined2 *puVar9;
  undefined1 *puVar10;
  undefined2 unaff_DS;
  
  if (*(char *)0xff43 != '\0') {
    *(undefined1 *)0xff44 = 0xff;
    FUN_0000_1023();
    FUN_0000_0fbf();
    uVar4 = _DAT_0000_ff2c;
    DAT_0000_5071 = *(undefined1 *)((byte)(cRam00000092 - 1) + 0x4199);
    out(0x3c4,0x702);
    out(0x3ce,0x205);
    out(0x3ce,8);
    iVar5 = 4;
    pbVar8 = _DAT_0000_5074;
    puVar10 = _DAT_0000_5072;
    do {
      iVar6 = 4;
      do {
        uVar3 = DAT_0000_5071;
        pbVar1 = pbVar8;
        pbVar8 = pbVar8 + 1;
        iVar7 = 0x280;
        if (*pbVar1 != 0xff) {
          puVar9 = (undefined2 *)((uint)*pbVar1 * 0x10 + *(int *)0xb000);
          iVar7 = 0x50;
          uVar2 = *puVar9;
          out(0x3cf,(char)uVar2);
          LOCK();
          *puVar10 = DAT_0000_5071;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[1] = uVar3;
          UNLOCK();
          uVar2 = puVar9[1];
          out(0x3cf,(char)uVar2);
          LOCK();
          puVar10[0x50] = uVar3;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[0x51] = uVar3;
          UNLOCK();
          uVar2 = puVar9[2];
          out(0x3cf,(char)uVar2);
          LOCK();
          puVar10[0xa0] = uVar3;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[0xa1] = uVar3;
          UNLOCK();
          uVar2 = puVar9[3];
          out(0x3cf,(char)uVar2);
          LOCK();
          puVar10[0xf0] = uVar3;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[0xf1] = uVar3;
          UNLOCK();
          uVar2 = puVar9[4];
          out(0x3cf,(char)uVar2);
          LOCK();
          puVar10[0x140] = uVar3;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[0x141] = uVar3;
          UNLOCK();
          uVar2 = puVar9[5];
          out(0x3cf,(char)uVar2);
          LOCK();
          puVar10[400] = uVar3;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[0x191] = uVar3;
          UNLOCK();
          uVar2 = puVar9[6];
          out(0x3cf,(char)uVar2);
          LOCK();
          puVar10[0x1e0] = uVar3;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[0x1e1] = uVar3;
          UNLOCK();
          uVar2 = puVar9[7];
          out(0x3cf,(char)uVar2);
          LOCK();
          puVar10[0x230] = uVar3;
          UNLOCK();
          out(0x3cf,(char)((uint)uVar2 >> 8));
          LOCK();
          puVar10[0x231] = uVar3;
          UNLOCK();
          puVar10 = puVar10 + 0x230;
        }
        puVar10 = puVar10 + iVar7;
        iVar6 = iVar6 + -1;
      } while (iVar6 != 0);
      puVar10 = puVar10 + -0x9fe;
      iVar5 = iVar5 + -1;
    } while (iVar5 != 0);
    out(0x3ce,5);
    out(0x3ce,0xff08);
    return 0x3ceff08;
  }
  return CONCAT22(in_DX,in_AX);
}



// Address: 0000:11b2

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_11b2(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  undefined2 unaff_DS;
  int iVar4;
  
  if (*(char *)0xff37 != '\0') {
    return;
  }
  *(undefined1 *)0xff37 = 0xff;
  iVar1 = 3;
  iVar3 = _DAT_0000_506b;
  do {
    iVar2 = 3;
    do {
      iVar4 = iVar3;
      FUN_0000_0730(iVar3);
      iVar3 = iVar4 + 2;
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    iVar3 = iVar4 + 0x27c;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:16a9

void __cdecl16near FUN_0000_16a9(void)

{
  uint unaff_SI;
  
  if (unaff_SI < 0xe900) {
    return;
  }
  return;
}



// Address: 0000:16b5

void __cdecl16near FUN_0000_16b5(void)

{
  uint unaff_SI;
  
  if (0xdfff < unaff_SI) {
    return;
  }
  return;
}



