/* Decompiled from chunk_10.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0071

void FUN_0000_0071(void)

{
  byte in_AL;
  
                    /* WARNING: Could not recover jumptable at 0x00000077. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)in_AL * 2 + -0x5f88))();
  return;
}



// Address: 0000:0118

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0118(void)

{
  int iVar1;
  int iVar2;
  char cVar3;
  undefined2 uVar4;
  char cVar5;
  undefined2 unaff_DS;
  
  uVar4 = 0xe17;
  iVar1 = 8;
  do {
    iVar2 = 0xc;
    do {
      (*_DAT_0000_3016)(uVar4);
      cVar5 = (char)((uint)uVar4 >> 8);
      cVar3 = (char)uVar4;
      uVar4 = CONCAT11(cVar5 + '\x01',cVar3);
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar4 = CONCAT11(cVar5 + -0xb,cVar3 + '\b');
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  if (*"" == '\0') {
    return;
  }
  uVar4 = 0x1117;
  iVar1 = 7;
  do {
    iVar2 = 6;
    do {
      (*_DAT_0000_3016)(uVar4);
      cVar5 = (char)((uint)uVar4 >> 8);
      cVar3 = (char)uVar4;
      uVar4 = CONCAT11(cVar5 + '\x01',cVar3);
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar4 = CONCAT11(cVar5 + -5,cVar3 + '\b');
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:03ec

void __cdecl16near FUN_0000_03ec(void)

{
  undefined2 unaff_DS;
  
  if (*(char *)0x5 == '\0' && *(char *)0x6 == '\0') {
    return;
  }
  if (*(char *)0x6 == '\0') {
    return;
  }
  if (*"" == '\0') {
    return;
  }
  return;
}



