/* Decompiled from chunk_06.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0128

void __cdecl16near FUN_0000_0128(void)

{
  char *pcVar1;
  char cVar2;
  char cVar3;
  byte bVar4;
  undefined2 in_BX;
  int unaff_SI;
  int unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  cVar3 = *(char *)(unaff_SI + -1);
  if (cVar3 < '\0') {
    FUN_0000_046c();
    return;
  }
  if (*(char *)(unaff_DI + -1) == -4) {
    *(undefined1 *)(unaff_DI + -1) = 0xff;
  }
  else {
    pcVar1 = (char *)(unaff_DI + -1);
    *pcVar1 = *pcVar1 + '\x01';
    cVar2 = *pcVar1;
    *(undefined1 *)(unaff_DI + -1) = 0xfe;
    if (cVar2 != '\0') {
      *(char *)(unaff_DI + -1) = cVar3;
      FUN_0000_0276();
    }
  }
  bVar4 = *(byte *)0xc012 - 5;
  if (*(byte *)0xc012 < 5) {
    return;
  }
  if (3 < bVar4) {
    return;
  }
  (*(code *)*(undefined2 *)((uint)bVar4 * 2 + 0x3176))(in_BX);
  return;
}



// Address: 0000:0276

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0276(void)

{
  uint *puVar1;
  uint uVar2;
  uint uVar3;
  undefined2 uVar4;
  byte in_AL;
  uint *puVar5;
  int iVar6;
  int iVar7;
  int in_DX;
  undefined2 *puVar8;
  byte *pbVar9;
  byte *pbVar10;
  undefined2 unaff_DS;
  
  pbVar10 = (byte *)(in_DX * 2);
  if (in_AL == 0) {
    iVar7 = 8;
    do {
      pbVar10[0] = 0;
      pbVar10[1] = 0;
      (pbVar10 + 2)[0] = 0;
      (pbVar10 + 2)[1] = 0;
      (pbVar10 + 4)[0] = 0;
      (pbVar10 + 4)[1] = 0;
      (pbVar10 + 6)[0] = 0;
      (pbVar10 + 6)[1] = 0;
      pbVar10 = pbVar10 + 0x140;
      iVar7 = iVar7 + -1;
    } while (iVar7 != 0);
    return;
  }
  iVar7 = (uint)in_AL * 2;
  if (*(int *)(iVar7 + 0x501d) == 0) {
    *(undefined2 *)(iVar7 + 0x501d) = pbVar10;
    uVar4 = _DAT_0000_ff2c;
    puVar5 = (uint *)((uint)(byte)(in_AL - 1) * 0x30 + -0x7fd0);
    iVar7 = 8;
    do {
      iVar6 = 2;
      do {
        pbVar9 = pbVar10;
        puVar1 = puVar5 + 1;
        uVar2 = *puVar5;
        puVar5 = (uint *)((int)puVar5 + 3);
        uVar3 = *puVar1;
        *pbVar9 = (byte)(uVar2 >> 10);
        pbVar9[1] = ((byte)(uVar2 >> 3) & 0x7f) >> 1;
        pbVar9[2] = (byte)((uint)(CONCAT11((char)uVar2,(byte)uVar3) * 4) >> 8) & 0x3f;
        pbVar9[3] = (byte)uVar3 & 0x3f;
        iVar6 = iVar6 + -1;
        pbVar10 = pbVar9 + 4;
      } while (iVar6 != 0);
      pbVar10 = pbVar9 + 0x13c;
      iVar7 = iVar7 + -1;
    } while (iVar7 != 0);
    return;
  }
  puVar8 = (undefined2 *)*(undefined2 *)(iVar7 + 0x501d);
  iVar7 = 8;
  do {
    *(undefined2 *)pbVar10 = *puVar8;
    *(undefined2 *)(pbVar10 + 2) = puVar8[1];
    *(undefined2 *)(pbVar10 + 4) = puVar8[2];
    *(undefined2 *)(pbVar10 + 6) = puVar8[3];
    pbVar10 = pbVar10 + 0x140;
    puVar8 = puVar8 + 0xa0;
    iVar7 = iVar7 + -1;
  } while (iVar7 != 0);
  return;
}



// Address: 0000:032a

void __cdecl16near FUN_0000_032a(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe900 == -1) {
    return;
  }
  if (*(char *)0xe900 == -4) {
    return;
  }
  *(undefined1 *)0xe900 = 0xff;
  FUN_0000_1504();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x25));
  if (*(char *)(unaff_SI + 0x25) < '\0') {
    uVar1 = FUN_0000_06d5();
  }
  FUN_0000_06dc(uVar1);
  FUN_0000_059d();
  return;
}



// Address: 0000:0367

void __cdecl16near FUN_0000_0367(void)

{
  undefined1 uVar1;
  int in_BX;
  int unaff_SI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined1 *)(in_BX + -0x1700);
  *(undefined1 *)(in_BX + -0x1700) = 0xff;
  UNLOCK();
  *(undefined1 *)0x5010 = uVar1;
  *(undefined1 *)0x5011 = 0;
  *(undefined1 *)(in_BX + -0x16ff) = 0xff;
  FUN_0000_1504();
  *(undefined2 *)0x5014 = *(undefined2 *)(unaff_SI + 0x24);
  FUN_0000_06dc();
  thunk_FUN_0000_0572();
  return;
}



// Address: 0000:03af

void __cdecl16near FUN_0000_03af(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe91b == -1) {
    return;
  }
  if (*(char *)0xe91b == -4) {
    return;
  }
  *(undefined1 *)0xe91b = 0xff;
  FUN_0000_1504();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x24));
  if (*(char *)(unaff_SI + 0x24) < '\0') {
    uVar1 = FUN_0000_06d5();
  }
  FUN_0000_06dc(uVar1);
  FUN_0000_059d();
  return;
}



// Address: 0000:03e7

void __cdecl16near FUN_0000_03e7(void)

{
  undefined1 uVar1;
  int extraout_DX;
  int in_BX;
  int unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *unaff_DI;
  *unaff_DI = 0xff;
  UNLOCK();
  *(undefined1 *)0x5010 = uVar1;
  LOCK();
  uVar1 = unaff_DI[0x1c];
  unaff_DI[0x1c] = 0xff;
  UNLOCK();
  *(undefined1 *)0x5011 = uVar1;
  FUN_0000_1504();
  FUN_0000_06dc();
  if ((*(char *)0x5010 != -1) && (*(char *)0x5010 != -4)) {
    if ((char)extraout_DX < '\0') {
      FUN_0000_06d5(in_BX * 8 + *(int *)0x4feb,unaff_SI + 0x25);
    }
    FUN_0000_059d();
  }
  if (((*(char *)0x4ff1 != '\x01') && (*(char *)0x5011 != -1)) && (*(char *)0x5011 != -4)) {
    if (extraout_DX < 0) {
      FUN_0000_06d5();
    }
    FUN_0000_059d();
  }
  return;
}



// Address: 0000:046c

void __cdecl16near FUN_0000_046c(void)

{
  undefined2 uVar1;
  undefined1 uVar2;
  undefined1 in_BL;
  int iVar3;
  undefined1 *unaff_SI;
  int unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + -1);
  *(undefined2 *)(unaff_DI + -1) = 0xfffe;
  UNLOCK();
  *(undefined2 *)0x5010 = uVar1;
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + 0x1b);
  *(undefined2 *)(unaff_DI + 0x1b) = 0xffff;
  UNLOCK();
  *(undefined2 *)0x5012 = uVar1;
  iVar3 = 0x5014;
  *(undefined1 *)0x5015 = *unaff_SI;
  FUN_0000_1504();
  *(undefined2 *)(iVar3 + 2) = *(undefined2 *)(unaff_SI + 0x23);
  *(undefined1 *)&DAT_0000_4ff2 = in_BL;
  *(char *)0x4ff3 = '\x12' - *(char *)0x4ff1;
  uVar2 = FUN_0000_06dc();
  *(undefined1 *)0x5014 = uVar2;
  thunk_FUN_0000_0572();
  if (*(char *)0x4ff1 != '\x01') {
    thunk_FUN_0000_0572();
    if ((*(char *)0xff34 != '\0') && (*(char *)0xff2f != '\0')) {
      FUN_0000_072d();
    }
  }
  return;
}



// Address: 0000:04e7

void __cdecl16near FUN_0000_04e7(void)

{
  char *pcVar1;
  char *pcVar2;
  char cVar3;
  int iVar4;
  char extraout_DL;
  int in_BX;
  char *pcVar5;
  char *unaff_SI;
  char *pcVar6;
  char *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  LOCK();
  cVar3 = unaff_DI[-1];
  unaff_DI[-1] = -2;
  UNLOCK();
  *(char *)0x5010 = cVar3;
  LOCK();
  cVar3 = unaff_DI[0x1b];
  unaff_DI[0x1b] = -1;
  UNLOCK();
  *(char *)0x5011 = cVar3;
  FUN_0000_1504();
  cVar3 = FUN_0000_06dc();
  if ((*(char *)0x5010 != -1) && (*(char *)0x5010 != -4)) {
    if (cVar3 < '\0') {
      FUN_0000_06d5(in_BX * 8 + *(int *)0x4feb,unaff_SI + 0x24);
    }
    FUN_0000_059d();
  }
  if (((*(char *)0x4ff1 != '\x01') && (*(char *)0x5011 != -1)) && (*(char *)0x5011 != -4)) {
    if (extraout_DL < '\0') {
      FUN_0000_06d5();
    }
    FUN_0000_059d();
  }
  while( true ) {
    FUN_0000_1504();
    *(int *)0x4feb = *(int *)0x4feb + 0xa00;
    pcVar1 = (char *)0x4ff1;
    *pcVar1 = *pcVar1 + -1;
    if (*pcVar1 == '\0') {
      return;
    }
    FUN_0000_0dff();
    if (unaff_SI[7] < '\0') {
      FUN_0000_03e7();
    }
    iVar4 = 6;
    pcVar2 = unaff_SI + 8;
    do {
      pcVar6 = unaff_DI;
      pcVar5 = pcVar2;
      if (*pcVar5 != *pcVar6) {
        FUN_0000_0128();
      }
      if (pcVar5[1] != pcVar6[1]) {
        FUN_0000_0128();
      }
      if (pcVar5[2] != pcVar6[2]) {
        FUN_0000_0128();
      }
      if (pcVar5[3] != pcVar6[3]) {
        FUN_0000_0128();
      }
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar5 + 4;
      unaff_DI = pcVar6 + 4;
    } while (iVar4 != 0);
    if (pcVar5[4] != pcVar6[4]) {
      FUN_0000_0128();
    }
    if (pcVar5[5] != pcVar6[5]) {
      FUN_0000_0128();
    }
    if (pcVar5[6] != pcVar6[6]) {
      FUN_0000_0128();
    }
    unaff_SI = pcVar5 + 8;
    unaff_DI = pcVar6 + 8;
    if (pcVar5[7] < '\0') break;
    if (pcVar5[7] != pcVar6[7]) {
      FUN_0000_0128();
    }
  }
  FUN_0000_04e7();
  return;
}



// Address: 0000:056f

void __cdecl16near thunk_FUN_0000_0572(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_06d5(0x572);
      in_DX = extraout_DX;
    }
    FUN_0000_059d(in_DX);
  }
  return;
}



// Address: 0000:0572

void __cdecl16near FUN_0000_0572(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_06d5();
      in_DX = extraout_DX;
    }
    FUN_0000_059d(in_DX);
  }
  return;
}



// Address: 0000:059d

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_059d(void)

{
  char in_AL;
  byte bVar1;
  undefined2 unaff_DS;
  
  bVar1 = *(byte *)0x4ff4;
  if ((in_AL != '\0') && (-1 < in_AL)) {
    bVar1 = bVar1 | 0x80;
  }
  _DAT_0000_4fe9 = *(undefined2 *)((uint)(bVar1 & 0x7f) * 2 + 0x4f8c);
  if (-1 < (char)bVar1) {
    FUN_0000_0655();
    FUN_0000_068e();
    return;
  }
  FUN_0000_0614();
  FUN_0000_068e();
  return;
}



// Address: 0000:0614

void __cdecl16near FUN_0000_0614(void)

{
  int iVar1;
  
  FUN_0000_069c();
  iVar1 = 8;
  do {
    FUN_0000_063f();
    FUN_0000_063f();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:063f

void __cdecl16near FUN_0000_063f(void)

{
  int iVar1;
  byte extraout_DH;
  byte in_BL;
  byte *unaff_DI;
  undefined2 unaff_ES;
  
  iVar1 = 4;
  do {
    FUN_0000_0672();
    in_BL = in_BL | extraout_DH;
    *unaff_DI = in_BL;
    unaff_DI = unaff_DI + 1;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0655

void __cdecl16near FUN_0000_0655(void)

{
  int iVar1;
  
  iVar1 = 8;
  do {
    FUN_0000_0665();
    FUN_0000_0665();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0665

void __cdecl16near FUN_0000_0665(void)

{
  int iVar1;
  undefined1 in_BL;
  undefined1 *unaff_DI;
  undefined2 unaff_ES;
  
  iVar1 = 4;
  do {
    FUN_0000_0672();
    *unaff_DI = in_BL;
    unaff_DI = unaff_DI + 1;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0672

int __cdecl16near FUN_0000_0672(void)

{
  int in_AX;
  
  return in_AX * 0x10;
}



// Address: 0000:068e

void __cdecl16near FUN_0000_068e(void)

{
  undefined2 *puVar1;
  int iVar2;
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  iVar2 = 8;
  do {
    *unaff_DI = *unaff_SI;
    unaff_DI[1] = unaff_SI[1];
    puVar1 = unaff_SI + 3;
    unaff_DI[2] = unaff_SI[2];
    unaff_SI = unaff_SI + 4;
    unaff_DI[3] = *puVar1;
    unaff_DI = unaff_DI + 0xa0;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:069c

void __cdecl16near FUN_0000_069c(void)

{
  uint *puVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  uint *unaff_SI;
  byte *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  iVar4 = 0x10;
  do {
    puVar1 = unaff_SI + 1;
    uVar2 = *unaff_SI;
    unaff_SI = (uint *)((int)unaff_SI + 3);
    uVar3 = *puVar1;
    *unaff_DI = (byte)(uVar2 >> 10);
    unaff_DI[1] = ((byte)(uVar2 >> 3) & 0x7f) >> 1;
    unaff_DI[2] = (byte)((uint)(CONCAT11((char)uVar2,(byte)uVar3) * 4) >> 8) & 0x3f;
    unaff_DI[3] = (byte)uVar3 & 0x3f;
    unaff_DI = unaff_DI + 4;
    iVar4 = iVar4 + -1;
  } while (iVar4 != 0);
  return;
}



// Address: 0000:06cd

void __cdecl16near FUN_0000_06cd(void)

{
  undefined2 *puVar1;
  int iVar2;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  
  for (iVar2 = 0x20; iVar2 != 0; iVar2 = iVar2 + -1) {
    puVar1 = unaff_DI;
    unaff_DI = unaff_DI + 1;
    *puVar1 = 0;
  }
  return;
}



// Address: 0000:06d5

undefined1 __cdecl16near FUN_0000_06d5(void)

{
  byte in_AL;
  
  return *(undefined1 *)(ulong)((in_AL & 0x7f) + 0xed20);
}



// Address: 0000:06dc

undefined2 __cdecl16near FUN_0000_06dc(void)

{
  undefined1 uVar1;
  byte in_AL;
  char cVar2;
  int iVar3;
  char *pcVar4;
  int iVar5;
  undefined2 unaff_DS;
  
  uVar1 = *(undefined1 *)((in_AL & 0x7f) + 0xed20);
  iVar3 = (uint)(in_AL & 0x7f) * 0x10 + *(int *)0xc010;
  iVar5 = -0x5f90;
  if ((*(byte *)(iVar3 + 5) & 0x80) == 0) {
    iVar5 = -0x5fd0;
  }
  pcVar4 = (char *)((uint)(*(byte *)(iVar3 + 6) & 0xf) * 5 +
                   *(int *)((uint)(byte)((*(byte *)(iVar3 + 4) & 0x1f) * '\x02') + iVar5));
  cVar2 = *pcVar4;
  if ((*(char *)0xff34 == '\0') && ((*(byte *)(iVar3 + 5) & 0x20) != 0)) {
    cVar2 = cVar2 + '\x03';
  }
  *(char *)0x4ff4 = cVar2;
  return CONCAT11((char)((uint)pcVar4 >> 8),uVar1);
}



// Address: 0000:072d

void __cdecl16near FUN_0000_072d(void)

{
  byte bVar1;
  byte *pbVar2;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  if (0xf < *(byte *)0x4ff3) {
    return;
  }
  bVar1 = (*pcRam0000011a)();
  if ((bVar1 & 0xf) < 0xe) {
    return;
  }
  bVar1 = 0;
  for (pbVar2 = (byte *)0xeda0; *pbVar2 != 0xff; pbVar2 = pbVar2 + 4) {
    bVar1 = bVar1 + 1;
  }
  if (0x1f < bVar1) {
    return;
  }
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)&DAT_0000_4ff2;
  if (bVar1 == 0xff) {
    bVar1 = 4;
  }
  if (0x1a < bVar1) {
    bVar1 = 0x1a;
  }
  *pbVar2 = bVar1;
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x4ff3;
  if (bVar1 == 0xff) {
    bVar1 = 0;
  }
  pbVar2[1] = bVar1;
  pbVar2[2] = 3;
  bVar1 = (*pcRam0000011a)();
  pbVar2[3] = bVar1 & 3;
  pbVar2[4] = 0xff;
  return;
}



// Address: 0000:0dff

void __cdecl16near FUN_0000_0dff(void)

{
  byte bVar1;
  byte bVar2;
  undefined2 unaff_DS;
  
  bVar1 = 0x12 - *(char *)0x4ff1;
  if (*(char *)0xff43 == '\0') {
    if ((byte)(*(char *)0x84 - 2U) == bVar1) {
      FUN_0000_10f4();
    }
    return;
  }
  bVar2 = *(char *)0x84 - 5;
  if (bVar1 < bVar2) {
    return;
  }
  if (bVar1 == bVar2) {
    FUN_0000_0f2d();
    FUN_0000_10f4();
    return;
  }
  if ((byte)(*(char *)0x84 + 5U) != bVar1) {
    return;
  }
  FUN_0000_0fd4();
  return;
}



// Address: 0000:0f2d

void __cdecl16near FUN_0000_0f2d(void)

{
  undefined2 unaff_DS;
  
  if (*(char *)0xff44 == '\0') {
    return;
  }
  FUN_0000_0f68();
  *(undefined1 *)0xff44 = 0;
  return;
}



// Address: 0000:0f46

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0f46(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  int iVar3;
  int iVar4;
  undefined2 *puVar5;
  undefined2 *puVar6;
  
  puVar6 = (undefined2 *)0xfa40;
  iVar3 = 0x20;
  puVar5 = _DAT_0000_4ff7;
  do {
    for (iVar4 = 0x10; iVar4 != 0; iVar4 = iVar4 + -1) {
      puVar2 = puVar6;
      puVar6 = puVar6 + 1;
      puVar1 = puVar5;
      puVar5 = puVar5 + 1;
      *puVar2 = *puVar1;
    }
    puVar5 = puVar5 + 0x90;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:0f68

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0f68(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  int iVar3;
  int iVar4;
  undefined2 *puVar5;
  undefined2 *puVar6;
  
  puVar5 = (undefined2 *)0xfa40;
  iVar3 = 0x20;
  puVar6 = _DAT_0000_4ff7;
  do {
    for (iVar4 = 0x10; iVar4 != 0; iVar4 = iVar4 + -1) {
      puVar2 = puVar6;
      puVar6 = puVar6 + 1;
      puVar1 = puVar5;
      puVar5 = puVar5 + 1;
      *puVar2 = *puVar1;
    }
    puVar6 = puVar6 + 0x90;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:0f8a

void __cdecl16near FUN_0000_0f8a(void)

{
  int iVar1;
  int iVar2;
  byte *pbVar3;
  byte *pbVar4;
  undefined2 unaff_DS;
  
  pbVar3 = (byte *)((uint)(*(char *)0x84 + *(char *)0x4ffb & 0x3f) * 0x24 +
                    (uint)(byte)(*(char *)0x83 + *(char *)0x4ffc + 4) + *(int *)0xff31);
  FUN_0000_1504();
  iVar1 = 4;
  do {
    iVar2 = 4;
    do {
      pbVar4 = pbVar3;
      *(undefined2 *)((uint)(*pbVar4 & 0x7f) * 2 + 0x501d) = 0;
      iVar2 = iVar2 + -1;
      pbVar3 = pbVar4 + 1;
    } while (iVar2 != 0);
    pbVar3 = pbVar4 + 0x21;
    FUN_0000_1504();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:0fd4

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0fd4(void)

{
  char *pcVar1;
  undefined2 uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  uint extraout_DX;
  uint extraout_DX_00;
  uint extraout_DX_01;
  uint extraout_DX_02;
  uint unaff_BP;
  char *pcVar6;
  uint *puVar7;
  uint *puVar8;
  undefined2 unaff_DS;
  
  if (*(char *)0xff43 != '\0') {
    *(undefined1 *)0xff44 = 0xff;
    FUN_0000_0f8a();
    FUN_0000_0f46();
    uVar2 = _DAT_0000_ff2c;
    _DAT_0000_4ff5 = *(undefined2 *)((uint)(byte)(cRam00000092 - 1) * 2 + 0x4086);
    iVar3 = 4;
    pcVar6 = _DAT_0000_4ff9;
    puVar7 = _DAT_0000_4ff7;
    do {
      iVar4 = 4;
      puVar8 = puVar7;
      do {
        pcVar1 = pcVar6;
        pcVar6 = pcVar6 + 1;
        if (*pcVar1 == -1) {
          puVar8 = puVar8 + 0x500;
        }
        else {
          iVar5 = 8;
          do {
            FUN_0000_1096();
            *puVar8 = *puVar8 & ~unaff_BP;
            *puVar8 = *puVar8 | extraout_DX;
            FUN_0000_1096();
            puVar8[1] = puVar8[1] & unaff_BP;
            puVar8[1] = puVar8[1] | extraout_DX_00;
            FUN_0000_1096();
            puVar8[2] = puVar8[2] & ~unaff_BP;
            puVar8[2] = puVar8[2] | extraout_DX_01;
            FUN_0000_1096();
            puVar8[3] = puVar8[3] & unaff_BP;
            puVar8[3] = puVar8[3] | extraout_DX_02;
            puVar8 = puVar8 + 0xa0;
            iVar5 = iVar5 + -1;
          } while (iVar5 != 0);
        }
        iVar4 = iVar4 + -1;
      } while (iVar4 != 0);
      puVar7 = puVar7 + 4;
      iVar3 = iVar3 + -1;
    } while (iVar3 != 0);
    return;
  }
  return;
}



// Address: 0000:1096

undefined4 __cdecl16near FUN_0000_1096(void)

{
  int iVar1;
  uint in_AX;
  uint uVar2;
  char cVar3;
  
  uVar2 = 0;
  cVar3 = CARRY2(in_AX,in_AX) * '\x02' + CARRY2(in_AX * 2,in_AX * 2);
  if ((cVar3 != '\0') && (uVar2 = (uint)DAT_0000_4ff6, cVar3 != '\x03')) {
    uVar2 = (uint)DAT_0000_4ff5;
  }
  iVar1 = in_AX * 0x10;
  cVar3 = CARRY2(in_AX * 4,in_AX * 4) * '\x02' + CARRY2(in_AX * 8,in_AX * 8);
  if (cVar3 == '\0') {
    return CONCAT22(uVar2,iVar1);
  }
  if (cVar3 == '\x03') {
    return CONCAT22(CONCAT11(DAT_0000_4ff6,(char)uVar2),iVar1);
  }
  return CONCAT22(CONCAT11(DAT_0000_4ff5,(char)uVar2),iVar1);
}



// Address: 0000:10f4

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_10f4(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  undefined2 unaff_DS;
  int iVar4;
  
  if (*(char *)0xff37 != '\0') {
    return;
  }
  *(undefined1 *)0xff37 = 0xff;
  iVar1 = 3;
  iVar3 = _DAT_0000_4fed;
  do {
    iVar2 = 3;
    do {
      iVar4 = iVar3;
      FUN_0000_068e(iVar3);
      iVar3 = iVar4 + 8;
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    iVar3 = iVar4 + 0x9f0;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:1504

void __cdecl16near FUN_0000_1504(void)

{
  uint unaff_SI;
  
  if (unaff_SI < 0xe900) {
    return;
  }
  return;
}



// Address: 0000:1510

void __cdecl16near FUN_0000_1510(void)

{
  uint unaff_SI;
  
  if (0xdfff < unaff_SI) {
    return;
  }
  return;
}



