/* Decompiled from chunk_17.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:00a8

void FUN_0000_00a8(void)

{
  byte in_AL;
  
                    /* WARNING: Could not recover jumptable at 0x000000ae. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)in_AL * 2 + -0x5f51))();
  return;
}



// Address: 0000:0994

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0994(void)

{
  int iVar1;
  int iVar2;
  char cVar3;
  char cVar5;
  undefined2 uVar4;
  undefined2 unaff_DS;
  
  uVar4 = *(undefined2 *)0xbb12;
  iVar1 = 8;
  do {
    iVar2 = 0xc;
    do {
      (*_DAT_0000_3016)(uVar4);
      cVar5 = (char)((uint)uVar4 >> 8);
      cVar3 = (char)uVar4;
      uVar4 = CONCAT11(cVar5 + '\x01',cVar3);
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar4 = CONCAT11(cVar5 + -0xb,cVar3 + '\b');
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



