/* Decompiled from chunk_31.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:02ed

void __stdcall16far FUN_0000_02ed(void)

{
  return;
}



