/* Decompiled from chunk_00.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:040b

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_040b(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  char in_BL;
  undefined2 unaff_DS;
  char cVar4;
  
  iVar1 = (uint)*(byte *)0xe7 * 9 + -0x5bcb;
  iVar2 = 3;
  do {
    iVar3 = 3;
    do {
      cVar4 = in_BL;
      iVar1 = iVar1 + 1;
      (*_DAT_0000_3022)(cVar4,iVar1);
      iVar3 = iVar3 + -1;
      in_BL = cVar4 + '\b';
    } while (iVar3 != 0);
    in_BL = cVar4 + -0x10;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:0493

void __cdecl16near FUN_0000_0493(void)

{
  undefined2 unaff_DS;
  
  do {
  } while (*(byte *)0xff1a < (byte)(*(char *)0xff33 * '\x04'));
  *(undefined1 *)0xff1a = 0;
  return;
}



// Address: 0000:04a7

void __cdecl16near FUN_0000_04a7(void)

{
  char cVar1;
  undefined1 uVar2;
  undefined2 unaff_DS;
  
  *(undefined1 *)0xa59c = 0x94;
  *(undefined1 *)0xa59d = 0x50;
  uVar2 = 0;
  cVar1 = *(byte *)0xa59a - *(byte *)0xa59c;
  if (cVar1 != '\0') {
    if (*(byte *)0xa59a < *(byte *)0xa59c) {
      cVar1 = -cVar1;
      uVar2 = 0xff;
    }
    else {
      uVar2 = 1;
    }
  }
  *(char *)0xa5a0 = cVar1;
  *(undefined1 *)0xa59e = uVar2;
  uVar2 = 0;
  cVar1 = *(byte *)0xa59b - *(byte *)0xa59d;
  if (cVar1 != '\0') {
    if (*(byte *)0xa59b < *(byte *)0xa59d) {
      cVar1 = -cVar1;
      uVar2 = 0xff;
    }
    else {
      uVar2 = 1;
    }
  }
  *(char *)0xa5a1 = cVar1;
  *(undefined1 *)0xa59f = uVar2;
  *(byte *)0xa5a3 = *(byte *)0xa5a0 >> 1;
  *(undefined1 *)0xa5a2 = 0;
  if (*(byte *)0xa5a1 <= *(byte *)0xa5a0) {
    return;
  }
  *(byte *)0xa5a3 = *(byte *)0xa5a1 >> 1;
  *(undefined1 *)0xa5a2 = 0xff;
  return;
}



// Address: 0000:050e

void __cdecl16near FUN_0000_050e(void)

{
  char cVar1;
  undefined2 unaff_DS;
  
  if (*(char *)0xa5a2 != '\0') {
    cVar1 = *(byte *)0xa5a3 - *(byte *)0xa5a0;
    if (*(byte *)0xa5a3 < *(byte *)0xa5a0) {
      cVar1 = cVar1 + *(char *)0xa5a1;
      *(char *)0xa59c = *(char *)0xa59c + *(char *)0xa59e;
    }
    *(char *)0xa5a3 = cVar1;
    *(char *)0xa59d = *(char *)0xa59d + *(char *)0xa59f;
    if (*(char *)0xa59b == *(char *)0xa59d) {
      return;
    }
    return;
  }
  cVar1 = *(byte *)0xa5a3 - *(byte *)0xa5a1;
  if (*(byte *)0xa5a3 < *(byte *)0xa5a1) {
    cVar1 = cVar1 + *(char *)0xa5a0;
    *(char *)0xa59d = *(char *)0xa59d + *(char *)0xa59f;
  }
  *(char *)0xa5a3 = cVar1;
  *(char *)0xa59c = *(char *)0xa59c + *(char *)0xa59e;
  if (*(char *)0xa59a == *(char *)0xa59c) {
    return;
  }
  return;
}



