/* Decompiled from chunk_14.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:042d

void __cdecl16near FUN_0000_042d(void)

{
  uint uVar1;
  undefined2 unaff_DS;
  
  uVar1 = *(int *)&DAT_0000_a7a0 - 1;
  *(uint *)&DAT_0000_a7a0 = uVar1;
  if (uVar1 < 0xf) {
    return;
  }
  return;
}



// Address: 0000:043f

void __cdecl16near FUN_0000_043f(void)

{
  uint uVar1;
  undefined2 unaff_DS;
  
  uVar1 = *(int *)&DAT_0000_a7a0 + 1;
  if (0x32 < uVar1) {
    return;
  }
  *(uint *)&DAT_0000_a7a0 = uVar1;
  return;
}



// Address: 0000:0450

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0450(void)

{
  byte *pbVar1;
  undefined1 *puVar2;
  undefined2 *puVar3;
  byte bVar4;
  uint uVar5;
  char cVar6;
  int iVar7;
  int iVar8;
  byte *pbVar9;
  undefined1 *puVar10;
  int *piVar11;
  undefined2 *puVar12;
  undefined1 *puVar13;
  undefined1 *puVar14;
  char *pcVar15;
  byte *pbVar16;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  bool bVar17;
  
  puVar12 = (undefined2 *)0xa7c9;
  for (iVar7 = 0x28; iVar7 != 0; iVar7 = iVar7 + -1) {
    puVar3 = puVar12;
    puVar12 = puVar12 + 1;
    *puVar3 = 0xffff;
  }
  uVar5 = (uint)*(byte *)0xa7b9 * 2;
  puVar10 = (undefined1 *)*(int *)(uVar5 + 0xa6c8);
  pbVar9 = (byte *)*(undefined2 *)(uVar5 + 0xa744);
  puVar13 = (undefined1 *)0xa7cb;
  iVar7 = 8;
  do {
    iVar8 = 8;
    do {
      puVar14 = puVar13;
      pbVar1 = pbVar9;
      bVar4 = *pbVar1;
      *pbVar1 = *pbVar1 << 1 | (char)bVar4 < '\0';
      if ((char)bVar4 < '\0') {
        puVar2 = puVar10;
        puVar10 = puVar10 + 1;
        *puVar14 = *puVar2;
      }
      iVar8 = iVar8 + -1;
      puVar13 = puVar14 + 1;
    } while (iVar8 != 0);
    puVar13 = puVar14 + 3;
    pbVar9 = pbVar9 + 1;
    iVar7 = iVar7 + -1;
  } while (iVar7 != 0);
  cVar6 = *(char *)0xa7ba;
  pcVar15 = (char *)0xa7f1;
  if ((*(char *)0xa7b9 == '\x06') || (7 < *(byte *)0xa7b9)) {
    pcVar15 = (char *)0xa7f2;
  }
  *pcVar15 = cVar6 * '\x02';
  bVar17 = (char *)0xffec < pcVar15 + 1;
  pcVar15[0x14] = cVar6 * '\x02' + '\x01';
  *(undefined1 *)0xa7b6 = 0;
  iVar7 = *(int *)&DAT_0000_a7a0;
  piVar11 = (int *)*(undefined2 *)0xc010;
  pbVar9 = (byte *)0xa7c9;
  iVar8 = 8;
  do {
    (*_DAT_0000_6036)();
    *(undefined1 *)0xa7bc = (char)uVar5;
    if (!bVar17) {
      cVar6 = '\0';
      pbVar16 = pbVar9;
      do {
        if (*pbVar16 != 0xff) {
          *piVar11 = iVar7;
          *(byte *)(piVar11 + 1) = *(char *)0xa7a2 + cVar6 & 0x3f;
          *(undefined1 *)((int)piVar11 + 3) = *(undefined1 *)0xa7bc;
          bVar4 = *pbVar16;
          *(byte *)(piVar11 + 3) = bVar4;
          uVar5 = CONCAT11(bVar4,-CARRY1(bVar4,bVar4)) & 0xff60;
          *(byte *)(piVar11 + 2) = (byte)uVar5 | (byte)(uVar5 >> 0xc) & 7;
          *(undefined1 *)((int)piVar11 + 5) = 0;
          if (*(char *)0xa7b7 != '\0') {
            *(byte *)((int)piVar11 + 5) = *(byte *)((int)piVar11 + 5) | 0x20;
          }
          (*_DAT_0000_6028)();
          uVar5 = (uint)*(byte *)0xa7b6;
          LOCK();
          bVar4 = *pbVar16;
          *pbVar16 = *(byte *)0xa7b6 | 0x80;
          UNLOCK();
          *(byte *)(uVar5 + 0xed20) = bVar4;
          piVar11 = piVar11 + 8;
          *(char *)0xa7b6 = *(char *)0xa7b6 + '\x01';
        }
        pbVar16 = pbVar16 + 1;
        cVar6 = cVar6 + '\x01';
      } while (cVar6 != '\n');
    }
    iVar7 = iVar7 + 1;
    bVar17 = (byte *)0xfff5 < pbVar9;
    pbVar9 = pbVar9 + 10;
    iVar8 = iVar8 + -1;
  } while (iVar8 != 0);
  FUN_0000_05fe();
  *piVar11 = -1;
  if (*(char *)0xa7c2 == '\0') {
    return;
  }
  if (*(char *)0xa7c8 != '\0') {
    *(char *)0xa7c6 = *(char *)0xa7c6 + '\x01';
    if (5 < *(byte *)0xa7c6) {
      *(undefined1 *)0xa7c2 = 0;
      return;
    }
    return;
  }
  if (0x11 < *(byte *)0xa7c3) {
    bVar4 = *(byte *)0xa7c7;
    *(char *)0xa7c3 = *(char *)0xa7c3 + *(char *)((uint)bVar4 * 2 + -0x5a28);
    *(char *)0xa7c5 = *(char *)0xa7c5 + *(char *)((uint)bVar4 * 2 + -0x5a27);
    *(char *)0xa7c7 = *(char *)0xa7c7 + (*(byte *)0xa7c7 < 0x10);
    bVar4 = *(char *)0xa7c6 + 1;
    if (2 < bVar4) {
      bVar4 = 0;
    }
    *(byte *)0xa7c6 = bVar4;
    if (*(char *)0xa7c7 == '\t') {
      *(undefined1 *)0xff75 = 0x31;
    }
    if (*(char *)0xa7c7 == '\f') {
      *(undefined1 *)0xff75 = 0x31;
    }
    if (*(char *)0xa7c7 == '\x0f') {
      *(undefined1 *)0xff75 = 0x31;
    }
    return;
  }
  *(undefined1 *)0xa7c8 = 0xff;
  *(undefined1 *)0xa7c6 = 3;
  *(undefined1 *)0xff75 = 0x32;
  return;
}



// Address: 0000:05fe

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_05fe(void)

{
  byte bVar1;
  byte bVar2;
  undefined1 in_BL;
  undefined2 *unaff_SI;
  byte *unaff_DI;
  undefined2 unaff_DS;
  bool bVar3;
  undefined2 in_stack_00000000;
  
  bVar3 = false;
  if (*(char *)0xa7c2 == '\0') {
    return;
  }
  (*_DAT_0000_6036)(*(undefined2 *)0xa7c3);
  if (bVar3) {
    return;
  }
  *unaff_SI = in_stack_00000000;
  *(undefined1 *)(unaff_SI + 1) = *(undefined1 *)0xa7c5;
  *(undefined1 *)((int)unaff_SI + 3) = in_BL;
  *(undefined1 *)(unaff_SI + 2) = 0x26;
  *(undefined1 *)((int)unaff_SI + 5) = 0;
  *(undefined1 *)(unaff_SI + 3) = *(undefined1 *)0xa7c6;
  (*_DAT_0000_6028)();
  bVar2 = *(byte *)0xa7b6;
  LOCK();
  bVar1 = *unaff_DI;
  *unaff_DI = bVar2 | 0x80;
  UNLOCK();
  *(byte *)(bVar2 + 0xed20) = bVar1;
  return;
}



// Address: 0000:0648

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0648(void)

{
  int iVar1;
  uint in_BX;
  undefined2 unaff_DS;
  int in_stack_00000000;
  
  iVar1 = *(uint *)0xa7a3 - in_BX;
  if (*(uint *)0xa7a3 < in_BX) {
    iVar1 = 0;
  }
  *(int *)0xa7a3 = iVar1;
  (*_DAT_0000_200c)(iVar1);
  if (in_stack_00000000 != 0) {
    return;
  }
  *(undefined1 *)0xa7b8 = 0;
  *(undefined1 *)0xa7c2 = 0;
  *(undefined1 *)0xff2e = 0xff;
  return;
}



// Address: 0000:0672

void __cdecl16near FUN_0000_0672(void)

{
  byte bVar1;
  undefined1 uVar2;
  undefined2 unaff_DS;
  
  if (0x27 < *(byte *)0xa7b8) {
    *(undefined1 *)0xff30 = 0xff;
    return;
  }
  *(undefined1 *)0xff2f = 0xff;
  *(char *)0xa7b8 = *(char *)0xa7b8 + '\x01';
  if (*(byte *)0xa7b8 < 10) {
    bVar1 = *(byte *)(ulong)(*(byte *)0xa7b8 + 0xa69b);
    *(byte *)0xa7b9 = bVar1;
    if (2 < bVar1) {
      *(undefined1 *)0xff75 = 0x33;
    }
    *(char *)0xa7bb = *(char *)0xa7bb + '\x01';
    *(byte *)0xa7bb = *(byte *)0xa7bb & 3;
    *(undefined1 *)0xa7ba = *(undefined1 *)(ulong)(*(byte *)0xa7bb + 0xa41b);
    FUN_0000_0450();
    return;
  }
  uVar2 = 6;
  if (*(byte *)0xa7b8 < 6) {
    uVar2 = *(undefined1 *)(ulong)(*(byte *)0xa7b8 + 0xa6bc);
  }
  *(undefined1 *)0xa7ba = uVar2;
  FUN_0000_0450();
  return;
}



