/* Decompiled from chunk_16.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0063

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0063(void)

{
  undefined2 unaff_DS;
  
  FUN_0000_01ae();
  (*_DAT_0000_2000)();
  *(undefined1 *)0xa505 = 0xff;
  return;
}



// Address: 0000:0079

void FUN_0000_0079(void)

{
  byte in_AL;
  
                    /* WARNING: Could not recover jumptable at 0x0000007f. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)in_AL * 2 + -0x5f80))();
  return;
}



// Address: 0000:01ae

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_01ae(void)

{
  int iVar1;
  int iVar2;
  char cVar3;
  undefined2 uVar4;
  char cVar5;
  
  uVar4 = 0x717;
  iVar1 = 8;
  do {
    iVar2 = 0xc;
    do {
      (*_DAT_0000_3016)(uVar4);
      cVar5 = (char)((uint)uVar4 >> 8);
      cVar3 = (char)uVar4;
      uVar4 = CONCAT11(cVar5 + '\x01',cVar3);
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar4 = CONCAT11(cVar5 + -0xb,cVar3 + '\b');
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



