/* Decompiled from chunk_12.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:00ba

void __cdecl16near FUN_0000_00ba(void)

{
  char *pcVar1;
  int iVar2;
  byte bVar3;
  char cVar4;
  char *pcVar5;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  bool bVar6;
  
  bVar3 = *(byte *)((byte)(*(char *)0xc006 - 1) + 0xd2);
  pcVar5 = (char *)0xbc3b;
  cVar4 = '\0';
  iVar2 = 6;
  do {
    bVar6 = CARRY1(bVar3,bVar3);
    bVar3 = bVar3 * '\x02';
    if (bVar6) {
      pcVar1 = pcVar5;
      pcVar5 = pcVar5 + 1;
      *pcVar1 = '\x06' - (char)iVar2;
      cVar4 = cVar4 + '\x01';
    }
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  *(char *)0xbc31 = cVar4;
  return;
}



// Address: 0000:00e6

void __cdecl16near FUN_0000_00e6(void)

{
  char *pcVar1;
  int iVar2;
  byte bVar3;
  char cVar4;
  char *pcVar5;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  bool bVar6;
  
  bVar3 = *(byte *)((byte)(*(char *)0xc006 - 1) + 0xdb);
  pcVar5 = (char *)0xbc41;
  cVar4 = '\0';
  iVar2 = 6;
  do {
    bVar6 = CARRY1(bVar3,bVar3);
    bVar3 = bVar3 * '\x02';
    if (bVar6) {
      pcVar1 = pcVar5;
      pcVar5 = pcVar5 + 1;
      *pcVar1 = '\x06' - (char)iVar2;
      cVar4 = cVar4 + '\x01';
    }
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  *(char *)0xbc32 = cVar4;
  return;
}



// Address: 0000:0112

void FUN_0000_0112(void)

{
  byte in_AL;
  
                    /* WARNING: Could not recover jumptable at 0x00000118. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)in_AL * 2 + -0x5ee7))();
  return;
}



// Address: 0000:09d3

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_09d3(void)

{
  uint in_AX;
  char *pcVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  char cVar5;
  undefined2 uVar6;
  char cVar7;
  undefined2 unaff_DS;
  
  pcVar1 = (char *)((in_AX & 0xff) * 6 + -22000);
  uVar6 = 0x717;
  iVar2 = 2;
  do {
    if (*pcVar1 == '\0') {
      return;
    }
    iVar4 = CONCAT11((char)((uint)iVar2 >> 8),*pcVar1);
    pcVar1 = pcVar1 + 3;
    do {
      iVar3 = 0xc;
      do {
        (*_DAT_0000_3016)(uVar6);
        cVar7 = (char)((uint)uVar6 >> 8);
        cVar5 = (char)uVar6;
        uVar6 = CONCAT11(cVar7 + '\x01',cVar5);
        iVar3 = iVar3 + -1;
      } while (iVar3 != 0);
      uVar6 = CONCAT11(cVar7 + -0xb,cVar5 + '\b');
      iVar4 = iVar4 + -1;
    } while (iVar4 != 0);
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



