/* Decompiled from chunk_03.bin */
/* Generated by Ghidra */

// Failed to decompile: FUN_0000_0000
// Address: 0000:0000

// Address: 0000:0128

void __cdecl16near FUN_0000_0128(void)

{
  char *pcVar1;
  char cVar2;
  char cVar3;
  byte bVar4;
  undefined2 in_BX;
  int unaff_SI;
  int unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  cVar3 = *(char *)(unaff_SI + -1);
  if (cVar3 < '\0') {
    FUN_0000_055c();
    return;
  }
  if (*(char *)(unaff_DI + -1) == -4) {
    *(undefined1 *)(unaff_DI + -1) = 0xff;
  }
  else {
    pcVar1 = (char *)(unaff_DI + -1);
    *pcVar1 = *pcVar1 + '\x01';
    cVar2 = *pcVar1;
    *(undefined1 *)(unaff_DI + -1) = 0xfe;
    if (cVar2 != '\0') {
      *(char *)(unaff_DI + -1) = cVar3;
      FUN_0000_0270();
    }
  }
  bVar4 = *(byte *)0xc012 - 5;
  if (*(byte *)0xc012 < 5) {
    return;
  }
  if (3 < bVar4) {
    return;
  }
  (*(code *)*(undefined2 *)((uint)bVar4 * 2 + 0x3170))(in_BX);
  return;
}



// Address: 0000:0270

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0270(void)

{
  undefined2 uVar1;
  byte in_AL;
  undefined2 *puVar2;
  int iVar3;
  undefined2 *in_DX;
  undefined2 *puVar4;
  undefined2 *puVar5;
  undefined2 unaff_DS;
  
  if (in_AL == 0) {
    *in_DX = 0;
    puVar2 = in_DX + 0x1000;
    if ((undefined2 *)0x3fff < puVar2) {
      puVar2 = in_DX + -0xfd8;
    }
    *puVar2 = 0;
    puVar4 = puVar2 + 0x1000;
    if ((undefined2 *)0x3fff < puVar4) {
      puVar4 = puVar2 + -0xfd8;
    }
    *puVar4 = 0;
    puVar2 = puVar4 + 0x1000;
    if ((undefined2 *)0x3fff < puVar2) {
      puVar2 = puVar4 + -0xfd8;
    }
    *puVar2 = 0;
    puVar4 = puVar2 + 0x1000;
    if ((undefined2 *)0x3fff < puVar4) {
      puVar4 = puVar2 + -0xfd8;
    }
    *puVar4 = 0;
    puVar2 = puVar4 + 0x1000;
    if ((undefined2 *)0x3fff < puVar2) {
      puVar2 = puVar4 + -0xfd8;
    }
    *puVar2 = 0;
    puVar4 = puVar2 + 0x1000;
    if ((undefined2 *)0x3fff < puVar4) {
      puVar4 = puVar2 + -0xfd8;
    }
    *puVar4 = 0;
    puVar2 = puVar4 + 0x1000;
    if ((undefined2 *)0x3fff < puVar2) {
      puVar2 = puVar4 + -0xfd8;
    }
    *puVar2 = 0;
    return;
  }
  iVar3 = (uint)in_AL * 2;
  if (*(int *)(iVar3 + 0x509f) == 0) {
    *(undefined2 *)(iVar3 + 0x509f) = in_DX;
    uVar1 = _DAT_0000_ff2c;
    puVar2 = (undefined2 *)((uint)(byte)(in_AL - 1) * 0x10 + -0x7fd0);
    iVar3 = 4;
    do {
      puVar4 = puVar2 + 1;
      *in_DX = *puVar2;
      puVar5 = in_DX + 0x1000;
      if ((undefined2 *)0x3fff < puVar5) {
        puVar5 = in_DX + -0xfd8;
      }
      puVar2 = puVar2 + 2;
      *puVar5 = *puVar4;
      in_DX = puVar5 + 0x1000;
      if ((undefined2 *)0x3fff < in_DX) {
        in_DX = puVar5 + -0xfd8;
      }
      iVar3 = iVar3 + -1;
    } while (iVar3 != 0);
    return;
  }
  puVar2 = (undefined2 *)*(undefined2 *)(iVar3 + 0x509f);
  *in_DX = *puVar2;
  puVar4 = in_DX + 0x1000;
  if ((undefined2 *)0x3fff < puVar4) {
    puVar4 = in_DX + -0xfd8;
  }
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar5) {
    puVar5 = puVar2 + -0xfd8;
  }
  *puVar4 = *puVar5;
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = puVar4 + -0xfd8;
  }
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x3fff < puVar4) {
    puVar4 = puVar5 + -0xfd8;
  }
  *puVar2 = *puVar4;
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar5) {
    puVar5 = puVar2 + -0xfd8;
  }
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = puVar4 + -0xfd8;
  }
  *puVar5 = *puVar2;
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x3fff < puVar4) {
    puVar4 = puVar5 + -0xfd8;
  }
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar5) {
    puVar5 = puVar2 + -0xfd8;
  }
  *puVar4 = *puVar5;
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = puVar4 + -0xfd8;
  }
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x3fff < puVar4) {
    puVar4 = puVar5 + -0xfd8;
  }
  *puVar2 = *puVar4;
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar5) {
    puVar5 = puVar2 + -0xfd8;
  }
  puVar2 = puVar4 + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = puVar4 + -0xfd8;
  }
  *puVar5 = *puVar2;
  puVar4 = puVar5 + 0x1000;
  if ((undefined2 *)0x3fff < puVar4) {
    puVar4 = puVar5 + -0xfd8;
  }
  puVar5 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar5) {
    puVar5 = puVar2 + -0xfd8;
  }
  *puVar4 = *puVar5;
  return;
}



// Address: 0000:0422

void __cdecl16near FUN_0000_0422(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe900 == -1) {
    return;
  }
  if (*(char *)0xe900 == -4) {
    return;
  }
  *(undefined1 *)0xe900 = 0xff;
  FUN_0000_15cf();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x25));
  if (*(char *)(unaff_SI + 0x25) < '\0') {
    uVar1 = FUN_0000_0807();
  }
  FUN_0000_080e(uVar1);
  FUN_0000_0684();
  return;
}



// Address: 0000:045f

void __cdecl16near FUN_0000_045f(void)

{
  undefined1 uVar1;
  int in_BX;
  int unaff_SI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined1 *)(in_BX + -0x1700);
  *(undefined1 *)(in_BX + -0x1700) = 0xff;
  UNLOCK();
  *(undefined1 *)0x5092 = uVar1;
  *(undefined1 *)0x5093 = 0;
  *(undefined1 *)(in_BX + -0x16ff) = 0xff;
  FUN_0000_15cf();
  *(undefined2 *)0x5096 = *(undefined2 *)(unaff_SI + 0x24);
  FUN_0000_080e();
  thunk_FUN_0000_065a();
  return;
}



// Address: 0000:04a3

void __cdecl16near FUN_0000_04a3(void)

{
  undefined1 extraout_AH;
  undefined2 uVar1;
  int unaff_SI;
  undefined2 unaff_DS;
  
  if (*(char *)0xe91b == -1) {
    return;
  }
  if (*(char *)0xe91b == -4) {
    return;
  }
  *(undefined1 *)0xe91b = 0xff;
  FUN_0000_15cf();
  uVar1 = CONCAT11(extraout_AH,*(char *)(unaff_SI + 0x24));
  if (*(char *)(unaff_SI + 0x24) < '\0') {
    uVar1 = FUN_0000_0807();
  }
  FUN_0000_080e(uVar1);
  FUN_0000_0684();
  return;
}



// Address: 0000:04db

void __cdecl16near FUN_0000_04db(void)

{
  undefined1 uVar1;
  int extraout_DX;
  int in_BX;
  int unaff_SI;
  undefined1 *unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *unaff_DI;
  *unaff_DI = 0xff;
  UNLOCK();
  *(undefined1 *)0x5092 = uVar1;
  LOCK();
  uVar1 = unaff_DI[0x1c];
  unaff_DI[0x1c] = 0xff;
  UNLOCK();
  *(undefined1 *)0x5093 = uVar1;
  FUN_0000_15cf();
  FUN_0000_080e();
  if ((*(char *)0x5092 != -1) && (*(char *)0x5092 != -4)) {
    if ((char)extraout_DX < '\0') {
      FUN_0000_0807(in_BX * 2 + *(int *)0x506d,unaff_SI + 0x25);
    }
    FUN_0000_0684();
  }
  if (((*(char *)0x5073 != '\x01') && (*(char *)0x5093 != -1)) && (*(char *)0x5093 != -4)) {
    if (extraout_DX < 0) {
      FUN_0000_0807();
    }
    FUN_0000_0684();
  }
  return;
}



// Address: 0000:055c

void __cdecl16near FUN_0000_055c(void)

{
  undefined2 uVar1;
  undefined1 uVar2;
  undefined1 in_BL;
  int iVar3;
  undefined1 *unaff_SI;
  int unaff_DI;
  undefined2 unaff_DS;
  
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + -1);
  *(undefined2 *)(unaff_DI + -1) = 0xfffe;
  UNLOCK();
  *(undefined2 *)0x5092 = uVar1;
  LOCK();
  uVar1 = *(undefined2 *)(unaff_DI + 0x1b);
  *(undefined2 *)(unaff_DI + 0x1b) = 0xffff;
  UNLOCK();
  *(undefined2 *)0x5094 = uVar1;
  iVar3 = 0x5096;
  *(undefined1 *)0x5097 = *unaff_SI;
  FUN_0000_15cf();
  *(undefined2 *)(iVar3 + 2) = *(undefined2 *)(unaff_SI + 0x23);
  *(undefined1 *)0x5074 = in_BL;
  *(char *)0x5075 = '\x12' - *(char *)0x5073;
  uVar2 = FUN_0000_080e();
  *(undefined1 *)0x5096 = uVar2;
  thunk_FUN_0000_065a();
  if (*(char *)0x5073 != '\x01') {
    thunk_FUN_0000_065a();
    if ((*(char *)0xff34 != '\0') && (*(char *)0xff2f != '\0')) {
      FUN_0000_085f();
    }
  }
  return;
}



// Address: 0000:05d3

void __cdecl16near FUN_0000_05d3(void)

{
  char *pcVar1;
  char *pcVar2;
  char cVar3;
  int iVar4;
  char extraout_DL;
  int in_BX;
  char *pcVar5;
  char *unaff_SI;
  char *pcVar6;
  char *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  LOCK();
  cVar3 = unaff_DI[-1];
  unaff_DI[-1] = -2;
  UNLOCK();
  *(char *)0x5092 = cVar3;
  LOCK();
  cVar3 = unaff_DI[0x1b];
  unaff_DI[0x1b] = -1;
  UNLOCK();
  *(char *)0x5093 = cVar3;
  FUN_0000_15cf();
  cVar3 = FUN_0000_080e();
  if ((*(char *)0x5092 != -1) && (*(char *)0x5092 != -4)) {
    if (cVar3 < '\0') {
      FUN_0000_0807(in_BX * 2 + *(int *)0x506d,unaff_SI + 0x24);
    }
    FUN_0000_0684();
  }
  if (((*(char *)0x5073 != '\x01') && (*(char *)0x5093 != -1)) && (*(char *)0x5093 != -4)) {
    if (extraout_DL < '\0') {
      FUN_0000_0807();
    }
    FUN_0000_0684();
  }
  while( true ) {
    FUN_0000_15cf();
    *(int *)0x506d = *(int *)0x506d + 0x140;
    pcVar1 = (char *)0x5073;
    *pcVar1 = *pcVar1 + -1;
    if (*pcVar1 == '\0') {
      return;
    }
    FUN_0000_0ed5();
    if (unaff_SI[7] < '\0') {
      FUN_0000_04db();
    }
    iVar4 = 6;
    pcVar2 = unaff_SI + 8;
    do {
      pcVar6 = unaff_DI;
      pcVar5 = pcVar2;
      if (*pcVar5 != *pcVar6) {
        FUN_0000_0128();
      }
      if (pcVar5[1] != pcVar6[1]) {
        FUN_0000_0128();
      }
      if (pcVar5[2] != pcVar6[2]) {
        FUN_0000_0128();
      }
      if (pcVar5[3] != pcVar6[3]) {
        FUN_0000_0128();
      }
      iVar4 = iVar4 + -1;
      pcVar2 = pcVar5 + 4;
      unaff_DI = pcVar6 + 4;
    } while (iVar4 != 0);
    if (pcVar5[4] != pcVar6[4]) {
      FUN_0000_0128();
    }
    if (pcVar5[5] != pcVar6[5]) {
      FUN_0000_0128();
    }
    if (pcVar5[6] != pcVar6[6]) {
      FUN_0000_0128();
    }
    unaff_SI = pcVar5 + 8;
    unaff_DI = pcVar6 + 8;
    if (pcVar5[7] < '\0') break;
    if (pcVar5[7] != pcVar6[7]) {
      FUN_0000_0128();
    }
  }
  FUN_0000_05d3();
  return;
}



// Address: 0000:0657

void __cdecl16near thunk_FUN_0000_065a(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_0807(0x65a);
      in_DX = extraout_DX;
    }
    FUN_0000_0684(in_DX);
  }
  return;
}



// Address: 0000:065a

void __cdecl16near FUN_0000_065a(void)

{
  undefined2 in_DX;
  undefined2 extraout_DX;
  char *unaff_BP;
  char *unaff_DI;
  undefined2 unaff_DS;
  
  if ((*unaff_BP != -1) && (*unaff_BP != -4)) {
    if (*unaff_DI < '\0') {
      FUN_0000_0807();
      in_DX = extraout_DX;
    }
    FUN_0000_0684(in_DX);
  }
  return;
}



// Address: 0000:0684

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_0684(void)

{
  char in_AL;
  byte bVar1;
  undefined2 unaff_DS;
  
  bVar1 = *(byte *)0x5076;
  if ((in_AL != '\0') && (-1 < in_AL)) {
    bVar1 = bVar1 | 0x80;
  }
  _DAT_0000_506b = *(undefined2 *)((uint)(bVar1 & 0x7f) * 2 + 0x500f);
  if (-1 < (char)bVar1) {
    FUN_0000_0726();
    FUN_0000_078e();
    return;
  }
  FUN_0000_06f8();
  FUN_0000_078e();
  return;
}



// Address: 0000:06f8

void __cdecl16near FUN_0000_06f8(void)

{
  uint uVar1;
  int iVar2;
  uint *unaff_BP;
  uint *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  FUN_0000_07f9();
  iVar2 = 8;
  do {
    *unaff_DI = *unaff_DI & *unaff_BP;
    uVar1 = FUN_0000_0731();
    *unaff_DI = *unaff_DI | uVar1;
    unaff_BP = unaff_BP + 1;
    unaff_DI = unaff_DI + 1;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Address: 0000:0726

void __cdecl16near FUN_0000_0726(void)

{
  undefined2 *puVar1;
  undefined2 uVar2;
  int iVar3;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  
  iVar3 = 8;
  do {
    uVar2 = FUN_0000_0731();
    puVar1 = unaff_DI;
    unaff_DI = unaff_DI + 1;
    *puVar1 = uVar2;
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return;
}



// Address: 0000:0731

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined2 __cdecl16near FUN_0000_0731(void)

{
  uint in_AX;
  
  return CONCAT11(*(char *)((in_AX >> 0xc) + _DAT_0000_506b) << 4 |
                  *(byte *)((uint)((byte)(in_AX >> 8) & 0xf) + _DAT_0000_506b),
                  *(char *)((in_AX >> 4 & 0xf) + _DAT_0000_506b) << 4 |
                  *(byte *)((uint)((byte)in_AX & 0xf) + _DAT_0000_506b));
}



// Address: 0000:078e

void __cdecl16near FUN_0000_078e(void)

{
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 *puVar1;
  undefined2 *puVar2;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  *unaff_DI = *unaff_SI;
  puVar2 = unaff_DI + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = unaff_DI + -0xfd8;
  }
  *puVar2 = unaff_SI[1];
  puVar1 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar1) {
    puVar1 = puVar2 + -0xfd8;
  }
  *puVar1 = unaff_SI[2];
  puVar2 = puVar1 + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = puVar1 + -0xfd8;
  }
  *puVar2 = unaff_SI[3];
  puVar1 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar1) {
    puVar1 = puVar2 + -0xfd8;
  }
  *puVar1 = unaff_SI[4];
  puVar2 = puVar1 + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = puVar1 + -0xfd8;
  }
  *puVar2 = unaff_SI[5];
  puVar1 = puVar2 + 0x1000;
  if ((undefined2 *)0x3fff < puVar1) {
    puVar1 = puVar2 + -0xfd8;
  }
  *puVar1 = unaff_SI[6];
  puVar2 = puVar1 + 0x1000;
  if ((undefined2 *)0x3fff < puVar2) {
    puVar2 = puVar1 + -0xfd8;
  }
  *puVar2 = unaff_SI[7];
  return;
}



// Address: 0000:07f9

void __cdecl16near FUN_0000_07f9(void)

{
  undefined2 *puVar1;
  undefined2 *puVar2;
  int iVar3;
  undefined2 *unaff_SI;
  undefined2 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  for (iVar3 = 8; iVar3 != 0; iVar3 = iVar3 + -1) {
    puVar2 = unaff_DI;
    unaff_DI = unaff_DI + 1;
    puVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    *puVar2 = *puVar1;
  }
  return;
}



// Address: 0000:0807

undefined1 __cdecl16near FUN_0000_0807(void)

{
  byte in_AL;
  
  return *(undefined1 *)(ulong)((in_AL & 0x7f) + 0xed20);
}



// Address: 0000:080e

undefined2 __cdecl16near FUN_0000_080e(void)

{
  undefined1 uVar1;
  byte in_AL;
  char cVar2;
  int iVar3;
  char *pcVar4;
  int iVar5;
  undefined2 unaff_DS;
  
  uVar1 = *(undefined1 *)((in_AL & 0x7f) + 0xed20);
  iVar3 = (uint)(in_AL & 0x7f) * 0x10 + *(int *)0xc010;
  iVar5 = -0x5f90;
  if ((*(byte *)(iVar3 + 5) & 0x80) == 0) {
    iVar5 = -0x5fd0;
  }
  pcVar4 = (char *)((uint)(*(byte *)(iVar3 + 6) & 0xf) * 5 +
                   *(int *)((uint)(byte)((*(byte *)(iVar3 + 4) & 0x1f) * '\x02') + iVar5));
  cVar2 = *pcVar4;
  if ((*(char *)0xff34 == '\0') && ((*(byte *)(iVar3 + 5) & 0x20) != 0)) {
    cVar2 = cVar2 + '\x03';
  }
  *(char *)0x5076 = cVar2;
  return CONCAT11((char)((uint)pcVar4 >> 8),uVar1);
}



// Address: 0000:085f

void __cdecl16near FUN_0000_085f(void)

{
  byte bVar1;
  byte *pbVar2;
  undefined2 unaff_CS;
  undefined2 unaff_DS;
  
  if (0xf < *(byte *)0x5075) {
    return;
  }
  bVar1 = (*pcRam0000011a)();
  if ((bVar1 & 0xf) < 0xe) {
    return;
  }
  bVar1 = 0;
  for (pbVar2 = (byte *)0xeda0; *pbVar2 != 0xff; pbVar2 = pbVar2 + 4) {
    bVar1 = bVar1 + 1;
  }
  if (0x1f < bVar1) {
    return;
  }
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x5074;
  if (bVar1 == 0xff) {
    bVar1 = 4;
  }
  if (0x1a < bVar1) {
    bVar1 = 0x1a;
  }
  *pbVar2 = bVar1;
  do {
    bVar1 = (*pcRam0000011a)();
  } while ((bVar1 & 3) == 3);
  bVar1 = ((bVar1 & 3) - 1) + *(char *)0x5075;
  if (bVar1 == 0xff) {
    bVar1 = 0;
  }
  pbVar2[1] = bVar1;
  pbVar2[2] = 3;
  bVar1 = (*pcRam0000011a)();
  pbVar2[3] = *(byte *)(ulong)((bVar1 & 3) + 0x38d1);
  pbVar2[4] = 0xff;
  return;
}



// Address: 0000:0ed5

void __cdecl16near FUN_0000_0ed5(void)

{
  byte bVar1;
  byte bVar2;
  undefined2 unaff_DS;
  
  bVar1 = 0x12 - *(char *)0x5073;
  if (*(char *)0xff43 == '\0') {
    if ((byte)(*(char *)0x84 - 2U) == bVar1) {
      FUN_0000_1147();
    }
    return;
  }
  bVar2 = *(char *)0x84 - 5;
  if (bVar1 < bVar2) {
    return;
  }
  if (bVar1 == bVar2) {
    FUN_0000_0fff();
    FUN_0000_1147();
    return;
  }
  if ((byte)(*(char *)0x84 + 5U) != bVar1) {
    return;
  }
  FUN_0000_10b0();
  return;
}



// Address: 0000:0fff

void __cdecl16near FUN_0000_0fff(void)

{
  undefined2 unaff_DS;
  
  if (*(char *)0xff44 == '\0') {
    return;
  }
  FUN_0000_1041();
  *(undefined1 *)0xff44 = 0;
  return;
}



// Address: 0000:1018

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1018(void)

{
  int iVar1;
  undefined2 *puVar2;
  undefined2 *puVar3;
  undefined2 *puVar4;
  undefined2 unaff_CS;
  
  puVar4 = (undefined2 *)0x519f;
  iVar1 = 0x20;
  puVar2 = _DAT_0000_5078;
  do {
    *puVar4 = *puVar2;
    puVar4[1] = puVar2[1];
    puVar3 = puVar4 + 3;
    puVar4[2] = puVar2[2];
    puVar4 = puVar4 + 4;
    *puVar3 = puVar2[3];
    puVar3 = puVar2 + 0x1000;
    if ((undefined2 *)0x3fff < puVar3) {
      puVar3 = puVar2 + -0xfd8;
    }
    iVar1 = iVar1 + -1;
    puVar2 = puVar3;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:1041

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1041(void)

{
  int iVar1;
  undefined2 *puVar2;
  undefined2 *puVar3;
  undefined2 *puVar4;
  undefined2 unaff_DS;
  
  puVar2 = (undefined2 *)0x519f;
  iVar1 = 0x20;
  puVar3 = _DAT_0000_5078;
  do {
    *puVar3 = *puVar2;
    puVar3[1] = puVar2[1];
    puVar4 = puVar2 + 3;
    puVar3[2] = puVar2[2];
    puVar2 = puVar2 + 4;
    puVar3[3] = *puVar4;
    puVar4 = puVar3 + 0x1000;
    if ((undefined2 *)0x3fff < puVar4) {
      puVar4 = puVar3 + -0xfd8;
    }
    iVar1 = iVar1 + -1;
    puVar3 = puVar4;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:1066

void __cdecl16near FUN_0000_1066(void)

{
  int iVar1;
  int iVar2;
  byte *pbVar3;
  byte *pbVar4;
  undefined2 unaff_DS;
  
  pbVar3 = (byte *)((uint)(*(char *)0x84 + *(char *)0x507c & 0x3f) * 0x24 +
                    (uint)(byte)(*(char *)0x83 + *(char *)0x507d + 4) + *(int *)0xff31);
  FUN_0000_15cf();
  iVar1 = 4;
  do {
    iVar2 = 4;
    do {
      pbVar4 = pbVar3;
      *(undefined2 *)((uint)(*pbVar4 & 0x7f) * 2 + 0x509f) = 0;
      iVar2 = iVar2 + -1;
      pbVar3 = pbVar4 + 1;
    } while (iVar2 != 0);
    pbVar3 = pbVar4 + 0x21;
    FUN_0000_15cf();
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:10b0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_10b0(void)

{
  char *pcVar1;
  undefined2 uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  char *pcVar7;
  uint *puVar8;
  uint *puVar9;
  uint *puVar10;
  undefined2 unaff_DS;
  
  if (*(char *)0xff43 != '\0') {
    *(undefined1 *)0xff44 = 0xff;
    FUN_0000_1066();
    FUN_0000_1018();
    uVar2 = _DAT_0000_ff2c;
    iVar4 = 4;
    pcVar7 = _DAT_0000_507a;
    puVar8 = _DAT_0000_5078;
    do {
      iVar5 = 4;
      puVar10 = puVar8;
      do {
        pcVar1 = pcVar7;
        pcVar7 = pcVar7 + 1;
        if (*pcVar1 == -1) {
          puVar10 = puVar10 + 0xa0;
        }
        else {
          iVar6 = 8;
          puVar9 = puVar10;
          do {
            uVar3 = FUN_0000_16d3();
            *puVar9 = *puVar9 | uVar3;
            puVar10 = puVar9 + 0x1000;
            if ((uint *)0x3fff < puVar10) {
              puVar10 = puVar9 + -0xfd8;
            }
            iVar6 = iVar6 + -1;
            puVar9 = puVar10;
          } while (iVar6 != 0);
        }
        iVar5 = iVar5 + -1;
      } while (iVar5 != 0);
      puVar8 = puVar8 + 1;
      iVar4 = iVar4 + -1;
    } while (iVar4 != 0);
    return;
  }
  return;
}



// Address: 0000:1147

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __cdecl16near FUN_0000_1147(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  undefined2 unaff_DS;
  int iVar4;
  
  if (*(char *)0xff37 != '\0') {
    return;
  }
  *(undefined1 *)0xff37 = 0xff;
  iVar1 = 3;
  iVar3 = _DAT_0000_506f;
  do {
    iVar2 = 3;
    do {
      iVar4 = iVar3;
      FUN_0000_078e(iVar3);
      iVar3 = iVar4 + 2;
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    iVar3 = iVar4 + 0x13c;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Address: 0000:15cf

void __cdecl16near FUN_0000_15cf(void)

{
  uint unaff_SI;
  
  if (unaff_SI < 0xe900) {
    return;
  }
  return;
}



// Address: 0000:15db

void __cdecl16near FUN_0000_15db(void)

{
  uint unaff_SI;
  
  if (0xdfff < unaff_SI) {
    return;
  }
  return;
}



// Address: 0000:16d3

int __cdecl16near FUN_0000_16d3(void)

{
  uint uVar1;
  uint in_AX;
  int iVar2;
  int iVar3;
  byte bVar4;
  bool bVar5;
  
  iVar2 = 0;
  iVar3 = 8;
  do {
    bVar5 = CARRY2(in_AX,in_AX);
    uVar1 = in_AX * 2;
    in_AX = in_AX * 4;
    bVar4 = 0;
    if ((char)(bVar5 * '\x02' + CARRY2(uVar1,uVar1)) != '\0') {
      bVar4 = 3;
    }
    iVar2 = CONCAT11((char)((uint)(iVar2 * 4) >> 8),(byte)(iVar2 * 4) | bVar4);
    iVar3 = iVar3 + -1;
  } while (iVar3 != 0);
  return iVar2;
}



