/* Decompiled from chunk_30.bin */
/* Generated by Ghidra */

// Address: 0000:0000

void FUN_0000_0000(void)

{
  code *pcVar1;
  
                    /* WARNING: Does not return */
  pcVar1 = (code *)invalidInstructionException();
  (*pcVar1)();
}



