/* Decompiled from chunk_08.bin */
/* Generated by Ghidra */

// Address: 0000:0000

void __cdecl16far FUN_0000_0000(void)

{
  undefined2 *puVar1;
  int iVar2;
  undefined2 *puVar3;
  
  DAT_0000_335b = 0;
  puVar3 = (undefined2 *)0x0;
  for (iVar2 = 0x2680; iVar2 != 0; iVar2 = iVar2 + -1) {
    puVar1 = puVar3;
    puVar3 = puVar3 + 1;
    *puVar1 = 0;
  }
  FUN_0000_0060();
  FUN_0000_0060();
  FUN_0000_0082();
  iVar2 = 0x10;
  do {
    FUN_0000_0291();
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  iVar2 = 0x10;
  do {
    FUN_0000_0291();
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  FUN_0000_02b3();
  return;
}



// Address: 0000:0060

void __cdecl16near FUN_0000_0060(void)

{
  char *pcVar1;
  undefined1 *puVar2;
  undefined2 uVar3;
  char cVar4;
  byte bVar5;
  uint uVar6;
  char cVar7;
  char *unaff_SI;
  char *pcVar8;
  undefined1 *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  uVar6 = 0;
  do {
    pcVar8 = unaff_SI + 1;
    uVar3 = CONCAT11(1,*unaff_SI);
    if (*unaff_SI == '\x06') {
      pcVar1 = pcVar8;
      pcVar8 = unaff_SI + 3;
      uVar3 = *(undefined2 *)pcVar1;
    }
    do {
      puVar2 = unaff_DI;
      unaff_DI = unaff_DI + 1;
      *puVar2 = (char)uVar3;
      cVar4 = (char)uVar6;
      cVar7 = (char)(uVar6 >> 8) + '\x01';
      uVar6 = CONCAT11(cVar7,cVar4);
      if ((cVar7 == '8') && (bVar5 = cVar4 + 1, uVar6 = (uint)bVar5, bVar5 == 0x58)) {
        return;
      }
      cVar4 = (char)((uint)uVar3 >> 8) + -1;
      uVar3 = CONCAT11(cVar4,(char)uVar3);
      unaff_SI = pcVar8;
    } while (cVar4 != '\0');
  } while( true );
}



// Address: 0000:0082

void FUN_0000_0082(void)

{
  undefined2 unaff_DS;
  
                    /* WARNING: Could not recover jumptable at 0x0000008a. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)*(byte *)&DAT_0000_335b * 2 + 0x338a))();
  return;
}



// Address: 0000:0291

void __cdecl16near FUN_0000_0291(void)

{
  byte *pbVar1;
  byte bVar2;
  byte bVar3;
  char cVar4;
  byte *unaff_SI;
  byte *unaff_DI;
  undefined2 unaff_ES;
  undefined2 unaff_DS;
  
  cVar4 = '\0';
  do {
    pbVar1 = unaff_SI;
    unaff_SI = unaff_SI + 1;
    bVar2 = *pbVar1;
    bVar3 = 1;
    if ((bVar2 & 0xf0) == 0x60) {
      bVar3 = bVar2 & 0xf;
      bVar2 = 0;
    }
    do {
      pbVar1 = unaff_DI;
      unaff_DI = unaff_DI + 1;
      *pbVar1 = bVar2;
      cVar4 = cVar4 + '\x01';
      bVar3 = bVar3 - 1;
    } while (bVar3 != 0);
  } while (cVar4 != '\x1c');
  return;
}



// Address: 0000:02b3

void FUN_0000_02b3(void)

{
  undefined2 unaff_DS;
  
                    /* WARNING: Could not recover jumptable at 0x000002bb. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined2 *)((uint)*(byte *)&DAT_0000_335b * 2 + 0x35bb))();
  return;
}



